/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_17131615_proyecto_04;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author alex
 */
public class PB_17131615_Frame_04 extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form PB_17131615_Frame_04
     */
    private String[] signos = {",","¡!","¿?",".","()","...",">","<","-","_","°","#","$","%","&","/","=","*","+","[]","{}",";"};
    
    private String []dato = new String[12];
    private Boton [] pares = new Boton[12];
    private JFileChooser jfch = new JFileChooser();
    private int intentos;
    private int pregunta = 0;
    private int parEncontrados;
    String comp;
    Boton botond =new Boton();
    Boton apariencia = new Boton();
    private int posX,posY;
   private int tama=24;
    
    public PB_17131615_Frame_04() {
        initComponents();
        comenzar();
    }
    
    public void comenzar()
    {
        Random azar = new Random();
        
        int j=0;
        int x = 30;
        int y = 50;
        for (int i = 0; i <dato.length; i++) 
        {
            
            if(i<6)
            dato[i] = signos[azar.nextInt(signos.length)];
            else
                dato[i] = dato[j++];
        }
        for (int i = 0; i <12; i++) 
        {  
            
            pares[i]= new Boton(dato[i],"Arial",tama,2);
            pares[i].setLocation(x, y);
            
            x+=100;
            
            if ((i+1) % 4 == 0)
            {
                y+=100;
                x= 30;
            }
            
            pares[i].addActionListener(this);
            this.add(pares[i]);  
        }
        
        parEncontrados = 0;
        intentos = 0;
        
        jLabPares.setText(parEncontrados+"");
        jLabIntentos.setText(intentos+"");
    }
    public int posicion(int x, int y)
    {
        int pos;
        if(x ==30 && y == 50)
            pos = 0;
        else  
            if(x ==130 && y == 50)
            pos = 1;
                else 
                    if(x ==230 && y == 50)
                        pos = 2;
                    else 
                        if(x ==330 && y == 50)
                            pos = 3;
                        else 
                            if(x ==30 && y == 150)
                                pos = 4;
                            else
                                if(x ==130 && y == 150)
                                    pos = 5;
                                else
                                    if(x ==230 && y == 150)
                                    pos = 6;
                                    else
                                        if(x ==330 && y == 150)
                                            pos = 7;
                                        else 
                                            if(x ==30 && y == 250)
                                                pos = 8;
                                            else
                                                if(x ==130 && y == 250)
                                                    pos = 9;
                                                else
                                                    if(x ==230 && y == 250)
                                                    pos = 10;
                                                    else
                                                         pos = 11;
        
        return pos;
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabPares = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabIntentos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuNuevo = new javax.swing.JMenuItem();
        jMenuGuardar = new javax.swing.JMenuItem();
        jMenuAbrir = new javax.swing.JMenuItem();
        jMenuCerrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuFuente = new javax.swing.JMenuItem();
        jMenuColor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 255, 204));
        jLabel1.setText("Pares encontrados:");

        jLabPares.setBackground(new java.awt.Color(51, 255, 204));
        jLabPares.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabPares.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(0, 255, 204));
        jLabel3.setText("N° de Intentos:");

        jLabIntentos.setBackground(new java.awt.Color(255, 255, 51));
        jLabIntentos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabIntentos.setOpaque(true);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pb_17131615_proyecto_04/2018-05-28 (2).png"))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(153, 255, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Alejandro Cervantes Rosales");
        jLabel4.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(255, 255, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("N° de Control: 17131615");
        jLabel5.setOpaque(true);

        jLabel6.setBackground(new java.awt.Color(102, 255, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Proyecto 04");
        jLabel6.setOpaque(true);

        jMenu1.setText("Archivo");

        jMenuNuevo.setText("Nuevo");
        jMenuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuNuevo);

        jMenuGuardar.setText("Guardar");
        jMenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuGuardar);

        jMenuAbrir.setText("Abrir");
        jMenuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAbrir);

        jMenuCerrar.setText("Cerrar");
        jMenuCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCerrarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCerrar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar Boton");

        jMenuFuente.setText("Fuente");
        jMenuFuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFuenteActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuFuente);

        jMenuColor.setText("Color");
        jMenuColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuColorActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuColor);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabPares, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabPares, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuCerrarActionPerformed

    private void jMenuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNuevoActionPerformed
        // TODO add your handling code here:
        for (int i=0; i<pares.length; i++)
            remove(pares[i]);
        
        comenzar();
        
        repaint();
    }//GEN-LAST:event_jMenuNuevoActionPerformed

    private void jMenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGuardarActionPerformed
        // TODO add your handling code here:
        jfch.showSaveDialog(jMenu1);
        File archivo = jfch.getSelectedFile();
        
        if (archivo == null)
            return;
        
        FileWriter fw = null;
        PrintWriter pw = null;
        
        try
        {
            fw = new FileWriter(archivo);
            pw = new PrintWriter(fw);

            pw.println(parEncontrados);
            pw.println(intentos);
            
            for (int i=0; i<pares.length; i++)
            {
                pw.println(pares[i].getSigno());
                pw.println(pares[i].isEnabled());
                //pw.println(pares[i].getBackground().getRGB());
            }
        }
        catch(IOException ex)
        {
            Logger.getLogger(PB_17131615_Frame_04.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            if (pw!=null)
                pw.close();
            if (fw!=null)
                try {
                    fw.close();
            } catch (IOException ex) {
                Logger.getLogger(PB_17131615_Frame_04.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuGuardarActionPerformed

    private void jMenuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAbrirActionPerformed
        // TODO add your handling code here:
        jfch.showOpenDialog(jMenu1);
        File archivo = jfch.getSelectedFile();
        
        if (archivo == null)
            return;
        
        FileReader fr = null;
        BufferedReader br = null;
        
        try
        {
            fr = new FileReader(archivo);
            br = new BufferedReader(fr);

            parEncontrados = Integer.parseInt(br.readLine());
            intentos = Integer.parseInt(br.readLine());
            
            jLabPares.setText(parEncontrados+"");
            jLabIntentos.setText(intentos+"");
            
            for (int i=0; i<pares.length; i++)
            {
                pares[i].setSigno(br.readLine());
                
                if (br.readLine().equals("true"))
                {
                    pares[i].setText("");
                    pares[i].setEnabled(true);
                }
                else
                {
                    pares[i].mostrarSigno();
                    pares[i].setEnabled(false);
                }
                
            }
        }
        catch (FileNotFoundException ex)
        {
            Logger.getLogger(PB_17131615_Frame_04.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (IOException ex)
        {
            Logger.getLogger(PB_17131615_Frame_04.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            try {
                if (br != null)
                    br.close();
                if (fr != null)
                    fr.close();
            } catch (IOException ex) {
                Logger.getLogger(PB_17131615_Frame_04.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jMenuAbrirActionPerformed

    private void jMenuColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuColorActionPerformed

    private void jMenuFuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFuenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuFuenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PB_17131615_Frame_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PB_17131615_Frame_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PB_17131615_Frame_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PB_17131615_Frame_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PB_17131615_Frame_04().setVisible(true);
            }
        });
    }

    
    public void actionPerformed(ActionEvent ae) {
        pregunta++;
        Boton botonc = (Boton)ae.getSource(); 
        botonc.mostrarSigno();
        if((pregunta%2) != 0)
        {
            
            botond.setSigno(botonc.getSigno());
            posX =botonc.getX();
            posY =botonc.getY();
            botonc.setEnabled(false); 
            
            return;
        }
        
         if((pregunta%2)==0)
         {
            botonc.mostrarSigno();
            intentos++;
            jLabIntentos.setText(intentos+"");
        
        if (botond.getSigno().equals(botonc.getSigno()))
        {
            botonc.setEnabled(false);
            parEncontrados++;
            jLabPares.setText(parEncontrados+"");
        }  
        else    
            {
             pares[posicion(posX,posY)].setEnabled(true);
             pares[posicion(posX,posY)].setText("");
             botonc.setText("");
            }
         }
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabIntentos;
    private javax.swing.JLabel jLabPares;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuAbrir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCerrar;
    private javax.swing.JMenuItem jMenuColor;
    private javax.swing.JMenuItem jMenuFuente;
    private javax.swing.JMenuItem jMenuGuardar;
    private javax.swing.JMenuItem jMenuNuevo;
    // End of variables declaration//GEN-END:variables
}
