/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_03_272019_AplicacionNominaEmpleado;

import java.awt.Color;
import java.text.DecimalFormat;


/**
 *
 * @author aa623
 */
public class jFrameRegistro extends javax.swing.JFrame {

    /**
     * Creates new form jFrameRegistro
     */
    private DecimalFormat df = new DecimalFormat("###,###,#00.00");
    
    jFrameMenu jfMenu;
    
    MiRandom azar = new MiRandom();
    
    public jFrameRegistro(jFrameMenu jfm) { //es la que manda a llamar al frame menu
        initComponents();
        
        jfMenu = jfm; 
        
        jRBEmpleado.setSelected(true);
        ocultar();
        
        jLabEmpReg.setText(jfMenu.getEmpleadosRegistrados()+"");

    }
    
    public void ocultar()
    {
        //Oculta las etiquetas en el frame
        jLabPiezas.setVisible(false);
        jLabPrecio.setVisible(false);
        jLabVentas.setVisible(false);
        jLabComision.setVisible(false);
        jLabDias.setVisible(false);
        jLabSueldo.setVisible(false);
        jLabBono.setVisible(false);
        
        //Oculta los campos de texto en el frame
        jTextPiezas.setVisible(false);
        jTextPrecio.setVisible(false);
        jTextVentas.setVisible(false);
        jTextComision.setVisible(false);
        jTextDias.setVisible(false);
        jTextSueldo.setVisible(false);
        jTextBono.setVisible(false);
        
        //Pone en los campos de textos puras cadenas vacias
        jTextNumero.setText("");
        jTextNombre.setText("");
        jTextPiezas.setText("");
        jTextPrecio.setText("");
        jTextVentas.setText("");
        jTextComision.setText("");
        jTextDias.setText("");
        jTextSueldo.setText("");
        jTextBono.setText("");
        
    }        
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jButRegresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabEmpReg = new javax.swing.JLabel();
        jRBEmpleado = new javax.swing.JRadioButton();
        jRBTaller = new javax.swing.JRadioButton();
        jRBVentas = new javax.swing.JRadioButton();
        jRBAdmin = new javax.swing.JRadioButton();
        jRBEjecutivo = new javax.swing.JRadioButton();
        jButAleatorios = new javax.swing.JButton();
        jButGrabar = new javax.swing.JButton();
        jButCancelar = new javax.swing.JButton();
        jLabNumero = new javax.swing.JLabel();
        jTextNumero = new javax.swing.JTextField();
        jLabNombre = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jLabPiezas = new javax.swing.JLabel();
        jTextPiezas = new javax.swing.JTextField();
        jLabPrecio = new javax.swing.JLabel();
        jTextPrecio = new javax.swing.JTextField();
        jLabVentas = new javax.swing.JLabel();
        jTextVentas = new javax.swing.JTextField();
        jLabComision = new javax.swing.JLabel();
        jTextComision = new javax.swing.JTextField();
        jLabSueldo = new javax.swing.JLabel();
        jTextSueldo = new javax.swing.JTextField();
        jLabDias = new javax.swing.JLabel();
        jTextDias = new javax.swing.JTextField();
        jLabBono = new javax.swing.JLabel();
        jTextBono = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRO DE EMPLEADOS");

        jButRegresar.setText("REGRESAR");
        jButRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegresarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Empleados registrados:");

        jLabEmpReg.setBackground(new java.awt.Color(204, 153, 0));
        jLabEmpReg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabEmpReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabEmpReg.setOpaque(true);

        buttonGroup1.add(jRBEmpleado);
        jRBEmpleado.setText("Empleado");
        jRBEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBEmpleadoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBTaller);
        jRBTaller.setText("Taller");
        jRBTaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBTallerActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBVentas);
        jRBVentas.setText("Ventas");
        jRBVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBVentasActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBAdmin);
        jRBAdmin.setText("Administrativo");
        jRBAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBAdminActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBEjecutivo);
        jRBEjecutivo.setText("Ejecutivo");
        jRBEjecutivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBEjecutivoActionPerformed(evt);
            }
        });

        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jButGrabar.setText("Grabar");
        jButGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButGrabarActionPerformed(evt);
            }
        });

        jButCancelar.setText("Cancelar");

        jLabNumero.setText("Numero:");
        jLabNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabNumeroMouseEntered(evt);
            }
        });

        jLabNombre.setText("Nombre:");

        jLabPiezas.setText("Piezas:");

        jLabPrecio.setText("Precio Unitario $");

        jLabVentas.setText("Ventas $");

        jLabComision.setText("% Comision");

        jLabSueldo.setText("Sueldo Diario $");

        jLabDias.setText("Dias Trabajados");

        jLabBono.setText("Bono $");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabEmpReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButAleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRBAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRBEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRBEjecutivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRBTaller, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBVentas))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabSueldo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabDias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabComision, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabVentas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabPrecio))
                            .addComponent(jLabBono, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextBono, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextComision)
                                .addComponent(jTextDias)
                                .addComponent(jTextSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextPrecio)
                                .addComponent(jTextVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBEmpleado)
                    .addComponent(jRBTaller)
                    .addComponent(jRBVentas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBAdmin)
                    .addComponent(jRBEjecutivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabNumero, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabNombre)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabPiezas)
                    .addComponent(jTextPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabVentas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabComision))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabDias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabSueldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextBono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabBono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButAleatorios)
                    .addComponent(jButCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButGrabar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabEmpReg, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegresarActionPerformed
        // TODO add your handling code here:
        //Borrar el registro 
        
        dispose(); //quita el objeto de la memoria "this"
        
        jfMenu.getEtiqueta().setBackground(Color.BLUE);
        
        jfMenu.setVisible(true);
    }//GEN-LAST:event_jButRegresarActionPerformed

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        // TODO add your handling code here: 
        jTextNumero.setText(azar.nextInt(1,1000)+"");
        jTextNombre.setText(azar.nextNombreLegal());
        
        jTextPiezas.setText(azar.nextInt(100,1000)+"");
        jTextPrecio.setText(df.format(azar.nextDouble(3,10,0.25))+"");
        
        jTextVentas.setText(azar.nextInt(5000,70000,1000)+"");
        jTextComision.setText(df.format(azar.nextDouble(2,8,0.2))+"");
        
        jTextDias.setText(azar.nextInt(6,30)+"");
        jTextSueldo.setText(azar.nextInt(102,600)+"");
        jTextBono.setText(azar.nextInt(2000,20000,500)+"");
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jRBEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBEmpleadoActionPerformed
        // TODO add your handling code here:
        ocultar();
    }//GEN-LAST:event_jRBEmpleadoActionPerformed

    private void jRBTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBTallerActionPerformed
        // TODO add your handling code here:
        ocultar();
        jLabPiezas.setVisible(true);
        jLabPrecio.setVisible(true);
        
        jTextPiezas.setVisible(true);
        jTextPrecio.setVisible(true);
    }//GEN-LAST:event_jRBTallerActionPerformed

    private void jRBVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBVentasActionPerformed
        // TODO add your handling code here:
        ocultar();
        
        jLabVentas.setVisible(true);
        jLabComision.setVisible(true);
        jTextVentas.setVisible(true);
        jTextComision.setVisible(true);
    }//GEN-LAST:event_jRBVentasActionPerformed

    private void jRBAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBAdminActionPerformed
        // TODO add your handling code here:
        ocultar();
        
        jLabDias.setVisible(true);
        jLabSueldo.setVisible(true);
        jTextDias.setVisible(true);
        jTextSueldo.setVisible(true);
        
        
    }//GEN-LAST:event_jRBAdminActionPerformed

    private void jRBEjecutivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBEjecutivoActionPerformed
        // TODO add your handling code here:
        ocultar(); 
        
        jLabDias.setVisible(true);
        jLabSueldo.setVisible(true);
        jLabBono.setVisible(true);
        
        jTextDias.setVisible(true);
        jTextSueldo.setVisible(true);
        jTextBono.setVisible(true);
    }//GEN-LAST:event_jRBEjecutivoActionPerformed

    private void jButGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButGrabarActionPerformed
        // TODO add your handling code here:
        int numero = Integer.parseInt(jTextNumero.getText()+"");
        String nombre = jTextNombre.getText();
        
        //Creamos un nuevo empleado
        if(jRBEmpleado.isSelected())
        {
            Empleado emp = new Empleado(numero,nombre);
            jfMenu.agregarEmpleado(emp);
        }    
        
        if(jRBTaller.isSelected())
        {    
            //El new Taller lo representa de manera fisica
            Taller tal = new Taller(numero,
                                    nombre,
                                    Integer.parseInt(jTextPiezas.getText()+""),
                                    Double.parseDouble(jTextPrecio.getText()+""));
            
            jfMenu.agregarEmpleado(tal);
        } 
        
         if(jRBVentas.isSelected())
        {    
            //El new Ventas lo representa de manera fisica
            Ventas ven = new Ventas(numero,
                                    nombre,
                                    Double.parseDouble(jTextVentas.getText()+""),
                                    Double.parseDouble(jTextComision.getText()+""));
            
            jfMenu.agregarEmpleado(ven);
        } 
         
        if(jRBAdmin.isSelected())
        {    
            //El new Administrativo lo representa de manera fisica
            Administrativo adm = new Administrativo(numero,
                                    nombre,
                                    Integer.parseInt(jTextDias.getText()+""),
                                    Double.parseDouble(jTextSueldo.getText()+""));
            
            jfMenu.agregarEmpleado(adm);
        } 
        
        if(jRBEjecutivo.isSelected())
        {    
            //El new Ejecutivo lo representa de manera fisica
            Ejecutivo eje = new Ejecutivo(numero,
                                    nombre,
                                    Integer.parseInt(jTextDias.getText()+""),
                                    Double.parseDouble(jTextSueldo.getText()+""),
                                    Double.parseDouble(jTextBono.getText()+""));
            
            jfMenu.agregarEmpleado(eje);
        } 
         
        jLabEmpReg.setText(jfMenu.getEmpleadosRegistrados()+""); //actualiza la etiqueta del FrameRegistro del numero de empleado
         
    }//GEN-LAST:event_jButGrabarActionPerformed

    private void jLabNumeroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabNumeroMouseEntered
        // TODO add your handling code here: 

        //Cuando el mouse pase por encima de la etiqueta ocurre el "evento"
        
        for(int i=1; i<=7;i++) //para agregar la cantidad de empleados que queramos
        {    
            switch(azar.nextInt(5))
            {
                case 0: jRBEmpleado.setSelected(true); break; //Escoge el tipo de empleado, genera aleatorios y despues graba
                case 1: jRBTaller.setSelected(true); break; //Escoge el tipo de empleado, genera aleatorios y despues graba
                case 2: jRBVentas.setSelected(true); break; //Escoge el tipo de empleado, genera aleatorios y despues graba
                case 3: jRBAdmin.setSelected(true); break;//Escoge el tipo de empleado, genera aleatorios y despues graba
                case 4: jRBEjecutivo.setSelected(true); break; //Escoge el tipo de empleado, genera aleatorios y despues graba
            } 
            jButAleatorios.doClick();
            jButGrabar.doClick();
        }
    }//GEN-LAST:event_jLabNumeroMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrameRegistro(new jFrameMenu()).setVisible(true); //Creamos un nuevo frame Menu
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButCancelar;
    private javax.swing.JButton jButGrabar;
    private javax.swing.JButton jButRegresar;
    private javax.swing.JLabel jLabBono;
    private javax.swing.JLabel jLabComision;
    private javax.swing.JLabel jLabDias;
    private javax.swing.JLabel jLabEmpReg;
    private javax.swing.JLabel jLabNombre;
    private javax.swing.JLabel jLabNumero;
    private javax.swing.JLabel jLabPiezas;
    private javax.swing.JLabel jLabPrecio;
    private javax.swing.JLabel jLabSueldo;
    private javax.swing.JLabel jLabVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRBAdmin;
    private javax.swing.JRadioButton jRBEjecutivo;
    private javax.swing.JRadioButton jRBEmpleado;
    private javax.swing.JRadioButton jRBTaller;
    private javax.swing.JRadioButton jRBVentas;
    private javax.swing.JTextField jTextBono;
    private javax.swing.JTextField jTextComision;
    private javax.swing.JTextField jTextDias;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextPiezas;
    private javax.swing.JTextField jTextPrecio;
    private javax.swing.JTextField jTextSueldo;
    private javax.swing.JTextField jTextVentas;
    // End of variables declaration//GEN-END:variables
}
