/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_18131267_proyecto_3;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aa622
 */
public class PB_18131267_Frame_03a extends javax.swing.JFrame {

    /**
     * Creates new form PB_18131267_Frame_03a
     */
    
    //Atributos que tiene el frame
    DefaultTableModel modelo;
    private int registroBandas;
    GrupoMusical[] bandas = new GrupoMusical[4];
    GrupoMusical [] dibujos = new GrupoMusical[bandas.length];
    Nacional bandaNa;
    Internacional bandaIn;
    
    public PB_18131267_Frame_03a() {
        initComponents();
        registroBandas = 4;
        
        modelo = (DefaultTableModel)jTabBandas.getModel();
        jTabBandas.setShowGrid(true);
        
        jSRenglon.setValue(1);
        
    }
    
    public int getTamano(){
        return(bandas.length);
    }
    
    public int getRegistroBandas(){
        return registroBandas;    
    }
    
    public boolean agregarGrupoMusical(GrupoMusical grupo){
        
        if(registroBandas == bandas.length)
            return false;
        
        bandas[registroBandas] = grupo;
        registroBandas++; //Incrementa el contador

        return true;
        
    }
    
       public void setGrupoMusical(GrupoMusical grupo, int posicion){
        if(posicion >=0 && posicion < bandas.length)
            bandas[posicion] = grupo;
    } 
       
       public GrupoMusical getBanda(int posicion)
    {
        if(posicion >=0 && posicion < bandas.length)
            return(bandas[posicion]);
        
        else
            return (null);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabBandas = new javax.swing.JTable();
        jButGuardar = new javax.swing.JButton();
        jButEjemplo = new javax.swing.JButton();
        jButDiagrama = new javax.swing.JButton();
        jButDesfile = new javax.swing.JButton();
        jButMostrar = new javax.swing.JButton();
        jButModificar = new javax.swing.JButton();
        jSRenglon = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jTextIntegrantes = new javax.swing.JTextField();
        jTextGenero = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pb_18131267_proyecto_3/Asignacion_18131267.jpg"))); // NOI18N
        jLabel1.setOpaque(true);

        jTabBandas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Genero", "Integrantes"
            }
        ));
        jScrollPane1.setViewportView(jTabBandas);

        jButGuardar.setText("Guardar");
        jButGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButGuardarActionPerformed(evt);
            }
        });

        jButEjemplo.setText("Ejemplo");
        jButEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemploActionPerformed(evt);
            }
        });

        jButDiagrama.setText("Diagrama");
        jButDiagrama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDiagramaActionPerformed(evt);
            }
        });

        jButDesfile.setText("Desfile");
        jButDesfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDesfileActionPerformed(evt);
            }
        });

        jButMostrar.setText("Mostrar");
        jButMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButMostrarActionPerformed(evt);
            }
        });

        jButModificar.setText("Modificar");
        jButModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButModificarActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Renglon");

        jTextGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextGeneroActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");

        jLabel4.setText("Genero");

        jLabel5.setText("Integrantes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButEjemplo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButDiagrama, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(jButDesfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(32, 32, 32)
                                                .addComponent(jLabel4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 4, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSRenglon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextIntegrantes, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSRenglon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIntegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButMostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButEjemplo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButDiagrama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButDesfile)
                        .addContainerGap())
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemploActionPerformed
        // TODO add your handling code here:
         modelo.setValueAt("Cartel de Santa", 0, 0);
        modelo.setValueAt("RAP LATINO", 0, 1);
        modelo.setValueAt(1, 0, 2);
        
        modelo.setValueAt("30STM", 1, 0);
        modelo.setValueAt("ROCK", 1, 1);
        modelo.setValueAt(2, 1, 2);
        
        modelo.setValueAt("Enjambre", 2, 0);
        modelo.setValueAt("INDIE ROCK", 2, 1);
        modelo.setValueAt(5, 2, 2);

        modelo.setValueAt("SODA STEREO", 3, 0);
        modelo.setValueAt("ROCK CLASICO", 3, 1);
        modelo.setValueAt(3, 3, 2);
        
    }//GEN-LAST:event_jButEjemploActionPerformed

    private void jButModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButModificarActionPerformed
        // TODO add your handling code here:
        
        int renglon = (int)jSRenglon.getValue(); //Seleccionamos el renglon a modificar
        String banda = jTextNombre.getText();
        String genero = jTextGenero.getText();
        int integrantes = Integer.parseInt(jTextIntegrantes.getText()+"");
        
        
        modelo.setValueAt(banda, renglon-1, 0);
        modelo.setValueAt(genero, renglon-1, 1);
        modelo.setValueAt(integrantes, renglon-1, 2);
        
    }//GEN-LAST:event_jButModificarActionPerformed

    private void jTextGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextGeneroActionPerformed

    private void jButGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButGuardarActionPerformed

                BandaN1 gpo1 = new BandaN1( 
                        (String)modelo.getValueAt(1, 0),
                        (String)modelo.getValueAt(1, 1),
                        (int)modelo.getValueAt(1, 2),
                        "MONTERREY.", 2);
            
                BandaI1 gpo2 = new BandaI1( 
                        (String)modelo.getValueAt(1, 0),
                        (String)modelo.getValueAt(1, 1),
                        (int)modelo.getValueAt(1, 2),
                        "EEUU.", 2);
                                   
                BandaN2 gpo3 = new BandaN2( 
                        (String)modelo.getValueAt(2, 0),
                        (String)modelo.getValueAt(2, 1),
                        (int)modelo.getValueAt(2, 2),
                        "ZACATECAS", 2);
                                   
                BandaI2 gpo4 = new BandaI2( 
                        (String)modelo.getValueAt(3, 0),
                        (String)modelo.getValueAt(3, 1),
                        (int)modelo.getValueAt(3, 2),
                        "ARGENTINA.", 3);
                
bandas[0] = gpo1;
bandas[1] = gpo2;
bandas[2] = gpo3;
bandas[3] = gpo4;

dibujos[0] = gpo1;
dibujos[1] = gpo2;
dibujos[2] = gpo3;
dibujos[3] = gpo4;

for(int  i = 0; i <bandas.length; i++){
    for(int j = i+1; j<bandas.length; j++){
        if(bandas[i].getIntegrantes() < bandas[j].getIntegrantes()){
            
            GrupoMusical aux = bandas[i];
            bandas[i] = bandas[j];
            bandas[j] = aux;
            
            GrupoMusical auxD = dibujos[i];
            dibujos[i] = dibujos[j];
            dibujos[j] = aux;
            
        }
        
    }
}
        
    }//GEN-LAST:event_jButGuardarActionPerformed

    private void jButDesfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDesfileActionPerformed
        // TODO add your handling code here:
        
         setVisible(false); //Oculta este frame
        PB_18131267_Frame_03b jFDesfile = new PB_18131267_Frame_03b(this);
        jFDesfile.setVisible(true);
        
    }//GEN-LAST:event_jButDesfileActionPerformed

    private void jButMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButMostrarActionPerformed
        // TODO add your handling code here:
        
         
        for(int i = 0; i < 1; i++){
            for(int j = 0; j<bandas.length; j++){
                
                dibujos[j].mover(this, bandas);
                
                try {
                Thread.sleep(90);
                } catch (InterruptedException ex) {
                Logger.getLogger(PB_18131267_Frame_03a.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        }
        
    }//GEN-LAST:event_jButMostrarActionPerformed

    private void jButDiagramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDiagramaActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        PB_18131267_Frame_03c jFDiagrama = new PB_18131267_Frame_03c(this);
        jFDiagrama.setVisible(true);
        
    }//GEN-LAST:event_jButDiagramaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PB_18131267_Frame_03a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PB_18131267_Frame_03a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PB_18131267_Frame_03a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PB_18131267_Frame_03a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PB_18131267_Frame_03a().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButDesfile;
    private javax.swing.JButton jButDiagrama;
    private javax.swing.JButton jButEjemplo;
    private javax.swing.JButton jButGuardar;
    private javax.swing.JButton jButModificar;
    private javax.swing.JButton jButMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner jSRenglon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabBandas;
    private javax.swing.JTextField jTextGenero;
    private javax.swing.JTextField jTextIntegrantes;
    private javax.swing.JTextField jTextNombre;
    // End of variables declaration//GEN-END:variables
}
