/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app_juego_infantil;

import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;


/**
 *
 * @author ahdeijack
 */
public class Memorama extends javax.swing.JFrame {

    /**
     * Creates new form Memorama
     */
    
    public Memorama() {
        initComponents();
        rolarCartas();
        
    }
    
    private Carta log = new Carta();
    private boolean caraVol = false;
    private ImageIcon Im1;
    private ImageIcon Im2;
    private JButton[] abtn = new JButton[2];
    private boolean primerc = false;
    int[] numeros = log.getNumCarta();
    
    
//metodo para saber si son pares.
    private void rolarCartas(){
    
    j1.setDisabledIcon(new ImageIcon(getClass().getResource("/imagenes/c"+numeros[0]+".png")));
    j1.setText(numeros[0]+"");
    j2.setDisabledIcon(new ImageIcon(getClass().getResource("/imagenes/c"+numeros[1]+".png")));
    j2.setText(numeros[1]+"");
    j3.setDisabledIcon(new ImageIcon(getClass().getResource("../imagenes/c"+numeros[2]+".png")));
    j3.setText(numeros[2]+"");
    j4.setDisabledIcon(new ImageIcon(getClass().getResource("../imagenes/c"+numeros[3]+".png")));
    j4.setText(numeros[3]+"");
    j5.setDisabledIcon(new ImageIcon(getClass().getResource("../imagenes/c"+numeros[4]+".png")));
    j5.setText(numeros[4]+"");
    j6.setDisabledIcon(new ImageIcon(getClass().getResource("../imagenes/c"+numeros[5]+".png")));
    j6.setText(numeros[5]+"");
    j7.setDisabledIcon(new ImageIcon(getClass().getResource("../imagenes/c"+numeros[6]+".png")));
    j7.setText(numeros[6]+"");
    j8.setDisabledIcon(new ImageIcon(getClass().getResource("../imagenes/c"+numeros[7]+".png")));
    j8.setText(numeros[7]+"");
    j9.setDisabledIcon(new ImageIcon(getClass().getResource("../imagenes/c"+numeros[8]+".png")));
    j9.setText(numeros[8]+"");
    j10.setDisabledIcon(new ImageIcon(getClass().getResource("../imagenes/c"+numeros[9]+".png")));
    j10.setText(numeros[9]+"");
    j11.setDisabledIcon(new ImageIcon(getClass().getResource("../imagenes/c"+numeros[10]+".png")));
    j11.setText(numeros[10]+"");
    j12.setDisabledIcon(new ImageIcon(getClass().getResource("../imagenes/c"+numeros[11]+".png")));
    j12.setText(numeros[11]+"");
    j13.setDisabledIcon(new ImageIcon(getClass().getResource("../imagenes/c"+numeros[12]+".png")));
    j13.setText(numeros[12]+"");
    j14.setDisabledIcon(new ImageIcon(getClass().getResource("../imagenes/c"+numeros[13]+".png")));
    j14.setText(numeros[13]+"");
    j15.setDisabledIcon(new ImageIcon(getClass().getResource("../imagenes/c"+numeros[14]+".png")));
    j15.setText(numeros[14]+"");
    j16.setDisabledIcon(new ImageIcon(getClass().getResource("../imagenes/c"+numeros[15]+".png")));
    j16.setText(numeros[15]+"");
    j17.setDisabledIcon(new ImageIcon(getClass().getResource("../imagenes/c"+numeros[16]+".png")));
    j17.setText(numeros[16]+"");
    j18.setDisabledIcon(new ImageIcon(getClass().getResource("../imagenes/c"+numeros[17]+".png")));
    j18.setText(numeros[17]+"");

    
      
    
    }
     
    private void btnEnabled (JButton btn){
        if(!caraVol){
            btn.setEnabled(false);
            Im1 = (ImageIcon)btn.getDisabledIcon();
            abtn[0] = btn;
            caraVol = true;
            primerc = false;
        }
        else {
            Im2 = (ImageIcon)btn.getDisabledIcon();
            btn.setEnabled(false);
            abtn[1] = btn;
            primerc = true;
        }
    }

   private void compare(JLabel jl){
       if(caraVol && primerc){
           
           int n1, n2, multi;
           try{
            n1 = Integer.parseInt(abtn[0].getText());
            n2 = Integer.valueOf(abtn[1].getText());
           } catch (NumberFormatException  e){
               n1 = 0;
               n2 = 0;
           }
          
           multi = n1*n2;
           jl.setText(multi+" ");
           
           if(Im1.getDescription().compareTo(Im2.getDescription()) != 0){
           abtn[0].setEnabled(true);
           abtn[1].setEnabled(true);
           
           }
           caraVol = false;
       }
   } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        j1 = new javax.swing.JButton();
        j2 = new javax.swing.JButton();
        j3 = new javax.swing.JButton();
        j4 = new javax.swing.JButton();
        j5 = new javax.swing.JButton();
        j6 = new javax.swing.JButton();
        j7 = new javax.swing.JButton();
        j8 = new javax.swing.JButton();
        j9 = new javax.swing.JButton();
        j10 = new javax.swing.JButton();
        j11 = new javax.swing.JButton();
        j12 = new javax.swing.JButton();
        j13 = new javax.swing.JButton();
        j14 = new javax.swing.JButton();
        j15 = new javax.swing.JButton();
        j16 = new javax.swing.JButton();
        j17 = new javax.swing.JButton();
        j18 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabRes = new javax.swing.JLabel();
        jButOtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Memorama de Multiplicar");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(119, 132, 192));
        jButton2.setText("< Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        j1.setBackground(new java.awt.Color(46, 148, 185));
        j1.setFont(new java.awt.Font("Dialog", 1, 1)); // NOI18N
        j1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_juego_infantil/carta.png"))); // NOI18N
        j1.setBorder(null);
        j1.setBorderPainted(false);
        j1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j1MouseExited(evt);
            }
        });
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });
        getContentPane().add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 40, 40));

        j2.setBackground(new java.awt.Color(46, 148, 185));
        j2.setFont(new java.awt.Font("Dialog", 1, 1)); // NOI18N
        j2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_juego_infantil/carta.png"))); // NOI18N
        j2.setBorder(null);
        j2.setBorderPainted(false);
        j2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j2MouseExited(evt);
            }
        });
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });
        getContentPane().add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 40, 40));

        j3.setBackground(new java.awt.Color(46, 148, 185));
        j3.setFont(new java.awt.Font("Dialog", 1, 1)); // NOI18N
        j3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_juego_infantil/carta.png"))); // NOI18N
        j3.setBorder(null);
        j3.setBorderPainted(false);
        j3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j3MouseExited(evt);
            }
        });
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });
        getContentPane().add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 40, 40));

        j4.setBackground(new java.awt.Color(46, 148, 185));
        j4.setFont(new java.awt.Font("Dialog", 1, 1)); // NOI18N
        j4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_juego_infantil/carta.png"))); // NOI18N
        j4.setBorder(null);
        j4.setBorderPainted(false);
        j4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j4MouseExited(evt);
            }
        });
        j4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4ActionPerformed(evt);
            }
        });
        getContentPane().add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 40, 40));

        j5.setBackground(new java.awt.Color(46, 148, 185));
        j5.setFont(new java.awt.Font("Dialog", 1, 1)); // NOI18N
        j5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_juego_infantil/carta.png"))); // NOI18N
        j5.setBorder(null);
        j5.setBorderPainted(false);
        j5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j5MouseExited(evt);
            }
        });
        j5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j5ActionPerformed(evt);
            }
        });
        getContentPane().add(j5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 40, 40));

        j6.setBackground(new java.awt.Color(46, 148, 185));
        j6.setFont(new java.awt.Font("Dialog", 1, 1)); // NOI18N
        j6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_juego_infantil/carta.png"))); // NOI18N
        j6.setBorder(null);
        j6.setBorderPainted(false);
        j6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j6MouseExited(evt);
            }
        });
        j6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j6ActionPerformed(evt);
            }
        });
        getContentPane().add(j6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 40, 40));

        j7.setBackground(new java.awt.Color(46, 148, 185));
        j7.setFont(new java.awt.Font("Dialog", 1, 1)); // NOI18N
        j7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_juego_infantil/carta.png"))); // NOI18N
        j7.setBorder(null);
        j7.setBorderPainted(false);
        j7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j7MouseExited(evt);
            }
        });
        j7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j7ActionPerformed(evt);
            }
        });
        getContentPane().add(j7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 40, 40));

        j8.setBackground(new java.awt.Color(46, 148, 185));
        j8.setFont(new java.awt.Font("Dialog", 1, 1)); // NOI18N
        j8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_juego_infantil/carta.png"))); // NOI18N
        j8.setBorder(null);
        j8.setBorderPainted(false);
        j8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j8MouseExited(evt);
            }
        });
        j8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j8ActionPerformed(evt);
            }
        });
        getContentPane().add(j8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 40, 40));

        j9.setBackground(new java.awt.Color(46, 148, 185));
        j9.setFont(new java.awt.Font("Dialog", 1, 1)); // NOI18N
        j9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_juego_infantil/carta.png"))); // NOI18N
        j9.setBorder(null);
        j9.setBorderPainted(false);
        j9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j9MouseExited(evt);
            }
        });
        j9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j9ActionPerformed(evt);
            }
        });
        getContentPane().add(j9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 40, 40));

        j10.setBackground(new java.awt.Color(46, 148, 185));
        j10.setFont(new java.awt.Font("Dialog", 1, 1)); // NOI18N
        j10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_juego_infantil/carta.png"))); // NOI18N
        j10.setBorder(null);
        j10.setBorderPainted(false);
        j10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j10MouseExited(evt);
            }
        });
        j10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j10ActionPerformed(evt);
            }
        });
        getContentPane().add(j10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 40, 40));

        j11.setBackground(new java.awt.Color(46, 148, 185));
        j11.setFont(new java.awt.Font("Dialog", 1, 1)); // NOI18N
        j11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_juego_infantil/carta.png"))); // NOI18N
        j11.setBorder(null);
        j11.setBorderPainted(false);
        j11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j11MouseExited(evt);
            }
        });
        j11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j11ActionPerformed(evt);
            }
        });
        getContentPane().add(j11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 40, 40));

        j12.setBackground(new java.awt.Color(46, 148, 185));
        j12.setFont(new java.awt.Font("Dialog", 1, 1)); // NOI18N
        j12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_juego_infantil/carta.png"))); // NOI18N
        j12.setBorder(null);
        j12.setBorderPainted(false);
        j12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j12MouseExited(evt);
            }
        });
        j12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j12ActionPerformed(evt);
            }
        });
        getContentPane().add(j12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 40, 40));

        j13.setBackground(new java.awt.Color(46, 148, 185));
        j13.setFont(new java.awt.Font("Dialog", 1, 1)); // NOI18N
        j13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_juego_infantil/carta.png"))); // NOI18N
        j13.setBorder(null);
        j13.setBorderPainted(false);
        j13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j13MouseExited(evt);
            }
        });
        j13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j13ActionPerformed(evt);
            }
        });
        getContentPane().add(j13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 40, 40));

        j14.setBackground(new java.awt.Color(46, 148, 185));
        j14.setFont(new java.awt.Font("Dialog", 1, 1)); // NOI18N
        j14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_juego_infantil/carta.png"))); // NOI18N
        j14.setBorder(null);
        j14.setBorderPainted(false);
        j14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j14MouseExited(evt);
            }
        });
        j14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j14ActionPerformed(evt);
            }
        });
        getContentPane().add(j14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 40, 40));

        j15.setBackground(new java.awt.Color(46, 148, 185));
        j15.setFont(new java.awt.Font("Dialog", 1, 1)); // NOI18N
        j15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_juego_infantil/carta.png"))); // NOI18N
        j15.setBorder(null);
        j15.setBorderPainted(false);
        j15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j15MouseExited(evt);
            }
        });
        j15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j15ActionPerformed(evt);
            }
        });
        getContentPane().add(j15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 40, 40));

        j16.setBackground(new java.awt.Color(46, 148, 185));
        j16.setFont(new java.awt.Font("Dialog", 1, 1)); // NOI18N
        j16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_juego_infantil/carta.png"))); // NOI18N
        j16.setBorder(null);
        j16.setBorderPainted(false);
        j16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j16MouseExited(evt);
            }
        });
        j16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j16ActionPerformed(evt);
            }
        });
        getContentPane().add(j16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 40, 40));

        j17.setBackground(new java.awt.Color(46, 148, 185));
        j17.setFont(new java.awt.Font("Dialog", 1, 1)); // NOI18N
        j17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_juego_infantil/carta.png"))); // NOI18N
        j17.setBorder(null);
        j17.setBorderPainted(false);
        j17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j17MouseExited(evt);
            }
        });
        j17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j17ActionPerformed(evt);
            }
        });
        getContentPane().add(j17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 40, 40));

        j18.setBackground(new java.awt.Color(46, 148, 185));
        j18.setFont(new java.awt.Font("Dialog", 1, 1)); // NOI18N
        j18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_juego_infantil/carta.png"))); // NOI18N
        j18.setBorder(null);
        j18.setBorderPainted(false);
        j18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j18MouseExited(evt);
            }
        });
        j18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j18ActionPerformed(evt);
            }
        });
        getContentPane().add(j18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 40, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Empezar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, -1));

        jLabRes.setFont(new java.awt.Font("Kalam Light", 1, 36)); // NOI18N
        jLabRes.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 80, 60));

        jButOtras.setBackground(new java.awt.Color(255, 102, 0));
        jButOtras.setForeground(new java.awt.Color(255, 255, 255));
        jButOtras.setText("Otras Tablas");
        jButOtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButOtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButOtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 600, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_juego_infantil/memorama_bg.png"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jFrameP abrirMenu = new jFrameP();
        abrirMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
        // TODO add your handling code here:
        btnEnabled (j1);
        
    }//GEN-LAST:event_j1ActionPerformed

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        // TODO add your handling code here:
        btnEnabled (j2);
        
    }//GEN-LAST:event_j2ActionPerformed

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        // TODO add your handling code here:
        btnEnabled (j3);
      
    }//GEN-LAST:event_j3ActionPerformed

    private void j4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4ActionPerformed
        // TODO add your handling code here:
        btnEnabled (j4);
        
    }//GEN-LAST:event_j4ActionPerformed

    private void j5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j5ActionPerformed
        // TODO add your handling code here:
        btnEnabled (j5);
        
    }//GEN-LAST:event_j5ActionPerformed

    private void j6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j6ActionPerformed
        // TODO add your handling code here:
        btnEnabled (j6);
 
        
    }//GEN-LAST:event_j6ActionPerformed

    private void j7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j7ActionPerformed
        // TODO add your handling code here:
      btnEnabled (j7);
        
    }//GEN-LAST:event_j7ActionPerformed

    private void j8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j8ActionPerformed
        // TODO add your handling code here:
       btnEnabled (j8);
        
    }//GEN-LAST:event_j8ActionPerformed

    private void j9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j9ActionPerformed
        // TODO add your handling code here:
       btnEnabled (j9);
        
    }//GEN-LAST:event_j9ActionPerformed

    private void j10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j10ActionPerformed
        // TODO add your handling code here:
       btnEnabled (j10);
    }//GEN-LAST:event_j10ActionPerformed

    private void j11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j11ActionPerformed
        // TODO add your handling code here:
       btnEnabled (j11);
        
    }//GEN-LAST:event_j11ActionPerformed

    private void j12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j12ActionPerformed
        // TODO add your handling code here:
       btnEnabled (j12); 
        
    }//GEN-LAST:event_j12ActionPerformed

    private void j13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j13ActionPerformed
        // TODO add your handling code here:
        btnEnabled (j13);
        
    }//GEN-LAST:event_j13ActionPerformed

    private void j14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j14ActionPerformed
        // TODO add your handling code here:
        btnEnabled (j14);
        
    }//GEN-LAST:event_j14ActionPerformed

    private void j15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j15ActionPerformed
        // TODO add your handling code here:
       btnEnabled (j15);
        
    }//GEN-LAST:event_j15ActionPerformed

    private void j16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j16ActionPerformed
        // TODO add your handling code here:
       btnEnabled (j16);
        
    }//GEN-LAST:event_j16ActionPerformed

    private void j17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j17ActionPerformed
        // TODO add your handling code here:
       btnEnabled (j17);
    }//GEN-LAST:event_j17ActionPerformed

    private void j18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j18ActionPerformed
        // TODO add your handling code here:
        btnEnabled (j18);
    }//GEN-LAST:event_j18ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        j1.setEnabled(true);
        j2.setEnabled(true);
        j3.setEnabled(true);
        j4.setEnabled(true);
        j5.setEnabled(true);
        j6.setEnabled(true);
        j7.setEnabled(true);
        j8.setEnabled(true);
        j9.setEnabled(true);
        j10.setEnabled(true);
        j11.setEnabled(true);
        j12.setEnabled(true);
        j13.setEnabled(true);
        j14.setEnabled(true);
        j15.setEnabled(true);
        j16.setEnabled(true);
        j17.setEnabled(true);
        j18.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void j1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1MouseExited
        // TODO add your handling code here:
        compare(jLabRes);
    }//GEN-LAST:event_j1MouseExited

    private void j2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2MouseExited
        // TODO add your handling code here:
        compare(jLabRes);
    }//GEN-LAST:event_j2MouseExited

    private void j3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j3MouseExited
        // TODO add your handling code here:
        compare(jLabRes);
    }//GEN-LAST:event_j3MouseExited

    private void j4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j4MouseExited
        // TODO add your handling code here:
        compare(jLabRes);
    }//GEN-LAST:event_j4MouseExited

    private void j5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j5MouseExited
        // TODO add your handling code here:
        compare(jLabRes);
    }//GEN-LAST:event_j5MouseExited

    private void j6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j6MouseExited
        // TODO add your handling code here:
        compare(jLabRes);
    }//GEN-LAST:event_j6MouseExited

    private void j7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j7MouseExited
        // TODO add your handling code here:
        compare(jLabRes);
    }//GEN-LAST:event_j7MouseExited

    private void j8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j8MouseExited
        // TODO add your handling code here:
        compare(jLabRes);
    }//GEN-LAST:event_j8MouseExited

    private void j10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j10MouseExited
        // TODO add your handling code here:
        compare(jLabRes);
    }//GEN-LAST:event_j10MouseExited

    private void j11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j11MouseExited
        // TODO add your handling code here:
        compare(jLabRes);
    }//GEN-LAST:event_j11MouseExited

    private void j14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j14MouseExited
        // TODO add your handling code here:
        compare(jLabRes);
    }//GEN-LAST:event_j14MouseExited

    private void j9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j9MouseExited
        // TODO add your handling code here:
        compare(jLabRes);
    }//GEN-LAST:event_j9MouseExited

    private void j12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j12MouseExited
        // TODO add your handling code here:
        compare(jLabRes);
    }//GEN-LAST:event_j12MouseExited

    private void j13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j13MouseExited
        // TODO add your handling code here:
        compare(jLabRes);
    }//GEN-LAST:event_j13MouseExited

    private void j15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j15MouseExited
        // TODO add your handling code here:
        compare(jLabRes);
    }//GEN-LAST:event_j15MouseExited

    private void j16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j16MouseExited
        // TODO add your handling code here:
        compare(jLabRes);
    }//GEN-LAST:event_j16MouseExited

    private void j17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j17MouseExited
        // TODO add your handling code here:
        compare(jLabRes);
    }//GEN-LAST:event_j17MouseExited

    private void j18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j18MouseExited
        // TODO add your handling code here:
        compare(jLabRes);
    }//GEN-LAST:event_j18MouseExited

    private void jButOtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButOtrasActionPerformed
        // TODO add your handling code here:
        Tablas abrirT = new Tablas();
        abrirT.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButOtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Memorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Memorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Memorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Memorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Memorama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton j1;
    private javax.swing.JButton j10;
    private javax.swing.JButton j11;
    private javax.swing.JButton j12;
    private javax.swing.JButton j13;
    private javax.swing.JButton j14;
    private javax.swing.JButton j15;
    private javax.swing.JButton j16;
    private javax.swing.JButton j17;
    private javax.swing.JButton j18;
    private javax.swing.JButton j2;
    private javax.swing.JButton j3;
    private javax.swing.JButton j4;
    private javax.swing.JButton j5;
    private javax.swing.JButton j6;
    private javax.swing.JButton j7;
    private javax.swing.JButton j8;
    private javax.swing.JButton j9;
    private javax.swing.JButton jButOtras;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabRes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}


