/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_17130852_proyecto_01;

import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NICODANA
 */
public class PB_17130852_Frame_01 extends javax.swing.JFrame {

    /**
     * Creates new form PB_17130852_Frame_01
     */
    
     
    // atributos del frame
    Rectangulo [] lista = new Rectangulo[3];
    
    public PB_17130852_Frame_01() {
        initComponents();
        
        DefaultTableModel modelo = (DefaultTableModel)jTableRectangulo.getModel();
        modelo.setRowCount(lista.length);
        jTableRectangulo.setShowGrid(true);
        
         for (int i=0; i<lista.length; i++)
            lista[i] = new Rectangulo();
        
        mostrar();
    }
    // métodos del frame
    public void mostrar()
    {
        double totalPerimetro=0;
        double totalAltura=0;
        
        for (int r=0; r<lista.length; r++)
        {
            jTableRectangulo.setValueAt(lista[r].getNombre(), r, 0);
            jTableRectangulo.setValueAt(lista[r].getBase(), r, 1);
            jTableRectangulo.setValueAt(lista[r].altura(), r, 2);
            jTableRectangulo.setValueAt(lista[r].getArea(), r, 3);
            jTableRectangulo.setValueAt(lista[r].perimetro(), r, 4);
            
            totalPerimetro+=lista[r].perimetro();
            totalAltura+=lista[r].altura();
        }
        jLabPT.setText(totalPerimetro+"");
        jLabPA.setText(totalAltura/3+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRectangulo = new javax.swing.JTable();
        jButEjemplo1 = new javax.swing.JButton();
        jButEjemplo2 = new javax.swing.JButton();
        jButEjemplo3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButGrabar = new javax.swing.JButton();
        jButAleatorios = new javax.swing.JButton();
        jButEditar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabPT = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabPA = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButAlfabetico = new javax.swing.JButton();
        jButMaMe = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextArea = new javax.swing.JTextField();
        jTextBase = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabMayor = new javax.swing.JLabel();
        jLabMenor = new javax.swing.JLabel();
        jButDescendente = new javax.swing.JButton();
        jSpinPosicion = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableRectangulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rectangulo", "Base", "Altura", "Area", "Perimetro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableRectangulo);

        jButEjemplo1.setText("Hoja");
        jButEjemplo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemplo1ActionPerformed(evt);
            }
        });

        jButEjemplo2.setText("Pizarrón");
        jButEjemplo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemplo2ActionPerformed(evt);
            }
        });

        jButEjemplo3.setText("Borrador");
        jButEjemplo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemplo3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ejemplo 1");

        jButGrabar.setText("Grabar");
        jButGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButGrabarActionPerformed(evt);
            }
        });

        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jButEditar.setText("Editar");
        jButEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEditarActionPerformed(evt);
            }
        });

        jLabel2.setText("Ejemplo 2");

        jLabel3.setText("Ejemplo 3");

        jLabel4.setText("Perimetro Total");

        jLabPT.setBackground(new java.awt.Color(255, 102, 255));
        jLabPT.setOpaque(true);

        jLabel6.setText("Promedio Altura");

        jLabPA.setBackground(new java.awt.Color(255, 102, 255));
        jLabPA.setOpaque(true);

        jLabel8.setText("Ordenar por: ");

        jButAlfabetico.setText("Alfabetico");
        jButAlfabetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAlfabeticoActionPerformed(evt);
            }
        });

        jButMaMe.setText("Mayor y Menor");
        jButMaMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButMaMeActionPerformed(evt);
            }
        });

        jLabel9.setText("Rectangulo");

        jLabel10.setText("Área");

        jLabel11.setText("Base");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pb_17130852_proyecto_01/asignacion.png"))); // NOI18N

        jLabMayor.setBackground(new java.awt.Color(255, 102, 255));
        jLabMayor.setOpaque(true);

        jLabMenor.setBackground(new java.awt.Color(255, 102, 255));
        jLabMenor.setOpaque(true);

        jButDescendente.setText("Descendente");
        jButDescendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDescendenteActionPerformed(evt);
            }
        });

        jSpinPosicion.setModel(new javax.swing.SpinnerNumberModel(1, 1, 3, 1));

        jLabel5.setText("Numero Rectangulo");

        jCheckBox1.setText("Incrementar");

        jLabel7.setBackground(new java.awt.Color(204, 255, 204));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Altura y Perimetro de un Rectangulo");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel7.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel9))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(118, 118, 118)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(11, 11, 11)
                                                .addComponent(jButEjemplo1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButEjemplo2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButEjemplo3)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextBase, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(jLabel8))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButDescendente)
                                                    .addComponent(jButAlfabetico))
                                                .addGap(110, 110, 110)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButMaMe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabMayor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabMenor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSpinPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButGrabar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(112, 112, 112)
                                        .addComponent(jCheckBox1)))
                                .addGap(6, 6, 6)
                                .addComponent(jButEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButAleatorios)))
                        .addGap(423, 423, 423))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabPA, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabPT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jButGrabar)
                            .addComponent(jButEditar)
                            .addComponent(jButAleatorios))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabPT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabPA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButEjemplo1)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButEjemplo2)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButEjemplo3)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jButMaMe))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButAlfabetico)
                                .addGap(18, 18, 18)
                                .addComponent(jButDescendente)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(43, 43, 43))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        // TODO add your handling code here:
         Random azar = new Random();
        
        String [] nom = {"Pantalla","Mesa","Grabadora","Ropero","Libro","Caja","Celular",
                         "Tablet","Modem","Ventana"};
        
        jTextNombre.setText(nom[azar.nextInt(nom.length)]);
        jTextArea.setText(1+azar.nextInt(1000)+"");
        jTextBase.setText(1+azar.nextInt(1000)+"");
        
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jButGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButGrabarActionPerformed
        // TODO add your handling code here:
        int posicion = (int)jSpinPosicion.getValue() - 1;
        
        Rectangulo rec = new Rectangulo(jTextNombre.getText(),
                                        Double.parseDouble(jTextBase.getText()),
                                        Double.parseDouble(jTextArea.getText()));
        
        lista[posicion] = rec;
        
        mostrar();
        
        if (jCheckBox1.isSelected())
            jSpinPosicion.setValue(posicion+2);
    }//GEN-LAST:event_jButGrabarActionPerformed

    private void jButEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEditarActionPerformed
        // TODO add your handling code here:
         int posicion = (int)jSpinPosicion.getValue() - 1;
        
        Rectangulo rec = lista[posicion];
        
        jTextNombre.setText(rec.getNombre());
        jTextArea.setText(rec.getArea()+"");
        jTextBase.setText(rec.getBase()+"");
        
    }//GEN-LAST:event_jButEditarActionPerformed

    private void jButDescendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDescendenteActionPerformed
        // TODO add your handling code here:
        for (int i=0; i<lista.length-1; i++)
            for (int j=i+1; j<lista.length; j++)
                if (lista[i].altura()<lista[j].altura())
                {
                    Rectangulo aux = lista[i];
                    lista[i] = lista[j];
                    lista[j] = aux;
                }
        
        mostrar();
    }//GEN-LAST:event_jButDescendenteActionPerformed

    private void jButAlfabeticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAlfabeticoActionPerformed
        // TODO add your handling code here:
        for (int i=0; i<lista.length-1; i++)
            for (int j=i+1; j<lista.length; j++)
                if (lista[i].getNombre().compareTo(lista[j].getNombre())>0)
                {
                    Rectangulo aux = lista[i];
                    lista[i] = lista[j];
                    lista[j] = aux;
                }
        
        mostrar();
    }//GEN-LAST:event_jButAlfabeticoActionPerformed

    private void jButMaMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButMaMeActionPerformed
        // TODO add your handling code here:
        Rectangulo may = lista[0];

        for (int i=1; i<lista.length; i++)
            if (lista[i].altura()>may.altura())
                may = lista[i];
        
        Rectangulo men = lista[0];

        for (int i=1; i<lista.length; i++)
            if (lista[i].altura()<men.altura())
                men = lista[i];
        
        jLabMayor.setText(may.getNombre());
        jLabMenor.setText(men.getNombre());
    }//GEN-LAST:event_jButMaMeActionPerformed

    private void jButEjemplo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemplo1ActionPerformed
        // TODO add your handling code here:
        jTextNombre.setText("Hoja");
        jTextBase.setText("21");
        jTextArea.setText("588");
    }//GEN-LAST:event_jButEjemplo1ActionPerformed

    private void jButEjemplo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemplo2ActionPerformed
        // TODO add your handling code here:
        jTextNombre.setText("Pizarrón");
        jTextBase.setText("150");
        jTextArea.setText("14250");
    }//GEN-LAST:event_jButEjemplo2ActionPerformed

    private void jButEjemplo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemplo3ActionPerformed
        // TODO add your handling code here:
        jTextNombre.setText("Borrador");
        jTextBase.setText("17");
        jTextArea.setText("119");
    }//GEN-LAST:event_jButEjemplo3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PB_17130852_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PB_17130852_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PB_17130852_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PB_17130852_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PB_17130852_Frame_01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButAlfabetico;
    private javax.swing.JButton jButDescendente;
    private javax.swing.JButton jButEditar;
    private javax.swing.JButton jButEjemplo1;
    private javax.swing.JButton jButEjemplo2;
    private javax.swing.JButton jButEjemplo3;
    private javax.swing.JButton jButGrabar;
    private javax.swing.JButton jButMaMe;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabMayor;
    private javax.swing.JLabel jLabMenor;
    private javax.swing.JLabel jLabPA;
    private javax.swing.JLabel jLabPT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinPosicion;
    private javax.swing.JTable jTableRectangulo;
    private javax.swing.JTextField jTextArea;
    private javax.swing.JTextField jTextBase;
    private javax.swing.JTextField jTextNombre;
    // End of variables declaration//GEN-END:variables
}
