/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_17130852_examen_04;

import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paco_
 */
public class PB_17130852_Frame_01 extends javax.swing.JFrame {

    /**
     * Creates new form PB_17130852_Frame_01
     */
    
    JFileChooser jfch = new JFileChooser();
    Random azar = new Random();
    String [] marca = {"Nissan","Mazda","Ford","Chevrolet","Kia","Mitsubishi","Chrysler"};
    int [] cil = {4,6,8};
    int [] precio = {50000,20000,60000,45000,55000};
    
    public PB_17130852_Frame_01() {
        initComponents();

        jTableAutos.setShowGrid(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAutos = new javax.swing.JTable();
        jSpinAutos = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jButAleatorios = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenu1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemNuevo = new javax.swing.JMenuItem();
        jMenuItemGT = new javax.swing.JMenuItem();
        jMenuItemLT = new javax.swing.JMenuItem();
        jMenuItemGB = new javax.swing.JMenuItem();
        jMenuItemLB = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableAutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "No.Cilindros", "Precio"
            }
        ));
        jScrollPane1.setViewportView(jTableAutos);

        jSpinAutos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jSpinAutos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinAutosStateChanged(evt);
            }
        });

        jLabel1.setText("Numero de Autos");

        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jButton1.setText("Examen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu2.setText("Archivo");

        jMenuItemNuevo.setText("Nuevo");
        jMenuItemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemNuevo);

        jMenuItemGT.setText("Grabar Texto");
        jMenuItemGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGTActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemGT);

        jMenuItemLT.setText("Leer Texto");
        jMenuItemLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLTActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemLT);

        jMenuItemGB.setText("Grabar Binario");
        jMenuItemGB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGBActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemGB);

        jMenuItemLB.setText("Leer Binario");
        jMenuItemLB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLBActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemLB);

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemSalir);

        jMenu1.add(jMenu2);

        setJMenuBar(jMenu1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSpinAutos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButAleatorios)
                        .addGap(33, 33, 33)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinAutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButAleatorios)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoActionPerformed
        // TODO add your handling code here:
        for (int r=0; r<(int)jSpinAutos.getValue(); r++)
        {
        jTableAutos.setValueAt(null, r, 0);
        jTableAutos.setValueAt(null, r, 1);
        jTableAutos.setValueAt(null, r, 2);   
        }
        
        jSpinAutos.setValue(0);
    }//GEN-LAST:event_jMenuItemNuevoActionPerformed

    private void jMenuItemGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGTActionPerformed
        // TODO add your handling code here: 
        jfch.showSaveDialog(jMenu1);
    
        File archivo = jfch.getSelectedFile();
        
        if(archivo == null)
            return;
        
        try {
            // TODO add your handling code here:
            FileWriter fw = new FileWriter(archivo);
            PrintWriter pw = new PrintWriter(fw);
                        
            pw.println((int)jSpinAutos.getValue());
            
            for (int r=0; r<(int)jSpinAutos.getValue(); r++)
            {
                pw.println(jTableAutos.getValueAt(r, 0)+"");
                pw.println(jTableAutos.getValueAt(r, 1)+"");
                pw.println(jTableAutos.getValueAt(r, 2)+"");
            }
       
            pw.close();
            fw.close();
            
            JOptionPane.showMessageDialog(this, " Archivo Grabado");
            
        } catch (IOException ex) {
            Logger.getLogger(PB_17130852_Frame_01.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemGTActionPerformed

    private void jMenuItemLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLTActionPerformed
        // TODO add your handling code here:
        jfch.showOpenDialog(jMenu1);
    
        File archivo = jfch.getSelectedFile();
        
        if(archivo == null)
            return;
        
        try {
            // TODO add your handling code here:
            FileReader fr = new FileReader(archivo);
            BufferedReader br = new BufferedReader(fr);
            
            
            try {
                int n = Integer.parseInt(br.readLine());

            jSpinAutos.setValue(n);
            
            for (int r=0; r<(int)jSpinAutos.getValue(); r++)
            {
                jTableAutos.setValueAt(br.readLine(), r, 0);
                jTableAutos.setValueAt(br.readLine(), r, 1);
                jTableAutos.setValueAt(br.readLine(), r, 2);
            }
            
            br.close();
            fr.close();
                
            } catch (IOException ex) {
                Logger.getLogger(PB_17130852_Frame_01.class.getName()).log(Level.SEVERE, null, ex);
            }

 
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PB_17130852_Frame_01.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemLTActionPerformed

    private void jSpinAutosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinAutosStateChanged
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel)jTableAutos.getModel();
        modelo.setRowCount((int)jSpinAutos.getValue());
    }//GEN-LAST:event_jSpinAutosStateChanged

    private void jMenuItemGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGBActionPerformed
        // TODO add your handling code here:
        jfch.showSaveDialog(jMenu1);
        
        File archivo = jfch.getSelectedFile();
        
        if (archivo == null) // seleccionó Cancelar
            return;
        
        FileOutputStream fos = null;
        DataOutputStream dos = null;
        
        try 
        {
            fos = new FileOutputStream(archivo);
            dos = new DataOutputStream(fos);
            
            dos.writeInt((int)jSpinAutos.getValue());
            
            for (int r=0; r<(int)jSpinAutos.getValue(); r++)
            {
                dos.writeUTF(jTableAutos.getValueAt(r, 0)+"");
                dos.writeUTF(jTableAutos.getValueAt(r, 1)+"");
                dos.writeUTF(jTableAutos.getValueAt(r, 2)+"");
            }
        } 
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(PB_17130852_Frame_01.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(PB_17130852_Frame_01.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            try {
                if (dos!=null)
                    dos.close();
                if (fos!=null)
                    fos.close();
            } 
            catch (IOException ex) 
            {
                Logger.getLogger(PB_17130852_Frame_01.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jMenuItemGBActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemLBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLBActionPerformed
        // TODO add your handling code here:
        jfch.showOpenDialog(jMenu1);
        
        File archivo = jfch.getSelectedFile();
        
        if (archivo == null) // seleccionó Cancelar
            return;
        
        FileInputStream fis = null;
        DataInputStream dis = null;
        
        try 
        {
            fis = new FileInputStream(archivo);
            dis = new DataInputStream(fis);
            
            jSpinAutos.setValue(dis.readInt());
            
            for (int r=0; r<(int)jSpinAutos.getValue(); r++)
            {
                jTableAutos.setValueAt(dis.readUTF(), r, 0);
                jTableAutos.setValueAt(dis.readUTF(), r, 1);
                jTableAutos.setValueAt(dis.readUTF(), r, 2);
            } 

        } 
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(PB_17130852_Frame_01.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(PB_17130852_Frame_01.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            try
            {
                if (dis!=null)
                    dis.close();
                if (fis!=null)
                    fis.close();
            }
            catch (IOException ex)
            {
                Logger.getLogger(PB_17130852_Frame_01.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItemLBActionPerformed

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        // TODO add your handling code here:
        for (int r=0; r<jTableAutos.getRowCount(); r++)
        {
            jTableAutos.setValueAt(marca[azar.nextInt(marca.length)], r, 0);
            jTableAutos.setValueAt(cil[azar.nextInt(cil.length)], r, 1);
            jTableAutos.setValueAt(precio[azar.nextInt(precio.length)], r, 2);

        }
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        PB_17130852_Frame_02 abrir = new PB_17130852_Frame_02(this);
        abrir.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PB_17130852_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PB_17130852_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PB_17130852_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PB_17130852_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PB_17130852_Frame_01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItemGB;
    private javax.swing.JMenuItem jMenuItemGT;
    private javax.swing.JMenuItem jMenuItemLB;
    private javax.swing.JMenuItem jMenuItemLT;
    private javax.swing.JMenuItem jMenuItemNuevo;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinAutos;
    private javax.swing.JTable jTableAutos;
    // End of variables declaration//GEN-END:variables
}
