/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appnotacionpolaca;

import Clases.ListaEnlazada;
import Clases.Nodo;
import Clases.NodoLista;
import java.awt.event.KeyEvent;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ahdeijack
 */
public class lista_enlazada extends javax.swing.JPanel {

    /**
     * Creates new form lista_enlazada
     */
    DefaultListModel modeloNom;
    DefaultListModel modeloTam;
    ListaEnlazada lista;

    
    public lista_enlazada() {
        initComponents();
        lista = new ListaEnlazada();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Archivo = new javax.swing.JTextField();
        jButBusqueda = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListNom = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_search_16px_1.png"))); // NOI18N
        jLabel1.setText("BUSQUEDA DE ARCHIVOS CON LISTA ENLAZADA.");
        jLabel1.setToolTipText("");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 380, -1));

        Archivo.setBackground(new java.awt.Color(0, 0, 0));
        Archivo.setForeground(new java.awt.Color(0, 153, 153));
        Archivo.setToolTipText("Nombre del archivo para buscar.");
        Archivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ArchivoKeyPressed(evt);
            }
        });
        add(Archivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 38, 86, -1));

        jButBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_search_16px.png"))); // NOI18N
        jButBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBusquedaActionPerformed(evt);
            }
        });
        add(jButBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, 20));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 38, 49, -1));

        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Directorios");
        jLabel2.setToolTipText("");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 38, 58, 20));

        jListNom.setBackground(new java.awt.Color(1, 1, 1));
        jListNom.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jListNom.setForeground(new java.awt.Color(125, 127, 160));
        jListNom.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "null", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListNom.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListNomValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListNom);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 370, 50));

        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Semejantes");
        jLabel3.setToolTipText("");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 370, -1));

        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Carpetas");
        jLabel4.setToolTipText("");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 370, -1));

        jt.setEditable(false);
        jt.setBackground(new java.awt.Color(0, 0, 0));
        jt.setColumns(20);
        jt.setForeground(new java.awt.Color(255, 255, 255));
        jt.setRows(5);
        jScrollPane1.setViewportView(jt);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 370, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_delete_bin_16px.png"))); // NOI18N
        jButton2.setToolTipText("Elimina el directorio seleccionado a la izquierda.");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jButBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBusquedaActionPerformed
        // TODO add your handling code here:
        lista = new ListaEnlazada();
        
            
        String [] carpetas = {"System32", "Archivos de Sistema", "Steam", "Instalaciones", "Programas",
                                            "NetBeansProjects", "Hentai", "Tareas", "Archivos de Sistema (x86)"};
      
        Random azar = new Random();
        int nodos = Integer.parseInt(jSpinner1.getValue()+"");
        Nodo sig= new Nodo();
        Nodo primero = new Nodo(1,carpetas[azar.nextInt(carpetas.length)], azar.nextInt(5), sig);
        Nodo nodo = primero;
      
        for (int i = 0; i < nodos; i++) {
            String carpetass = carpetas[azar.nextInt(carpetas.length)];
            Nodo nuevo = new Nodo(i,carpetass, azar.nextInt(5),primero);
            lista.Insertar(nuevo);
            nodo = nuevo;
            
        }
        modeloNom = new DefaultListModel();
        lista.muestra(modeloNom, jListNom, Archivo.getText());

    }//GEN-LAST:event_jButBusquedaActionPerformed

    private void jListNomValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListNomValueChanged
        String nombre = Archivo.getText();
        String carpetas = (String) jListNom.getSelectedValue();
        if (nombre == null) {
            JOptionPane.showMessageDialog(null, "No hay ninún archivo para buscar.");
        }
        jt.setText("El archivo '"+nombre+"' se encuentra en la dirección seleccionada. ");
        JOptionPane.showMessageDialog(null, carpetas);
    }//GEN-LAST:event_jListNomValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int v =  Integer.parseInt(jSpinner1.getValue()+"");
        lista.Borrar(v);
        jButBusqueda.doClick();
        jSpinner1.setValue(v-1);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ArchivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ArchivoKeyPressed
        // TODO add your handling code here:
          if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jButBusqueda.doClick();
        }
    }//GEN-LAST:event_ArchivoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Archivo;
    private javax.swing.JButton jButBusqueda;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jListNom;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jt;
    // End of variables declaration//GEN-END:variables
}
