package pb_18131288_proyecto_03;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ahedeijak
 */
public class PB_18131288_Frame_03a extends javax.swing.JFrame {

    /**
     * Creates new form PB_18131288_Frame_03a
     */
    //Atributos del frame
    DefaultTableModel modelo;
    private int bandasRegistradas;
     PB_18131288_Clase_A [] banditas = new PB_18131288_Clase_A[4];
     PB_18131288_Clase_A [] dibujos = new PB_18131288_Clase_A[banditas.length];
        Nacional bandaN;
        Internacional bandaI;
    
    
    public PB_18131288_Frame_03a() {
        initComponents();
        bandasRegistradas = 4;
        
        modelo = (DefaultTableModel)jTabBanda.getModel();
        jTabBanda.setShowGrid(true);
        //mostrar(); //creamos el metodo mostrar para poder ver los 
                      //registros cuando el usuario lo desee.
                      
        modelo.setValueAt("La banda baston", 0, 0);
        modelo.setValueAt("Hip-Hop", 0, 1);
        modelo.setValueAt(2, 0, 2);
        
        modelo.setValueAt("Bunbury", 1, 0);
        modelo.setValueAt("Rock", 1, 1);
        modelo.setValueAt(1, 1, 2);
        
        modelo.setValueAt("Little Jesus", 2, 0);
        modelo.setValueAt("Indie", 2, 1);
        modelo.setValueAt(5, 2, 2);

        modelo.setValueAt("TøP", 3, 0);
        modelo.setValueAt("Electropop", 3, 1);
        modelo.setValueAt(2, 3, 2);
        
        jSRenglon.setValue(1);
    }
    
    public int getTamano(){
        return(banditas.length);
    }
    
    public int getBandasRegistradas(){
        return bandasRegistradas;
    }
    
     public boolean agregarGrupoMusical(PB_18131288_Clase_A grupo)
    {
        if(bandasRegistradas == banditas.length)
            return false;
        
        banditas[bandasRegistradas] = grupo;
        bandasRegistradas++; //Incrementa el contador

        return true;
    }   
     
      public void setGrupoMusical(PB_18131288_Clase_A grupo, int posicion)
    {
        if(posicion >=0 && posicion < banditas.length)
            banditas[posicion] = grupo;
    }   
    
    public PB_18131288_Clase_A getBanda(int posicion)
    {
        if(posicion >=0 && posicion < banditas.length)
            return(banditas[posicion]);
        
        else
            return (null);
    }  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabBanda = new javax.swing.JTable();
        jLabNombre1 = new javax.swing.JLabel();
        jLabNombre2 = new javax.swing.JLabel();
        jLabNombre4 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextGenero = new javax.swing.JTextField();
        jTextIntegrantes = new javax.swing.JTextField();
        jButModificar = new javax.swing.JButton();
        jLabNombre6 = new javax.swing.JLabel();
        jSRenglon = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        jButDiagrama = new javax.swing.JButton();
        jButDesfile = new javax.swing.JButton();
        jButGuardar = new javax.swing.JButton();
        jButDesfile1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabBanda.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jTabBanda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Banda", "Genero", "Integrantes"
            }
        ));
        jScrollPane1.setViewportView(jTabBanda);
        if (jTabBanda.getColumnModel().getColumnCount() > 0) {
            jTabBanda.getColumnModel().getColumn(0).setMinWidth(120);
        }

        jLabNombre1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabNombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabNombre1.setText("Genero");

        jLabNombre2.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabNombre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabNombre2.setText("Nombre");

        jLabNombre4.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabNombre4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabNombre4.setText("Integrantes");

        jTextNombre.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N

        jTextGenero.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N

        jTextIntegrantes.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N

        jButModificar.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jButModificar.setText("Modificar");
        jButModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButModificarActionPerformed(evt);
            }
        });

        jLabNombre6.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabNombre6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabNombre6.setText("Renglon");

        jSRenglon.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N

        jButton3.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jButton3.setText("Ejemplo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButDiagrama.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jButDiagrama.setText("Diagrama");
        jButDiagrama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDiagramaActionPerformed(evt);
            }
        });

        jButDesfile.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jButDesfile.setText("Mostrar");
        jButDesfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDesfileActionPerformed(evt);
            }
        });

        jButGuardar.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jButGuardar.setText("Guardar");
        jButGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButGuardarActionPerformed(evt);
            }
        });

        jButDesfile1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jButDesfile1.setText("Desfile");
        jButDesfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDesfile1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabNombre2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabNombre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabNombre4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextIntegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabNombre6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSRenglon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButDesfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButDiagrama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jButDesfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabNombre1)
                    .addComponent(jLabNombre2)
                    .addComponent(jLabNombre4)
                    .addComponent(jLabNombre6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIntegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSRenglon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButDiagrama, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButDesfile, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButDesfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButModificarActionPerformed
        // TODO add your handling code here:
        
        int renglon = (int)jSRenglon.getValue(); //Seleccionamos el renglon a modificar
        String banda = jTextNombre.getText();
        String genero = jTextGenero.getText();
        int integrantes = Integer.parseInt(jTextIntegrantes.getText()+"");
        
        
        modelo.setValueAt(banda, renglon-1, 0);
        modelo.setValueAt(genero, renglon-1, 1);
        modelo.setValueAt(integrantes, renglon-1, 2);
        
    }//GEN-LAST:event_jButModificarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         //Los nombres de ejemplos son un chascarrillo.
        modelo.setValueAt("BASTON", 0, 0);
        modelo.setValueAt("RAP LATINO", 0, 1);
        modelo.setValueAt(2, 0, 2);
        
        modelo.setValueAt("ENRIQUE BUNBURY", 1, 0);
        modelo.setValueAt("ROCK", 1, 1);
        modelo.setValueAt(1, 1, 2);
        
        modelo.setValueAt("Little Jesus", 2, 0);
        modelo.setValueAt("INDIE", 2, 1);
        modelo.setValueAt(5, 2, 2);

        modelo.setValueAt("Twenty One Pilots", 3, 0);
        modelo.setValueAt("RAP ESQUIZOFRENICO", 3, 1);
        modelo.setValueAt(2, 3, 2);
        
        
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButDesfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDesfileActionPerformed
        
        for(int i = 0; i < 1; i++){
            for(int j = 0; j<banditas.length; j++){
                
                dibujos[j].mover(this, banditas);
                
                try {
                Thread.sleep(90);
                } catch (InterruptedException ex) {
                Logger.getLogger(PB_18131288_Frame_03a.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        }
        
        
    }//GEN-LAST:event_jButDesfileActionPerformed

    private void jButGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButGuardarActionPerformed
        // TODO add your handling code here:
          BandaBaston gpo1 = new BandaBaston((String)modelo.getValueAt(0, 0),
                                                  (String)modelo.getValueAt(0, 1),
                                                  (int)modelo.getValueAt(0, 2),
                                                   "Baja Cal. Sur. MX", 1);
            
                Bunbury gpo2 = new Bunbury( 
                        (String)modelo.getValueAt(1, 0),
                        (String)modelo.getValueAt(1, 1),
                        (int)modelo.getValueAt(1, 2),
                        "Zaragoza Espana.", 2);
                                   
                LittleJesus gpo3 = new LittleJesus( 
                        (String)modelo.getValueAt(2, 0),
                        (String)modelo.getValueAt(2, 1),
                        (int)modelo.getValueAt(2, 2),
                        "Mexico DF.", 2);
                                   
                Twenty gpo4 = new Twenty( 
                        (String)modelo.getValueAt(3, 0),
                        (String)modelo.getValueAt(3, 1),
                        (int)modelo.getValueAt(3, 2),
                        "Ohio EEUU.", 3);
                
banditas[0] = gpo1;
banditas[1] = gpo2;
banditas[2] = gpo3;
banditas[3] = gpo4;

dibujos[0] = gpo1;
dibujos[1] = gpo2;
dibujos[2] = gpo3;
dibujos[3] = gpo4;

for(int  i = 0; i <banditas.length; i++){
    for(int j = i+1; j<banditas.length; j++){
        if(banditas[i].getIntegrantes() < banditas[j].getIntegrantes()){
            
            PB_18131288_Clase_A aux = banditas[i];
            banditas[i] = banditas[j];
            banditas[j] = aux;
            
            PB_18131288_Clase_A auxD = dibujos[i];
            dibujos[i] = dibujos[j];
            dibujos[j] = aux;
            
        }
        
    }
}



    }//GEN-LAST:event_jButGuardarActionPerformed

    private void jButDesfile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDesfile1ActionPerformed
        // TODO add your handling code here:
        setVisible(false); //Oculta este frame
        
        PB_18131288_Frame_03b jFDesfile = new PB_18131288_Frame_03b(this);
        jFDesfile.setVisible(true);
        
    }//GEN-LAST:event_jButDesfile1ActionPerformed

    private void jButDiagramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDiagramaActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        PB_18131288_Frame_03c jFDiagrama = new PB_18131288_Frame_03c(this);
        jFDiagrama.setVisible(true);
        
    }//GEN-LAST:event_jButDiagramaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PB_18131288_Frame_03a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PB_18131288_Frame_03a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PB_18131288_Frame_03a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PB_18131288_Frame_03a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PB_18131288_Frame_03a().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButDesfile;
    private javax.swing.JButton jButDesfile1;
    private javax.swing.JButton jButDiagrama;
    private javax.swing.JButton jButGuardar;
    private javax.swing.JButton jButModificar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabNombre1;
    private javax.swing.JLabel jLabNombre2;
    private javax.swing.JLabel jLabNombre4;
    private javax.swing.JLabel jLabNombre6;
    private javax.swing.JSpinner jSRenglon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabBanda;
    private javax.swing.JTextField jTextGenero;
    private javax.swing.JTextField jTextIntegrantes;
    private javax.swing.JTextField jTextNombre;
    // End of variables declaration//GEN-END:variables
}
