/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_18131250_proyecto_3;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Valentin_PC
 */
public class pb_18131250_Frame_3b extends javax.swing.JFrame {

    /**
     * Creates new form pb_18131250_Frame_3b
     */
    
    pb_18131250_Frame_3a jPrin;
    GrupoMusical [] copia;
    
    public pb_18131250_Frame_3b(pb_18131250_Frame_3a jP) {
        initComponents();
        jPrin = jP;
        copia = new GrupoMusical[jPrin.getRegistroBandas()]; //Copiamos el arreglo del frame principal al segundo frame
        for(int i = 0; i < copia.length; i++){
            copia[i] = jPrin.getBanda(i);
        }
    }
    
    public void dibujar(){
        GrupoMusical [] copiaDibujos = jPrin.dibujos;
        GrupoMusical [] copiaBandas = jPrin.bandas;
        
        
        for(int  i = 0; i <copiaBandas.length; i++){
    for(int j = i+1; j<copiaBandas.length; j++){
        if(copiaBandas[i].getGenero().compareTo(copiaBandas[j].getGenero())>0){
            
            GrupoMusical aux = copiaBandas[i];
            copiaBandas[i] = copiaBandas[j];
            copiaBandas[j] = aux;
            
            GrupoMusical auxD = copiaDibujos[i];
            copiaDibujos[i] = copiaDibujos[j];
            copiaDibujos[j] = aux;
            
        }
        
    }
}
        for(int i = 0; i < 1; i++){
            for(int j = 0; j<copiaDibujos.length; j++){
                
                copiaDibujos[j].mover(jPanelCool, copiaDibujos);
                
                try {
                Thread.sleep(90);
                } catch (InterruptedException ex) {
                Logger.getLogger(pb_18131250_Frame_3a.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanelCool = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Desfilar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Regresar");

        jPanelCool.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanelCoolLayout = new javax.swing.GroupLayout(jPanelCool);
        jPanelCool.setLayout(jPanelCoolLayout);
        jPanelCoolLayout.setHorizontalGroup(
            jPanelCoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelCoolLayout.setVerticalGroup(
            jPanelCoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 295, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dibujar();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pb_18131250_Frame_3b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pb_18131250_Frame_3b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pb_18131250_Frame_3b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pb_18131250_Frame_3b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pb_18131250_Frame_3b(new pb_18131250_Frame_3a()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanelCool;
    // End of variables declaration//GEN-END:variables
}
