package pb_17130819_proyecto_02;

import Utilerias.JTable.ColorCeldas;
import java.awt.Color;
import java.util.Random;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CaRlA
 */
public class PB_17130819_Frame_02 extends javax.swing.JFrame {

    /**
     * Creates new form PB_17130819_Frame_02
     */
    
    //Arreglos paralelos
    Inventario Inicial[] = new Inventario[4];
    Inventario Final[] = new Inventario[4];
    Inventario Venta[] = new Inventario[4];
    
    DefaultTableModel modelo;
    
    public PB_17130819_Frame_02() {
        initComponents();
        
        modelo = (DefaultTableModel)jTableRegistro.getModel();
        
        for (int i=0; i<Inicial.length; i++) //Para inicializar los objetos en los arreglos
        {
            Inicial[i] = new Inventario();
            Final[i] = new Inventario();
            Venta[i] = new Inventario();
        }
        
        Mostrar();
    }

    public void Mostrar() //Método mostrar
    {
        for (int i=0; i<jTableRegistro.getRowCount() - 1; i++)
        {
            jTableRegistro.setValueAt(Inicial[i].getNombre(), i, 0);
            jTableRegistro.setValueAt(Inicial[i].getGalon(), i, 1);
            jTableRegistro.setValueAt(Inicial[i].getPinta(), i, 2);
            jTableRegistro.setValueAt(Inicial[i].getOnza(), i, 3);
            
            jTableRegistro.setValueAt(Final[i].getGalon(), i, 4);
            jTableRegistro.setValueAt(Final[i].getPinta(), i, 5);
            jTableRegistro.setValueAt(Final[i].getOnza(), i, 6);
            
            jTableRegistro.setValueAt(Venta[i].getGalon(), i, 7);
            jTableRegistro.setValueAt(Venta[i].getPinta(), i, 8);
            jTableRegistro.setValueAt(Venta[i].getOnza(), i, 9);
            
            jTableRegistro.setValueAt(Venta[i].getVentas(), i, 10);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRegistro = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonEjemplo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSpinnerCantRen = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jButtonCalcular = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonRandom = new javax.swing.JButton();
        jButton1Alf = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldOnza = new javax.swing.JTextField();
        jButton2Desc = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {"Totales", null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kiosco", "Galón", "Pinta", "Onza", "Galón", "Pinta", "Onza", "Galón", "Pinta", "Onza", "$ Ventas"
            }
        ));
        jScrollPane1.setViewportView(jTableRegistro);
        if (jTableRegistro.getColumnModel().getColumnCount() > 0) {
            jTableRegistro.getColumnModel().getColumn(0).setMinWidth(100);
            jTableRegistro.getColumnModel().getColumn(10).setMinWidth(75);
        }

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inventario inicial");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(204, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Inventario final");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(255, 0, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ventas");
        jLabel3.setOpaque(true);

        jButtonEjemplo.setText("Ejemplo");
        jButtonEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjemploActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Mayor Venta");
        jLabel4.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(255, 204, 0));
        jLabel5.setText("Menor Venta");
        jLabel5.setOpaque(true);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pb_17130819_proyecto_02/Asignacion2.png"))); // NOI18N

        jSpinnerCantRen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerCantRenStateChanged(evt);
            }
        });

        jLabel7.setText("Cantidad de renglones:");

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Carla Georgina Pereyra Lam\nNo. Control: 17130819\nProyecto 02\nControl de inventario y ventas a detalle de\ncierto perfume en distintos puntos de\nventa.");
        jScrollPane2.setViewportView(jTextArea1);

        jButtonRandom.setText("Random");
        jButtonRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandomActionPerformed(evt);
            }
        });

        jButton1Alf.setText("1.- Alfabético");
        jButton1Alf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AlfActionPerformed(evt);
            }
        });

        jLabel9.setText("Valor de la onza:");

        jTextFieldOnza.setText("0");

        jButton2Desc.setText("2.- Descendiente x ventas");
        jButton2Desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2DescActionPerformed(evt);
            }
        });

        jLabel8.setText("Ordenamiento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(2, 2, 2)
                                .addComponent(jSpinnerCantRen, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(2, 2, 2)
                                .addComponent(jTextFieldOnza, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(3, 3, 3)
                                .addComponent(jButton1Alf)
                                .addGap(124, 124, 124)
                                .addComponent(jButtonRandom))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2Desc)
                                .addGap(45, 45, 45)
                                .addComponent(jButtonCalcular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEjemplo)))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldOnza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jButton1Alf)
                    .addComponent(jButtonRandom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinnerCantRen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(jButton2Desc)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonCalcular)
                        .addComponent(jButtonEjemplo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane2))
                    .addComponent(jLabel6))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        // TODO add your handling code here:
        for (int i=0; i<jTableRegistro.getRowCount()-1; i++)
        {
            Inventario uno = new Inventario(); //this
            uno.setNombre(jTableRegistro.getValueAt(i, 0).toString());
            uno.setGalon(Integer.parseInt(jTableRegistro.getValueAt(i, 1).toString()));
            uno.setPinta(Integer.parseInt(jTableRegistro.getValueAt(i, 2).toString()));
            uno.setOnza(Integer.parseInt(jTableRegistro.getValueAt(i, 3).toString()));

            Inventario dos = new Inventario(); //i
            dos.setGalon(Integer.parseInt(jTableRegistro.getValueAt(i, 4).toString()));
            dos.setPinta(Integer.parseInt(jTableRegistro.getValueAt(i, 5).toString()));
            dos.setOnza(Integer.parseInt(jTableRegistro.getValueAt(i, 6).toString()));

            Inventario tres = uno.Venta(dos); //return
            tres.setVentas(Venta[i].OnzasTotales()*Double.parseDouble(jTextFieldOnza.getText()));
            
            Inicial[i] = uno;
            Final[i] = dos;
            Venta[i] = tres;
        }
        
        Mostrar();
        
        ColorCeldas color = new ColorCeldas(jTableRegistro); //Objeto color
        
        int posM=0, posm=0; //Contadores posición mayor y menor
        double mayor=Venta[0].getVentas(), menor=Venta[0].getVentas();
        
        for (int i=1; i<Venta.length; i++) //Comparar para mayor
        {
            if(Venta[i].getVentas() > mayor)
            {
                posM = i;
                mayor = Venta[i].getVentas();
            }
            
            if(Venta[i].getVentas() < menor) //Comparar para menor
            {
                posm = i;
                menor = Venta[i].getVentas();
            }
        }
        
        for (int i=0; i<jTableRegistro.getColumnCount(); i++) //Insertar colores
        {
            color.addCelda(posm, i, Color.yellow);
            color.addCelda(posM, i, Color.blue);
        }
        
        if(band)
        {
            band = false;
            jButtonCalcular.doClick();
        }
    }//GEN-LAST:event_jButtonCalcularActionPerformed
boolean band = true;

    private void jButtonEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjemploActionPerformed
        // TODO add your handling code here:
        jTableRegistro.setValueAt("Galerias", 0, 0);
        jTableRegistro.setValueAt("4 Ways", 1, 0);
        jTableRegistro.setValueAt("Fundadores", 2, 0);
        jTableRegistro.setValueAt("Image Place", 3, 0);
        
        jTableRegistro.setValueAt(4, 0, 1);
        jTableRegistro.setValueAt(5, 0, 2);
        jTableRegistro.setValueAt(14, 0, 3);
        
        jTableRegistro.setValueAt(6, 1, 1);
        jTableRegistro.setValueAt(0, 1, 2);
        jTableRegistro.setValueAt(0, 1, 3);
        
        jTableRegistro.setValueAt(5, 2, 1);
        jTableRegistro.setValueAt(7, 2, 2);
        jTableRegistro.setValueAt(15, 2, 3);
        
        jTableRegistro.setValueAt(3, 3, 1);
        jTableRegistro.setValueAt(1, 3, 2);
        jTableRegistro.setValueAt(4, 3, 3);
        
        jTableRegistro.setValueAt(2, 0, 4);
        jTableRegistro.setValueAt(7, 0, 5);
        jTableRegistro.setValueAt(10, 0, 6);
        
        jTableRegistro.setValueAt(1, 1, 4);
        jTableRegistro.setValueAt(6, 1, 5);
        jTableRegistro.setValueAt(15, 1, 6);
        
        jTableRegistro.setValueAt(3, 2, 4);
        jTableRegistro.setValueAt(0, 2, 5);
        jTableRegistro.setValueAt(0, 2, 6);
        
        jTableRegistro.setValueAt(3, 3, 4);
        jTableRegistro.setValueAt(0, 3, 5);
        jTableRegistro.setValueAt(2, 3, 6);
    }//GEN-LAST:event_jButtonEjemploActionPerformed

    private void jButton1AlfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AlfActionPerformed
        // TODO add your handling code here:
    for(int i=0; i<Inicial.length; i++)
        for(int j=i+1; j<Inicial.length; j++)
            if(Inicial[i].getNombre().compareTo(Inicial[j].getNombre()) >0)
            {
                Inventario aux = Inicial[i];
                Inicial[i] = Inicial[j];
                Inicial[j] = aux;
                
                Inventario aux2 = Final[i];
                Final[i] = Final[j];
                Final[j] = aux2;
                
                Inventario aux3 = Venta[i];
                Venta[i] = Venta[j];
                Venta[j] = aux3;
            }
    
    ColorCeldas color = new ColorCeldas(jTableRegistro); //Objeto color 
        
        int posM=0, posm=0; //Contadores posición mayor y menos
        double mayor=Venta[0].getVentas(), menor=Venta[0].getVentas();
        
        for (int i=1; i<Venta.length; i++) 
        {
            if(Venta[i].getVentas() > mayor) //Comparar para mayor
            {
                posM = i;
                mayor = Venta[i].getVentas();
            }
            
            if(Venta[i].getVentas() < menor) //Comparar para menor
            {
                posm = i;
                menor = Venta[i].getVentas();
            }
        }
        
        for (int i=0; i<jTableRegistro.getColumnCount(); i++) //Insertar colores
        {
            color.addCelda(posm, i, Color.yellow);
            color.addCelda(posM, i, Color.blue);
        }
    
    Mostrar();
    }//GEN-LAST:event_jButton1AlfActionPerformed

    private void jSpinnerCantRenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerCantRenStateChanged
        // TODO add your handling code here:
        modelo.setRowCount((int)jSpinnerCantRen.getValue()+1); //Insertar en la tabla la cantidad de renglones indicada en el Spinner
        
        Inicial = new Inventario[(int)jSpinnerCantRen.getValue()];
        Final = new Inventario[(int)jSpinnerCantRen.getValue()];
        Venta = new Inventario[(int)jSpinnerCantRen.getValue()];
        
        for(int i=0; i<Inicial.length; i++)
        {
            Inicial[i] = new Inventario();
            Final[i] = new Inventario();
            Venta[i] = new Inventario();
        }
        
        jTableRegistro.setValueAt("Totales:", jTableRegistro.getRowCount()-1, 0); //Insertar palabra "totales" en el ultimo renglón de la primer columna
        
        Mostrar();
    }//GEN-LAST:event_jSpinnerCantRenStateChanged

    private void jButtonRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandomActionPerformed
        // TODO add your handling code here:
        Random azar = new Random();
        
        String Nom[] = {"H.E.B", "Famsa", "City Club", "Oriente", "Morelos", "Colón"};
        
        for (int i=0; i<jTableRegistro.getRowCount()-1; i++)
        {
            jTableRegistro.setValueAt(Nom[azar.nextInt(Nom.length)], i, 0);
            jTableRegistro.setValueAt(1+azar.nextInt(10), i, 1);
            jTableRegistro.setValueAt(1+azar.nextInt(10), i, 2);
            jTableRegistro.setValueAt(1 + azar.nextInt(10), i, 3);
            jTableRegistro.setValueAt(1+azar.nextInt(10), i, 4);
            jTableRegistro.setValueAt(1+azar.nextInt(10), i, 5);
            jTableRegistro.setValueAt(1+azar.nextInt(10), i, 6);
        }
    }//GEN-LAST:event_jButtonRandomActionPerformed

    private void jButton2DescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2DescActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<Inicial.length; i++)
            for(int j=i+1; j<Inicial.length; j++)
                if(Venta[i].getVentas() > Venta[j].getVentas())
                {
                    Inventario aux = Inicial[i];
                    Inicial[i] = Inicial[j];
                    Inicial[j] = aux;

                    Inventario aux2 = Final[i];
                    Final[i] = Final[j];
                    Final[j] = aux2;

                    Inventario aux3 = Venta[i];
                    Venta[i] = Venta[j];
                    Venta[j] = aux3;
                }
        
        ColorCeldas color = new ColorCeldas(jTableRegistro);
        
        int posM=0, posm=0;
        double mayor=Venta[0].getVentas(), menor=Venta[0].getVentas();
        
        for (int i=1; i<Venta.length; i++) 
        {
            if(Venta[i].getVentas() > mayor)
            {
                posM = i;
                mayor = Venta[i].getVentas();
            }
            
            if(Venta[i].getVentas() < menor)
            {
                posm = i;
                menor = Venta[i].getVentas();
            }
        }
        for (int i = 0; i < jTableRegistro.getColumnCount(); i++)
        {
            color.addCelda(posm, i, Color.yellow);
            color.addCelda(posM, i, Color.blue);
        }
        
        Mostrar();
    }//GEN-LAST:event_jButton2DescActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PB_17130819_Frame_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PB_17130819_Frame_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PB_17130819_Frame_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PB_17130819_Frame_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PB_17130819_Frame_02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Alf;
    private javax.swing.JButton jButton2Desc;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonEjemplo;
    private javax.swing.JButton jButtonRandom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerCantRen;
    private javax.swing.JTable jTableRegistro;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldOnza;
    // End of variables declaration//GEN-END:variables
}
