/*
 *  Carlos Alberto Vázquez Aguirre 
 */
package Calculadora_Con_Funciones;

import javax.swing.JFrame;

/**
 *
 * @author Ahedeijak
 */
public class NewJCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form NewJCalculadora
     */
    public NewJCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextValor1 = new javax.swing.JTextField();
        jTextValor2 = new javax.swing.JTextField();
        jButPotencia = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabResultado = new javax.swing.JLabel();
        jButDiv = new javax.swing.JButton();
        jButMod = new javax.swing.JButton();
        jButFac = new javax.swing.JButton();
        jButFac1 = new javax.swing.JButton();
        jButComb = new javax.swing.JButton();
        jButAbs = new javax.swing.JButton();
        jBurPerm = new javax.swing.JButton();
        jButBorrar = new javax.swing.JButton();
        jBurPerm1 = new javax.swing.JButton();
        jButRV1 = new javax.swing.JButton();
        jButSen = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButCos = new javax.swing.JButton();
        jButCtg = new javax.swing.JButton();
        jButTan = new javax.swing.JButton();
        jButSec = new javax.swing.JButton();
        jBut7 = new javax.swing.JButton();
        jBut8 = new javax.swing.JButton();
        jBut9 = new javax.swing.JButton();
        jBut4 = new javax.swing.JButton();
        jBut5 = new javax.swing.JButton();
        jBut6 = new javax.swing.JButton();
        jBut1 = new javax.swing.JButton();
        jBut2 = new javax.swing.JButton();
        jBut3 = new javax.swing.JButton();
        jBut0 = new javax.swing.JButton();
        jCheckValor = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setText("Valor 1");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Valor 2");

        jTextValor1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValor1ActionPerformed(evt);
            }
        });

        jTextValor2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextValor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValor2ActionPerformed(evt);
            }
        });

        jButPotencia.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButPotencia.setText("Potencia");
        jButPotencia.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jButPotencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButPotenciaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setText("Resultado:");

        jLabResultado.setBackground(new java.awt.Color(153, 255, 204));
        jLabResultado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabResultado.setOpaque(true);

        jButDiv.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButDiv.setText("Div");
        jButDiv.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jButDiv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDivActionPerformed(evt);
            }
        });

        jButMod.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButMod.setText("Mod");
        jButMod.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jButMod.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButModActionPerformed(evt);
            }
        });

        jButFac.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButFac.setText("Factorial");
        jButFac.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jButFac.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButFacActionPerformed(evt);
            }
        });

        jButFac1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButFac1.setText("Raiz ´2");
        jButFac1.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jButFac1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButFac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButFac1ActionPerformed(evt);
            }
        });

        jButComb.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButComb.setText("Comb");
        jButComb.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jButComb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButComb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCombActionPerformed(evt);
            }
        });

        jButAbs.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButAbs.setText("Abs");
        jButAbs.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jButAbs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButAbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAbsActionPerformed(evt);
            }
        });

        jBurPerm.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jBurPerm.setText("Perm");
        jBurPerm.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jBurPerm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBurPerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBurPermActionPerformed(evt);
            }
        });

        jButBorrar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButBorrar.setText("CE");
        jButBorrar.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jButBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBorrarActionPerformed(evt);
            }
        });

        jBurPerm1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jBurPerm1.setText("n/1");
        jBurPerm1.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jBurPerm1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBurPerm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBurPerm1ActionPerformed(evt);
            }
        });

        jButRV1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButRV1.setText("R=V1");
        jButRV1.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jButRV1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButRV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRV1ActionPerformed(evt);
            }
        });

        jButSen.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButSen.setText("SEN");
        jButSen.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jButSen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButSen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSenActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButCos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButCos.setText("COS");
        jButCos.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jButCos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCosActionPerformed(evt);
            }
        });

        jButCtg.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButCtg.setText("CTG");
        jButCtg.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jButCtg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButCtg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCtgActionPerformed(evt);
            }
        });

        jButTan.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButTan.setText("TAN");
        jButTan.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jButTan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButTanActionPerformed(evt);
            }
        });

        jButSec.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButSec.setText("SEC");
        jButSec.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jButSec.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSecActionPerformed(evt);
            }
        });

        jBut7.setText("7");
        jBut7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut7ActionPerformed(evt);
            }
        });

        jBut8.setText("8");
        jBut8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut8ActionPerformed(evt);
            }
        });

        jBut9.setText("9");
        jBut9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut9ActionPerformed(evt);
            }
        });

        jBut4.setText("4");
        jBut4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut4ActionPerformed(evt);
            }
        });

        jBut5.setText("5");
        jBut5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut5ActionPerformed(evt);
            }
        });

        jBut6.setText("6");
        jBut6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut6ActionPerformed(evt);
            }
        });

        jBut1.setText("1");
        jBut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut1ActionPerformed(evt);
            }
        });

        jBut2.setText("2");
        jBut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut2ActionPerformed(evt);
            }
        });

        jBut3.setText("3");
        jBut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut3ActionPerformed(evt);
            }
        });

        jBut0.setText("0");
        jBut0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut0ActionPerformed(evt);
            }
        });

        jCheckValor.setText("Valor 2");
        jCheckValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckValorActionPerformed(evt);
            }
        });

        jButton2.setText("Series");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextValor1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(jTextValor2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBut7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBut8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBut9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBut4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBut5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBut6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jBut0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jBut1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jBut2)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jBut3)
                                            .addComponent(jCheckValor)))))
                            .addComponent(jButBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBurPerm1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButAbs, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButFac, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButSen, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButFac1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButCos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButComb, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButCtg, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBurPerm, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButTan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButRV1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButSec, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButFac)
                                    .addComponent(jButSen))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButFac1)
                                        .addComponent(jButCos))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButComb)
                                        .addComponent(jButCtg))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jBurPerm)
                                        .addComponent(jButTan))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButRV1)
                                        .addComponent(jButSec))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButPotencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButDiv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButMod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButAbs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBurPerm1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jBut7)
                            .addComponent(jBut8)
                            .addComponent(jBut9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBut4)
                                .addComponent(jBut5)
                                .addComponent(jBut6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBut1)
                            .addComponent(jBut2)
                            .addComponent(jBut3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBut0)
                            .addComponent(jCheckValor))
                        .addGap(12, 12, 12)
                        .addComponent(jButBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextValor1ActionPerformed

    private void jButPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButPotenciaActionPerformed
        // TODO add your handling code here:
        double base = Double.parseDouble(jTextValor1.getText());
        int exp = Integer.parseInt(jTextValor2.getText());
        
        jLabResultado.setText(Mate.potencia(base, exp)+"");
        
    }//GEN-LAST:event_jButPotenciaActionPerformed

    private void jButDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDivActionPerformed
        // TODO add your handling code here:
        double num = Double.parseDouble(jTextValor1.getText());
        double den = Double.parseDouble(jTextValor2.getText());
        
        jLabResultado.setText(Mate.div(num, den)+"");
        
    }//GEN-LAST:event_jButDivActionPerformed

    private void jButModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButModActionPerformed
        // TODO add your handling code here:
        double num = Double.parseDouble(jTextValor1.getText());
        double den = Double.parseDouble(jTextValor2.getText());
        
        jLabResultado.setText(Mate.mod(num, den)+"");
        
        
    }//GEN-LAST:event_jButModActionPerformed

    private void jButFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButFacActionPerformed
        // TODO add your handling code here:
        double num = Double.parseDouble(jTextValor1.getText());
        jLabResultado.setText(Mate.factorial((int) num)+"");
    }//GEN-LAST:event_jButFacActionPerformed

    private void jButFac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButFac1ActionPerformed
        // TODO add your handling code here:
        double n;
        n = Double.parseDouble(jTextValor1.getText());
        jLabResultado.setText(Mate.raiz(n)+"");
        
    }//GEN-LAST:event_jButFac1ActionPerformed

    private void jButCombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCombActionPerformed
        // TODO add your handling code here:
        int x, n;
        n = Integer.parseInt(jTextValor1.getText());
        x = Integer.parseInt(jTextValor2.getText());
        
        jLabResultado.setText(Mate.combinacion(n, x)+"");
    }//GEN-LAST:event_jButCombActionPerformed

    private void jButAbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAbsActionPerformed
        // TODO add your handling code here:
        double x;
        x = Integer.parseInt(jTextValor1.getText());
        jLabResultado.setText(Mate.absoluto(x)+"");
        
    }//GEN-LAST:event_jButAbsActionPerformed

    private void jBurPermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBurPermActionPerformed
        // TODO add your handling code here:
        int x, n;
        n = Integer.parseInt(jTextValor1.getText());
        x = Integer.parseInt(jTextValor2.getText());
        
        jLabResultado.setText(Mate.permutacion(n, x)+"");
    }//GEN-LAST:event_jBurPermActionPerformed

    private void jButBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBorrarActionPerformed
        // TODO add your handling code here:
        jTextValor1.setText("");
        jTextValor2.setText("");
        jLabResultado.setText("");
    }//GEN-LAST:event_jButBorrarActionPerformed

    private void jBurPerm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBurPerm1ActionPerformed
        // TODO add your handling code here:
         double x;
         x = Integer.parseInt(jTextValor1.getText());
         jLabResultado.setText(Mate.inverso(x)+"");
    }//GEN-LAST:event_jBurPerm1ActionPerformed

    private void jButRV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRV1ActionPerformed
        // TODO add your handling code here:
        jTextValor1.setText(jLabResultado.getText());
        jLabResultado.setText("");
        
    }//GEN-LAST:event_jButRV1ActionPerformed

    private void jButSenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSenActionPerformed
        // TODO add your handling code here:
        double n;
        n = Double.parseDouble(jTextValor1.getText());
        jLabResultado.setText(Mate.sen(n)+"");
    }//GEN-LAST:event_jButSenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCosActionPerformed
        // TODO add your handling code here:
        double n;
        n = Double.parseDouble(jTextValor1.getText());
        jLabResultado.setText(Mate.cos(n)+"");
    }//GEN-LAST:event_jButCosActionPerformed

    private void jButCtgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCtgActionPerformed
        // TODO add your handling code here:
        double n;
        n = Double.parseDouble(jTextValor1.getText());
        jLabResultado.setText(Mate.ctg(n)+"");
    }//GEN-LAST:event_jButCtgActionPerformed

    private void jButTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButTanActionPerformed
        // TODO add your handling code here:
        double n;
        n = Double.parseDouble(jTextValor1.getText());
        jLabResultado.setText(Mate.tan(n)+"");
    }//GEN-LAST:event_jButTanActionPerformed

    private void jButSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSecActionPerformed
        // TODO add your handling code here:
        double n;
        n = Double.parseDouble(jTextValor1.getText());
        jLabResultado.setText(Mate.sec(n)+"");
        
    }//GEN-LAST:event_jButSecActionPerformed

    private void jBut0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut0ActionPerformed
        // TODO add your handling code here:
        if(jCheckValor.isSelected())
            jTextValor2.setText(jTextValor2.getText()+"0");
        else jTextValor1.setText(jTextValor1.getText()+"0");
    }//GEN-LAST:event_jBut0ActionPerformed

    private void jTextValor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextValor2ActionPerformed

    private void jBut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut1ActionPerformed
        // TODO add your handling code here:
        if(jCheckValor.isSelected())
            jTextValor2.setText(jTextValor2.getText()+"1");
        else jTextValor1.setText(jTextValor1.getText()+"1");
        
    }//GEN-LAST:event_jBut1ActionPerformed

    private void jBut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut2ActionPerformed
        // TODO add your handling code here:
        if(jCheckValor.isSelected())
            jTextValor2.setText(jTextValor2.getText()+"2");
        else jTextValor1.setText(jTextValor1.getText()+"2");
        
    }//GEN-LAST:event_jBut2ActionPerformed

    private void jCheckValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckValorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckValorActionPerformed

    private void jBut7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut7ActionPerformed
        // TODO add your handling code here:
        if(jCheckValor.isSelected())
            jTextValor2.setText(jTextValor2.getText()+"7");
        else jTextValor1.setText(jTextValor1.getText()+"7");
    }//GEN-LAST:event_jBut7ActionPerformed

    private void jBut8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut8ActionPerformed
        // TODO add your handling code here:
        if(jCheckValor.isSelected())
            jTextValor2.setText(jTextValor2.getText()+"8");
        else jTextValor1.setText(jTextValor1.getText()+"8");
    }//GEN-LAST:event_jBut8ActionPerformed

    private void jBut9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut9ActionPerformed
        // TODO add your handling code here:
        if(jCheckValor.isSelected())
            jTextValor2.setText(jTextValor2.getText()+"9");
        else jTextValor1.setText(jTextValor1.getText()+"9");
    }//GEN-LAST:event_jBut9ActionPerformed

    private void jBut4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut4ActionPerformed
        // TODO add your handling code here:
        if(jCheckValor.isSelected())
            jTextValor2.setText(jTextValor2.getText()+"4");
        else jTextValor1.setText(jTextValor1.getText()+"4");
    }//GEN-LAST:event_jBut4ActionPerformed

    private void jBut5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut5ActionPerformed
        // TODO add your handling code here:
        if(jCheckValor.isSelected())
            jTextValor2.setText(jTextValor2.getText()+"5");
        else jTextValor1.setText(jTextValor1.getText()+"5");
    }//GEN-LAST:event_jBut5ActionPerformed

    private void jBut6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut6ActionPerformed
        // TODO add your handling code here:if(jCheckValor.isSelected())
            if(jCheckValor.isSelected())
            jTextValor2.setText(jTextValor2.getText()+"6");
        else jTextValor1.setText(jTextValor1.getText()+"6");
    }//GEN-LAST:event_jBut6ActionPerformed

    private void jBut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut3ActionPerformed
        // TODO add your handling code here:
        if(jCheckValor.isSelected())
            jTextValor2.setText(jTextValor2.getText()+"3");
        else jTextValor1.setText(jTextValor1.getText()+"3");
    }//GEN-LAST:event_jBut3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
JFrame CalculadoraSeries = new JFrame();
CalculadoraSeries.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBurPerm;
    private javax.swing.JButton jBurPerm1;
    private javax.swing.JButton jBut0;
    private javax.swing.JButton jBut1;
    private javax.swing.JButton jBut2;
    private javax.swing.JButton jBut3;
    private javax.swing.JButton jBut4;
    private javax.swing.JButton jBut5;
    private javax.swing.JButton jBut6;
    private javax.swing.JButton jBut7;
    private javax.swing.JButton jBut8;
    private javax.swing.JButton jBut9;
    private javax.swing.JButton jButAbs;
    private javax.swing.JButton jButBorrar;
    private javax.swing.JButton jButComb;
    private javax.swing.JButton jButCos;
    private javax.swing.JButton jButCtg;
    private javax.swing.JButton jButDiv;
    private javax.swing.JButton jButFac;
    private javax.swing.JButton jButFac1;
    private javax.swing.JButton jButMod;
    private javax.swing.JButton jButPotencia;
    private javax.swing.JButton jButRV1;
    private javax.swing.JButton jButSec;
    private javax.swing.JButton jButSen;
    private javax.swing.JButton jButTan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JRadioButton jCheckValor;
    private javax.swing.JLabel jLabResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextValor1;
    private javax.swing.JTextField jTextValor2;
    // End of variables declaration//GEN-END:variables
}
