/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_18131396_proyecto_01;

import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahdeijack
 */
public class Pa_18131396_Frame_01 extends javax.swing.JFrame {

    /**
     * Creates new form Pa_18131396_Frame_01
     */
    
    private DefaultTableModel modelo;
    private Random azar = new Random();
    Cuerpo [] cuerpos;
    Energia [] energias;
   String nombre;
   double energia;
   double velocidad;
    
    public Pa_18131396_Frame_01() {
        initComponents();
        modelo = (DefaultTableModel)jTab1.getModel();
        jTab1.setShowGrid(true);
        
         jTextNombre.setText("null");
        jTextEnergia.setText("0");
        jTextVelocidad.setText("0");
    }
    
    public void llenar(){
        cuerpos = new Cuerpo[modelo.getRowCount()];
        energias = new Energia[modelo.getRowCount()];
        
        double total = 0;
        double promedio = 0;
        
        for (int i = 0; i < modelo.getRowCount(); i++) {
            
            energias[i] = new Energia(Double.parseDouble(modelo.getValueAt(i, 1)+""),
                                                       Double.parseDouble(modelo.getValueAt(i, 2)+""));
        
           cuerpos[i] = new Cuerpo(modelo.getValueAt(i, 0)+"",
                                                    energias[i]);
           
           modelo.setValueAt(cuerpos[i].getEnergia().obtenerMasa(), i, 3);
           
           total += Double.parseDouble(modelo.getValueAt(i, 3)+"");
           promedio += Double.parseDouble(modelo.getValueAt(i, 2)+"");
        }
        promedio = promedio / modelo.getRowCount();
        jLabMasaTotal.setText(total+"");
        jLabPromedioVelocidad.setText(promedio+"");   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTab1 = new javax.swing.JTable();
        jTextEnergia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextVelocidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButAleatorios = new javax.swing.JButton();
        jTextNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSpin1 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jSpinPos = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jButCalcular = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabMasaTotal = new javax.swing.JLabel();
        jLabPromedioVelocidad = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabMayorNombre = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabMenorNombre = new javax.swing.JLabel();
        jButOrdenMasa = new javax.swing.JButton();
        jButOrdenCuerpo = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabMayorMasa = new javax.swing.JLabel();
        jLabMenorMasa = new javax.swing.JLabel();
        jButEjemplo1 = new javax.swing.JButton();
        jButEjemplo2 = new javax.swing.JButton();
        jButEjemplo3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cuerpo", "Energia", "Velocidad", "Masa"
            }
        ));
        jScrollPane1.setViewportView(jTab1);
        if (jTab1.getColumnModel().getColumnCount() > 0) {
            jTab1.getColumnModel().getColumn(0).setResizable(false);
            jTab1.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 11, 492, 146));

        jTextEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEnergiaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextEnergia, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 77, 56, -1));

        jLabel1.setText("Energia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 57, 56, -1));

        jTextVelocidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVelocidadActionPerformed(evt);
            }
        });
        getContentPane().add(jTextVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 77, 56, -1));

        jLabel2.setText("Velocidad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 57, 56, -1));

        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });
        getContentPane().add(jButAleatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 103, 210, -1));

        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 77, 56, -1));

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 57, 56, -1));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 137, 210, -1));

        jSpin1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));
        jSpin1.setEditor(new javax.swing.JSpinner.NumberEditor(jSpin1, ""));
        jSpin1.setRequestFocusEnabled(false);
        jSpin1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpin1StateChanged(evt);
            }
        });
        getContentPane().add(jSpin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 31, 180, -1));

        jLabel4.setText("Cuerpos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 11, 180, -1));

        jSpinPos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));
        jSpinPos.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinPos, ""));
        jSpinPos.setRequestFocusEnabled(false);
        jSpinPos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinPosStateChanged(evt);
            }
        });
        getContentPane().add(jSpinPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 191, 77, -1));

        jLabel5.setText("Posicion");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 171, 77, -1));

        jButCalcular.setBackground(new java.awt.Color(153, 153, 255));
        jButCalcular.setText("Calcular");
        jButCalcular.setOpaque(false);
        jButCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(jButCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 171, 85, 40));

        jLabel6.setText("Promedio/Total:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 171, 142, -1));

        jLabMasaTotal.setBackground(new java.awt.Color(153, 255, 153));
        jLabMasaTotal.setText("   ");
        jLabMasaTotal.setOpaque(true);
        getContentPane().add(jLabMasaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 171, 110, -1));

        jLabPromedioVelocidad.setBackground(new java.awt.Color(153, 255, 153));
        jLabPromedioVelocidad.setText("  ");
        jLabPromedioVelocidad.setOpaque(true);
        getContentPane().add(jLabPromedioVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 171, 120, -1));

        jLabel7.setText("Mayor");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 191, -1, -1));

        jLabMayorNombre.setBackground(new java.awt.Color(204, 204, 204));
        jLabMayorNombre.setText("  ");
        jLabMayorNombre.setOpaque(true);
        getContentPane().add(jLabMayorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 191, 66, -1));

        jLabel9.setText("Menor");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 191, -1, -1));

        jLabMenorNombre.setBackground(new java.awt.Color(255, 204, 255));
        jLabMenorNombre.setText("  ");
        jLabMenorNombre.setOpaque(true);
        getContentPane().add(jLabMenorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 191, 120, -1));

        jButOrdenMasa.setText("Orden Por Masa");
        jButOrdenMasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButOrdenMasaActionPerformed(evt);
            }
        });
        getContentPane().add(jButOrdenMasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 255, 337, -1));

        jButOrdenCuerpo.setText("Orden por Cuerpo");
        jButOrdenCuerpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButOrdenCuerpoActionPerformed(evt);
            }
        });
        getContentPane().add(jButOrdenCuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 222, 337, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_18131396_proyecto_01/ASIGNACION.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 222, -1, -1));

        jLabMayorMasa.setBackground(new java.awt.Color(204, 204, 204));
        jLabMayorMasa.setText("  ");
        jLabMayorMasa.setOpaque(true);
        getContentPane().add(jLabMayorMasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 191, 66, -1));

        jLabMenorMasa.setBackground(new java.awt.Color(255, 204, 255));
        jLabMenorMasa.setText("  ");
        jLabMenorMasa.setOpaque(true);
        getContentPane().add(jLabMenorMasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 191, 110, -1));

        jButEjemplo1.setText("Ejemplo 1");
        jButEjemplo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemplo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButEjemplo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 289, 337, -1));

        jButEjemplo2.setText("Ejemplo 2");
        jButEjemplo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemplo2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButEjemplo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 323, 337, -1));

        jButEjemplo3.setText("Ejemplo 3");
        jButEjemplo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemplo3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButEjemplo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 357, 337, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEnergiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEnergiaActionPerformed

    private void jTextVelocidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVelocidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextVelocidadActionPerformed

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        // TODO add your handling code here:
        jTextNombre.setText(Nombre.nextNombre());
        jTextEnergia.setText(azar.nextInt(99)*999999+"");
        jTextVelocidad.setText(azar.nextInt(99)*999999+"");
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jSpin1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpin1StateChanged
        // TODO add your handling code here:
        int renglon = Integer.parseInt(jSpin1.getValue()+"");
        modelo.setRowCount(renglon);
    }//GEN-LAST:event_jSpin1StateChanged

    private void jSpinPosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinPosStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinPosStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Object o[] = new Object[3];
         nombre = jTextNombre.getText();
         energia = Double.parseDouble(jTextEnergia.getText()+"");
         velocidad = Double.parseDouble(jTextVelocidad.getText()+"");
                        o[0] = nombre;
                        o[1] = energia;
                        o[2] = velocidad;
                        
         if (nombre.compareTo("")<0 || energia == 0 || velocidad == 0) {
            JOptionPane.showMessageDialog(this, "necesitas llenar todos los parametros");
        } else {
              int renglon = Integer.parseInt(jSpinPos.getValue()+"");        
                if (renglon == modelo.getRowCount()) {
                        modelo.addRow(o);
             } else {
                    modelo.setValueAt(o[0], renglon, 0);
                    modelo.setValueAt(o[1], renglon, 1);
                    modelo.setValueAt(o[2], renglon, 2);
                }
         
        }
         
    jTextNombre.setText("null");
    jTextEnergia.setText("0");
    jTextVelocidad.setText("0");
    jSpinPos.setValue(Integer.parseInt(modelo.getRowCount()+""));
    jSpin1.setValue(Integer.parseInt(modelo.getRowCount()+""));
         

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalcularActionPerformed
        // TODO add your handling code here:
        llenar();
        
                Energia nueva = new Energia(0,0);
                Cuerpo mayor = new Cuerpo("",nueva);
                Cuerpo menor = cuerpos[0];
                
                for (int i = 0; i < cuerpos.length; i++) {
                    if (cuerpos[i].getEnergia().obtenerMasa() > mayor.getEnergia().obtenerMasa()) {
                        mayor = cuerpos[i];        
                    }
                    
                    if (cuerpos[i].getEnergia().obtenerMasa() < menor.getEnergia().obtenerMasa()) {
                        menor = cuerpos[i];
                    }
            }
                
                jLabMayorNombre.setText(mayor.getNombre());
                jLabMayorMasa.setText(mayor.getEnergia().obtenerMasa()+"");
                
                 jLabMenorNombre.setText(menor.getNombre());
                jLabMenorMasa.setText(menor.getEnergia().obtenerMasa()+"");
    }//GEN-LAST:event_jButCalcularActionPerformed

    private void jButOrdenMasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButOrdenMasaActionPerformed
        // TODO add your handling code here:
                jButCalcular.doClick();
                //Cuerpos 
                for (int i = 0; i < cuerpos.length-1; i++) {
                    for (int j = 0; j < cuerpos.length; j++) {
                        if (cuerpos[i].getEnergia().obtenerMasa() < cuerpos[j].getEnergia().obtenerMasa()) {
                            Cuerpo orden = cuerpos[i];
                            cuerpos[i] = cuerpos[j];
                            cuerpos[j] = orden;
                        }
                    }
        }
                
                modelo.setRowCount(0);
                modelo.setRowCount(cuerpos.length);
                for (int i = 0; i < cuerpos.length; i++) {
                   modelo.setValueAt(cuerpos[i].getNombre(), i, 0);
                   modelo.setValueAt(cuerpos[i].getEnergia().getEnergia(), i, 1);
                   modelo.setValueAt(cuerpos[i].getEnergia().getVelocidad(), i, 2);
                   modelo.setValueAt(cuerpos[i].getEnergia().obtenerMasa(), i, 3);
                }
        
    }//GEN-LAST:event_jButOrdenMasaActionPerformed

    private void jButOrdenCuerpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButOrdenCuerpoActionPerformed
        // TODO add your handling code here:
             jButCalcular.doClick();
             
                             for (int i = 0; i < cuerpos.length-1; i++) {
                    for (int j = 0; j < cuerpos.length; j++) {
                        if (cuerpos[i].getNombre().compareTo(cuerpos[j].getNombre())>0) {
                            Cuerpo orden = cuerpos[i];
                            cuerpos[i] = cuerpos[j];
                            cuerpos[j] = orden;
                        }
                    }
        }
                
                modelo.setRowCount(0);
                modelo.setRowCount(cuerpos.length);
                for (int i = 0; i < cuerpos.length; i++) {
                   modelo.setValueAt(cuerpos[i].getNombre(), i, 0);
                   modelo.setValueAt(cuerpos[i].getEnergia().getEnergia(), i, 1);
                   modelo.setValueAt(cuerpos[i].getEnergia().getVelocidad(), i, 2);
                   modelo.setValueAt(cuerpos[i].getEnergia().obtenerMasa(), i, 3);
                }
             
    }//GEN-LAST:event_jButOrdenCuerpoActionPerformed

    private void jButEjemplo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemplo1ActionPerformed
        // TODO add your handling code here:
        jTextNombre.setText("C-25");
        jTextEnergia.setText("0.000000025");
        jTextVelocidad.setText("288000000");
        
    }//GEN-LAST:event_jButEjemplo1ActionPerformed

    private void jButEjemplo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemplo2ActionPerformed
        // TODO add your handling code here:
        jTextNombre.setText("M-18");
        jTextEnergia.setText("0.000000004");
        jTextVelocidad.setText("250000000");
    }//GEN-LAST:event_jButEjemplo2ActionPerformed

    private void jButEjemplo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemplo3ActionPerformed
        // TODO add your handling code here:
        jTextNombre.setText("A-87");
        jTextEnergia.setText("0.000000001");
        jTextVelocidad.setText("295000000");
    }//GEN-LAST:event_jButEjemplo3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pa_18131396_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pa_18131396_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pa_18131396_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pa_18131396_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pa_18131396_Frame_01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButCalcular;
    private javax.swing.JButton jButEjemplo1;
    private javax.swing.JButton jButEjemplo2;
    private javax.swing.JButton jButEjemplo3;
    private javax.swing.JButton jButOrdenCuerpo;
    private javax.swing.JButton jButOrdenMasa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabMasaTotal;
    private javax.swing.JLabel jLabMayorMasa;
    private javax.swing.JLabel jLabMayorNombre;
    private javax.swing.JLabel jLabMenorMasa;
    private javax.swing.JLabel jLabMenorNombre;
    private javax.swing.JLabel jLabPromedioVelocidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpin1;
    private javax.swing.JSpinner jSpinPos;
    private javax.swing.JTable jTab1;
    private javax.swing.JTextField jTextEnergia;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextVelocidad;
    // End of variables declaration//GEN-END:variables
}
