/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_17130767_proyecto_02;

import Utilerias.JTable.ColorCeldas;
import java.awt.Color;
import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gasparin
 */
public class PB_17130767_Frame_01 extends javax.swing.JFrame {

    /**
     * Creates new form PB_17130767_Frame_01
     */
    
     Inventario inicial[] = new Inventario[4];
    Inventario Final[] = new Inventario[4];
    Inventario venta[] = new Inventario[4];
    
    DefaultTableModel modelo;
    
    
    public PB_17130767_Frame_01() {
        initComponents();
        
        modelo = (DefaultTableModel)jTableReg.getModel();
        
        for (int i=0; i<inicial.length; i++)
        {
            inicial[i] = new Inventario();
            Final[i] = new Inventario();
            venta[i] = new Inventario();
        }
        
        Mostrar();
    }

    public void Mostrar()
    {
        for (int i=0; i<jTableReg.getRowCount() - 1; i++)
        {
            jTableReg.setValueAt(inicial[i].getNombre(), i, 0);
            jTableReg.setValueAt(inicial[i].getGalon(), i, 1);
            jTableReg.setValueAt(inicial[i].getPinta(), i, 2);
            jTableReg.setValueAt(inicial[i].getOnza(), i, 3);
            
            jTableReg.setValueAt(Final[i].getGalon(), i, 4);
            jTableReg.setValueAt(Final[i].getPinta(), i, 5);
            jTableReg.setValueAt(Final[i].getOnza(), i, 6);
            
            jTableReg.setValueAt(venta[i].getGalon(), i, 7);
            jTableReg.setValueAt(venta[i].getPinta(), i, 8);
            jTableReg.setValueAt(venta[i].getOnza(), i, 9);
            
            jTableReg.setValueAt(venta[i].getVentas(), i, 10);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReg = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButAlfabetico = new javax.swing.JButton();
        jButCal = new javax.swing.JButton();
        jButAleatorios = new javax.swing.JButton();
        jButEjemplo = new javax.swing.JButton();
        jSpinRen = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextOnza = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableReg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kiosco", "Galon", "Pinta", "Onza", "Galon", "Pinta", "Onza", "Galon", "Pinta", "Onza", "Ventas"
            }
        ));
        jScrollPane1.setViewportView(jTableReg);
        if (jTableReg.getColumnModel().getColumnCount() > 0) {
            jTableReg.getColumnModel().getColumn(0).setMinWidth(95);
        }

        jButton1.setText("Por ventas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButAlfabetico.setText("Orden Alfabetico");
        jButAlfabetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAlfabeticoActionPerformed(evt);
            }
        });

        jButCal.setText("Calcular");
        jButCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalActionPerformed(evt);
            }
        });

        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jButEjemplo.setText("Ejemplo");
        jButEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemploActionPerformed(evt);
            }
        });

        jSpinRen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinRenStateChanged(evt);
            }
        });

        jLabel1.setText("Renglones:");

        jLabel2.setText("Onza:");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButAlfabetico)
                                .addGap(108, 108, 108)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinRen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextOnza, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jButCal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButAleatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButEjemplo)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButCal)
                    .addComponent(jButAleatorios)
                    .addComponent(jButEjemplo)
                    .addComponent(jSpinRen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTextOnza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButAlfabetico)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalActionPerformed
        // TODO add your handling code here:
        for (int i=0; i<jTableReg.getRowCount()-1; i++)
        {
            Inventario uno = new Inventario(); //this
            uno.setNombre(jTableReg.getValueAt(i, 0).toString());
            uno.setGalon(Integer.parseInt(jTableReg.getValueAt(i, 1).toString()));
            uno.setPinta(Integer.parseInt(jTableReg.getValueAt(i, 2).toString()));
            uno.setOnza(Integer.parseInt(jTableReg.getValueAt(i, 3).toString()));

            Inventario dos = new Inventario(); //i
            dos.setGalon(Integer.parseInt(jTableReg.getValueAt(i, 4).toString()));
            dos.setPinta(Integer.parseInt(jTableReg.getValueAt(i, 5).toString()));
            dos.setOnza(Integer.parseInt(jTableReg.getValueAt(i, 6).toString()));

            Inventario tres = uno.Venta(dos); //return
            tres.setVentas(venta[i].OnzasTotales()*Double.parseDouble(jTextOnza.getText()));
            
            inicial[i] = uno;
            Final[i] = dos;
            venta[i] = tres;
        }
        
        Mostrar();
        
        ColorCeldas color = new ColorCeldas(jTableReg);
        
                int posM=0, posm=0;
        double mayor=venta[0].getVentas(), menor=venta[0].getVentas();
        
        for (int i=1; i<venta.length; i++)
        {
            if(venta[i].getVentas() > mayor)
            {
                posM = i;
                mayor = venta[i].getVentas();
            }
            
            if(venta[i].getVentas() < menor)
            {
                posm = i;
                menor = venta[i].getVentas();
            }
        }
         for (int i=0; i<jTableReg.getColumnCount(); i++)
        {
            color.addCelda(posm, i, Color.yellow);
            color.addCelda(posM, i, Color.blue);
        }
        
        if(band)
        {
            band = false;
            jButCal.doClick();
        }
    }//GEN-LAST:event_jButCalActionPerformed
    boolean band = true;
    private void jButEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemploActionPerformed
        // TODO add your handling code here:
        jTableReg.setValueAt("Cuatro caminos", 0, 0);
        jTableReg.setValueAt("Galerias", 1, 0);
        jTableReg.setValueAt("Senderos", 2, 0);
        jTableReg.setValueAt("Independencia", 3, 0);
        
        jTableReg.setValueAt(4, 0, 1);
        jTableReg.setValueAt(5, 0, 2);
        jTableReg.setValueAt(14, 0, 3);
        
        jTableReg.setValueAt(6, 1, 1);
        jTableReg.setValueAt(0, 1, 2);
        jTableReg.setValueAt(0, 1, 3);
        
        jTableReg.setValueAt(5, 2, 1);
        jTableReg.setValueAt(7, 2, 2);
        jTableReg.setValueAt(15, 2, 3);
        
        jTableReg.setValueAt(3, 3, 1);
        jTableReg.setValueAt(1, 3, 2);
        jTableReg.setValueAt(4, 3, 3);
        
        jTableReg.setValueAt(2, 0, 4);
        jTableReg.setValueAt(7, 0, 5);
        jTableReg.setValueAt(10, 0, 6);
        
        jTableReg.setValueAt(1, 1, 4);
        jTableReg.setValueAt(6, 1, 5);
        jTableReg.setValueAt(15, 1, 6);
        
        jTableReg.setValueAt(3, 2, 4);
        jTableReg.setValueAt(0, 2, 5);
        jTableReg.setValueAt(0, 2, 6);
        
        jTableReg.setValueAt(3, 3, 4);
        jTableReg.setValueAt(0, 3, 5);
        jTableReg.setValueAt(2, 3, 6);

    }//GEN-LAST:event_jButEjemploActionPerformed

    private void jButAlfabeticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAlfabeticoActionPerformed
        // TODO add your handling code here:
            for(int i=0; i<inicial.length; i++)
        for(int j=i+1; j<inicial.length; j++)
            if(inicial[i].getNombre().compareTo(inicial[j].getNombre()) >0)
            {
                Inventario aux = inicial[i];
                inicial[i] = inicial[j];
                inicial[j] = aux;
                
                Inventario aux2 = Final[i];
                Final[i] = Final[j];
                Final[j] = aux2;
                
                Inventario aux3 = venta[i];
                venta[i] = venta[j];
                venta[j] = aux3;
            }
    
    ColorCeldas color = new ColorCeldas(jTableReg); //Objeto color 
        
        int posM=0, posm=0; //Contadores posición mayor y menos
        double mayor=venta[0].getVentas(), menor=venta[0].getVentas();
        
        for (int i=1; i<venta.length; i++) 
        {
            if(venta[i].getVentas() > mayor) //Comparar para mayor
            {
                posM = i;
                mayor = venta[i].getVentas();
            }
            
            if(venta[i].getVentas() < menor) //Comparar para menor
            {
                posm = i;
                menor = venta[i].getVentas();
            }
        }
        
        for (int i=0; i<jTableReg.getColumnCount(); i++) //Insertar colores
        {
            color.addCelda(posm, i, Color.yellow);
            color.addCelda(posM, i, Color.blue);
        }
    
    Mostrar();

    }//GEN-LAST:event_jButAlfabeticoActionPerformed

    private void jSpinRenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinRenStateChanged
        // TODO add your handling code here:
        modelo.setRowCount((int)jSpinRen.getValue()+1);
        
        inicial = new Inventario[(int)jSpinRen.getValue()];
        Final = new Inventario[(int)jSpinRen.getValue()];
        venta = new Inventario[(int)jSpinRen.getValue()];
        
        for(int i=0; i<inicial.length; i++)
        {
            inicial[i] = new Inventario();
            Final[i] = new Inventario();
            venta[i] = new Inventario();
        }
        
        jTableReg.setValueAt("Totales:", jTableReg.getRowCount()-1, 0);
        
        Mostrar();

    }//GEN-LAST:event_jSpinRenStateChanged

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        // TODO add your handling code here:
        Random azar = new Random();
        
        String Nom[] = {"Soriana Ote", "Morelos", "Revolución", "Colón", "Jacarandas", "El fresno"};
        
        for (int i=0; i<jTableReg.getRowCount()-1; i++)
        {
            jTableReg.setValueAt(Nom[azar.nextInt(Nom.length)], i, 0);
            jTableReg.setValueAt(1+azar.nextInt(10), i, 1);
            jTableReg.setValueAt(1+azar.nextInt(10), i, 2);
            jTableReg.setValueAt(1 + azar.nextInt(10), i, 3);
            jTableReg.setValueAt(1+azar.nextInt(10), i, 4);
            jTableReg.setValueAt(1+azar.nextInt(10), i, 5);
            jTableReg.setValueAt(1+azar.nextInt(10), i, 6);
        }
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<inicial.length; i++)
            for(int j=i+1; j<inicial.length; j++)
                if(venta[i].getVentas() > venta[j].getVentas())
                {
                    Inventario aux = inicial[i];
                    inicial[i] = inicial[j];
                    inicial[j] = aux;

                    Inventario aux2 = Final[i];
                    Final[i] = Final[j];
                    Final[j] = aux2;

                    Inventario aux3 = venta[i];
                    venta[i] = venta[j];
                    venta[j] = aux3;
                }
        
        ColorCeldas color = new ColorCeldas(jTableReg);
        
        int posM=0, posm=0;
        double mayor=venta[0].getVentas(), menor=venta[0].getVentas();
        
        for (int i=1; i<venta.length; i++) 
        {
            if(venta[i].getVentas() > mayor)
            {
                posM = i;
                mayor = venta[i].getVentas();
            }
            
            if(venta[i].getVentas() < menor)
            {
                posm = i;
                menor = venta[i].getVentas();
            }
        }
        for (int i = 0; i < jTableReg.getColumnCount(); i++)
        {
            color.addCelda(posm, i, Color.yellow);
            color.addCelda(posM, i, Color.blue);
        }
        
        Mostrar();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PB_17130767_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PB_17130767_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PB_17130767_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PB_17130767_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PB_17130767_Frame_01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButAlfabetico;
    private javax.swing.JButton jButCal;
    private javax.swing.JButton jButEjemplo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinRen;
    private javax.swing.JTable jTableReg;
    private javax.swing.JTextField jTextOnza;
    // End of variables declaration//GEN-END:variables
}
