/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_05_162019_AplicacionEmpleadoHerenciaArchivo;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aa625
 */
public class jFrameReporte extends javax.swing.JFrame {

    /**
     * Creates new form jFrameReporte
     */
    //Atributos del frame
    jFrameMenu jfMenu; //para conectar los Frames secundarios con el Menu
    Empleado [] copia;
    DefaultTableModel modelo;
    
    public jFrameReporte(jFrameMenu jfm) {
        initComponents();
        
        jfMenu = jfm; //para conectar los Frames secundarios con el Menu
        
        jLabEmpReg1.setText(jfMenu.getEmpleadosRegistrados()+""); //actualiza la etiqueta del FrameReporte del numero de empleado
        
        copia = new Empleado[jfMenu.getEmpleadosRegistrados()];
        
        for(int i =0; i<copia.length; i++)
            copia[i] = jfMenu.getEmpleado(i); //es para poder trabajar en la copia y no modificar el arreglo original: el del FrameMenu
        
        modelo = (DefaultTableModel)jTableReporte.getModel();
        modelo.setRowCount(copia.length);
        jTableReporte.setShowGrid(true);
        
        mostrar();
    }
    
    public void mostrar()
    {
        double total = 0;
        
        
        
        for(int r=0; r<copia.length; r++)
        {
            
            for(int c=0; c<modelo.getColumnCount(); c++)
            {    
                modelo.setValueAt(null,r,c);
            }
            
            modelo.setValueAt(copia[r].getNumero(), r, 0);
            modelo.setValueAt(copia[r].getNombre(), r, 1);
            
            if(copia[r] instanceof Taller) //Un objeto es una instancia de una clase
            {
                Taller tal = (Taller)copia[r]; //el mismo objeto o hacemos de referencia de Taller
                
                modelo.setValueAt(tal.getPiezas(),r,2);
                modelo.setValueAt(tal.getPrecioUnitario(), r, 3);
            }    
            
            if(copia[r] instanceof Ventas) //Un objeto es una instancia de una clase
            {
                Ventas ven = (Ventas)copia[r]; //el mismo objeto o hacemos de referencia de Taller //un casteo
                
                modelo.setValueAt(ven.getVentasTotales(),r,4);
                modelo.setValueAt(ven.getComision(), r, 5);
            }  
            
            if(copia[r] instanceof Administrativo) //Un objeto es una instancia de una clase
            {
                Administrativo adm = (Administrativo)copia[r]; //el mismo objeto o hacemos de referencia de Taller //un casteo
                
                modelo.setValueAt(adm.getDiasTrabajados(),r,6);
                modelo.setValueAt(adm.getSueldoDiario(), r, 7);
            }    
            
            if(copia[r] instanceof Ejecutivo) //Un objeto es una instancia de una clase
            {
                Ejecutivo eje = (Ejecutivo)copia[r]; //el mismo objeto o hacemos de referencia de Taller //un casteo
                
                modelo.setValueAt(eje.getDiasTrabajados(),r,6);
                modelo.setValueAt(eje.getSueldoDiario(), r, 7);
                modelo.setValueAt(eje.getBono(), r, 8);
            }   
            
            total += copia[r].sueldo();
            
            modelo.setValueAt(copia[r].sueldo(), r, 9);
        }
        
        jLabSueldoTotal.setText(total+"");
       
    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButRegresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabSueldoTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReporte = new javax.swing.JTable();
        jButPorSueldo = new javax.swing.JButton();
        jButPorAlfabetico = new javax.swing.JButton();
        jButPorOriginal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabEmpReg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jButRegresar.setText("REGRESAR");
        jButRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegresarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Empleados registrados:");

        jLabSueldoTotal.setBackground(new java.awt.Color(204, 153, 0));
        jLabSueldoTotal.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabSueldoTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabSueldoTotal.setOpaque(true);

        jTableReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUMERO", "NOMBRE", "# PIEZAS", "P. UNITARIO $", "VENTAS $", "% COMISION", "DIAS TRAB.", "SUELDO DIARIO", "BONO", "SUELDO"
            }
        ));
        jScrollPane1.setViewportView(jTableReporte);
        if (jTableReporte.getColumnModel().getColumnCount() > 0) {
            jTableReporte.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTableReporte.getColumnModel().getColumn(1).setPreferredWidth(175);
            jTableReporte.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableReporte.getColumnModel().getColumn(7).setPreferredWidth(90);
            jTableReporte.getColumnModel().getColumn(9).setPreferredWidth(90);
        }

        jButPorSueldo.setText("POR SUELDO");
        jButPorSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButPorSueldoActionPerformed(evt);
            }
        });

        jButPorAlfabetico.setText("ALFABETICO");
        jButPorAlfabetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButPorAlfabeticoActionPerformed(evt);
            }
        });

        jButPorOriginal.setText("ORDEN ORIGINAL");
        jButPorOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButPorOriginalActionPerformed(evt);
            }
        });

        jLabel1.setText("TOTAL:");

        jLabEmpReg1.setBackground(new java.awt.Color(204, 153, 0));
        jLabEmpReg1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabEmpReg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabEmpReg1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButPorAlfabetico)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabEmpReg1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jButPorSueldo))
                                .addGap(41, 41, 41)
                                .addComponent(jButPorOriginal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabSueldoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButRegresar))
                        .addGap(3, 3, 3)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabSueldoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButPorSueldo)
                        .addComponent(jButPorAlfabetico)
                        .addComponent(jButPorOriginal)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButRegresar)
                            .addComponent(jLabEmpReg1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 19, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegresarActionPerformed
        // TODO add your handling code here:
        //Borrar el registro
        dispose(); //quita el objeto de la memoria "this"

        jfMenu.getEtiqueta().setBackground(Color.PINK); //AL DARLE REGRESAR LA ETIQUETA DEL FRAME MENU CAMBIA DE COLOR: A ROSA

        jfMenu.setVisible(true); //VUELVE A "MOSTRAR" EL FRAME MENU
    }//GEN-LAST:event_jButRegresarActionPerformed

    private void jButPorSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButPorSueldoActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<copia.length-1; i++)
            for(int j=i+1; j<copia.length; j++)
                if(copia[i].sueldo() < copia[j].sueldo())
                {    
                    Empleado aux = copia[i];
                    copia[i] = copia[j];
                    copia[j] = aux;
                }
        mostrar();
    }//GEN-LAST:event_jButPorSueldoActionPerformed

    private void jButPorAlfabeticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButPorAlfabeticoActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<copia.length-1; i++)
            for(int j=i+1; j<copia.length; j++)
                if(copia[i].getNombre().compareTo(copia[j].getNombre())>0)
                {    
                    Empleado aux = copia[i];
                    copia[i] = copia[j];
                    copia[j] = aux;
                }
        mostrar();    
    }//GEN-LAST:event_jButPorAlfabeticoActionPerformed

    private void jButPorOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButPorOriginalActionPerformed
        // TODO add your handling code here:
        for(int i =0; i<copia.length; i++)
            copia[i] = jfMenu.getEmpleado(i); //es para poder trabajar en la copia y no modificar el arreglo original: el del FrameMenu
        mostrar();
    }//GEN-LAST:event_jButPorOriginalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrameReporte(new jFrameMenu()).setVisible(true); //aqui mandarle un nuevo frame para que no marque error
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButPorAlfabetico;
    private javax.swing.JButton jButPorOriginal;
    private javax.swing.JButton jButPorSueldo;
    private javax.swing.JButton jButRegresar;
    private javax.swing.JLabel jLabEmpReg1;
    private javax.swing.JLabel jLabSueldoTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableReporte;
    // End of variables declaration//GEN-END:variables
}
