package GUI;


import Clases.Conexion;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSeparator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ahdeijack
 */
public class CONSULTAS extends javax.swing.JFrame {
    Conexion objCxn = new Conexion();
    int mostrar = 1;
    String d1, d2, d3, d4, d5 ,d6 ,d7, d8, d9, d10, d11, clave;
    Random r;
    /**
     * Creates new form CONSULTAS
     */
    public CONSULTAS() {
        initComponents();
         mostrarTablas(0);
         ocultar();
    }
    
    public void ocultar(){
         Label1.setVisible(false);
         Label2.setVisible(false);
         Label3.setVisible(false);
         Label4.setVisible(false);
         Label5.setVisible(false);
         Label6.setVisible(false);
         Label7.setVisible(false);
         Label8.setVisible(false);
         Label9.setVisible(false);
         Label10.setVisible(false);
         Label11.setVisible(false);
         
         Dato1.setVisible(false);
         Dato2.setVisible(false);
         Dato3.setVisible(false);
         Dato4.setVisible(false);
         Dato5.setVisible(false);
         Dato6.setVisible(false);
         Dato7.setVisible(false);
         Dato8.setVisible(false);
         Dato9.setVisible(false);
         Dato10.setVisible(false);
         Dato11.setVisible(false);
         
         Dato1.setText("");
         Dato2.setText("");
         Dato3.setText("");
         Dato4.setText("");
         Dato5.setText("");
         Dato6.setText("");
         Dato7.setText("");
         Dato8.setText("");
         Dato9.setText("");
         Dato10.setText("");
         Dato11.setText("");
         
         B1.setVisible(false);
         B2.setVisible(false);
         B3.setVisible(false);
         B4.setVisible(false);
         B5.setVisible(false);
         B6.setVisible(false);
         
         
         M1.setVisible(false);
         M2.setVisible(false);
         M3.setVisible(false);
         M4.setVisible(false);
         M5.setVisible(false);
         M6.setVisible(false);
         
         R1.setVisible(false);
         R2.setVisible(false);
         R3.setVisible(false);
         R4.setVisible(false);
         R5.setVisible(false);
         R6.setVisible(false);

    }
    public void mostrarTablas(int mostrar){
        switch (mostrar) {
            case 0:
                objCxn.mostrarDatosAerolinea(jTable1);
                break;
            case 1:
                objCxn.mostrarDatosAvion(jTable1);
                break;
            case 2:
                objCxn.mostrarDatosVuelo(jTable1);
                break;
            case 3:
                objCxn.mostrarDatosAeropuerto(jTable1);
                break;
            case 4:
                objCxn.mostrarDatosReservaciones(jTable1);
                break;
            case 5:
                objCxn.mostrarDatosCliente(jTable1);
                break;
            case 6:
                objCxn.vuelo_reservacion(jTable1);
                break;
            case 7:
                objCxn.cliente_reservacion(jTable1);
                break;
            case 8:
                objCxn.pago_tarjeta(jTable1);
                break;
            case 9:
                objCxn.cliente_telerfono(jTable1);
                break;         
            case 10:
                objCxn.asiento(jTable1);
                break;
            case 11:
                objCxn.pago(jTable1);
                break;
            case 12:
                objCxn.tarifa(jTable1);
                break;
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField10 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboSeleccion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboAdd = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        Label1 = new javax.swing.JLabel();
        Separador = new javax.swing.JSeparator();
        Label2 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        Label6 = new javax.swing.JLabel();
        Label7 = new javax.swing.JLabel();
        Label8 = new javax.swing.JLabel();
        Label9 = new javax.swing.JLabel();
        Label10 = new javax.swing.JLabel();
        Label11 = new javax.swing.JLabel();
        Dato1 = new javax.swing.JTextField();
        Dato2 = new javax.swing.JTextField();
        Dato3 = new javax.swing.JTextField();
        Dato4 = new javax.swing.JTextField();
        Dato5 = new javax.swing.JTextField();
        Dato6 = new javax.swing.JTextField();
        Dato7 = new javax.swing.JTextField();
        Dato8 = new javax.swing.JTextField();
        Dato9 = new javax.swing.JTextField();
        Dato10 = new javax.swing.JTextField();
        Dato11 = new javax.swing.JTextField();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        Seleccion = new javax.swing.JButton();
        M1 = new javax.swing.JButton();
        M2 = new javax.swing.JButton();
        M3 = new javax.swing.JButton();
        M4 = new javax.swing.JButton();
        M5 = new javax.swing.JButton();
        M6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        R1 = new javax.swing.JButton();
        R2 = new javax.swing.JButton();
        R3 = new javax.swing.JButton();
        R4 = new javax.swing.JButton();
        R5 = new javax.swing.JButton();
        R6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agencia de vuelos.");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 982, 230));

        jComboSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aerolineas", "Aviones", "Vuelos", "Aeropuerto", "Reservaciones", "Clientes", "Vuelos y Reservaciones", "Clientes y Reservaciones", "Pagos con tarjeta", "Telefono de clientes", "Asiento", "Pago", "Tarifa", " ", " " }));
        jComboSeleccion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboSeleccionItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 272, 118, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consultar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 252, 118, -1));

        jButton1.setText("Borrar");
        jButton1.setToolTipText("Borra un registro de la consulta actual.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 252, 842, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Añadir");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 314, 118, -1));

        jComboAdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aerolineas", "Aviones", "Vuelos", "Aeropuerto", "Reservaciones", "Clientes" }));
        jComboAdd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboAddItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 334, 118, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 298, 118, 10));

        Label1.setText("Clave");
        getContentPane().add(Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 70, -1));

        Separador.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(Separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 252, 10, 149));

        Label2.setText("Clave");
        getContentPane().add(Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 290, 70, -1));

        Label3.setText("Clave");
        getContentPane().add(Label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 290, 70, -1));

        Label4.setText("Clave");
        getContentPane().add(Label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 290, 70, -1));

        Label5.setText("Clave");
        getContentPane().add(Label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 290, 70, -1));

        Label6.setText("Clave");
        getContentPane().add(Label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 70, -1));

        Label7.setText("Clave");
        getContentPane().add(Label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 290, 70, -1));

        Label8.setText("Clave");
        getContentPane().add(Label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 290, 70, -1));

        Label9.setText("Clave");
        getContentPane().add(Label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 286, 70, -1));

        Label10.setText("Clave");
        getContentPane().add(Label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 286, 70, -1));

        Label11.setText("Clave");
        getContentPane().add(Label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 286, 70, -1));
        getContentPane().add(Dato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 306, 70, -1));
        getContentPane().add(Dato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 306, 70, -1));
        getContentPane().add(Dato3, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 306, 70, -1));
        getContentPane().add(Dato4, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 306, 70, -1));
        getContentPane().add(Dato5, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 306, 70, -1));
        getContentPane().add(Dato6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 306, 70, -1));
        getContentPane().add(Dato7, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 306, 70, -1));
        getContentPane().add(Dato8, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 306, 70, -1));
        getContentPane().add(Dato9, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 306, 70, -1));
        getContentPane().add(Dato10, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 306, 70, -1));
        getContentPane().add(Dato11, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 306, 70, -1));

        B1.setText("Agregar");
        B1.setToolTipText("Aerolineas");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        getContentPane().add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 337, -1, -1));

        B2.setText("Agregar");
        B2.setToolTipText("Aviones");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        getContentPane().add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 371, -1, -1));

        B3.setText("Agregar");
        B3.setToolTipText("Vuelos");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        getContentPane().add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 337, -1, -1));

        B4.setText("Agregar");
        B4.setToolTipText("Aeropuertos");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        getContentPane().add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 371, -1, -1));

        B5.setText("Agregar");
        B5.setToolTipText("Reservaciones");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });
        getContentPane().add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 337, -1, -1));

        B6.setText("Agregar");
        B6.setToolTipText("Clientes");
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });
        getContentPane().add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 371, -1, -1));

        Seleccion.setText("Seleccionar");
        Seleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionActionPerformed(evt);
            }
        });
        getContentPane().add(Seleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 365, 118, -1));

        M1.setText("Modificar");
        M1.setToolTipText("Aerolineas");
        M1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M1ActionPerformed(evt);
            }
        });
        getContentPane().add(M1, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 337, -1, -1));

        M2.setText("Modificar");
        M2.setToolTipText("Aviones");
        M2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M2ActionPerformed(evt);
            }
        });
        getContentPane().add(M2, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 371, -1, -1));

        M3.setText("Modificar");
        M3.setToolTipText("Vuelos");
        M3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M3ActionPerformed(evt);
            }
        });
        getContentPane().add(M3, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 337, -1, -1));

        M4.setText("Modificar");
        M4.setToolTipText("Aeropuertos");
        M4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M4ActionPerformed(evt);
            }
        });
        getContentPane().add(M4, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 371, -1, -1));

        M5.setText("Modificar");
        M5.setToolTipText("Reservaciones");
        M5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M5ActionPerformed(evt);
            }
        });
        getContentPane().add(M5, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 337, -1, -1));

        M6.setText("Modificar");
        M6.setToolTipText("Clientes");
        M6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M6ActionPerformed(evt);
            }
        });
        getContentPane().add(M6, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 371, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Carlos Alberto Vázquez Aguirre.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 300, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Proyecto Unidad 5");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 300, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("18131288");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 300, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Aleatorio");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 70, -1));

        R1.setText("Llenar");
        R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1ActionPerformed(evt);
            }
        });
        getContentPane().add(R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 80, -1));

        R2.setText("Llenar");
        R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2ActionPerformed(evt);
            }
        });
        getContentPane().add(R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 80, -1));

        R3.setText("Llenar");
        R3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3ActionPerformed(evt);
            }
        });
        getContentPane().add(R3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 80, -1));

        R4.setText("Llenar");
        R4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R4ActionPerformed(evt);
            }
        });
        getContentPane().add(R4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 80, -1));

        R5.setText("Llenar");
        R5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R5ActionPerformed(evt);
            }
        });
        getContentPane().add(R5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 80, -1));

        R6.setText("Llenar");
        R6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R6ActionPerformed(evt);
            }
        });
        getContentPane().add(R6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboSeleccionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboSeleccionItemStateChanged
        // TODO add your handling code here:
                mostrar = jComboSeleccion.getSelectedIndex();

                mostrarTablas(mostrar);
    }//GEN-LAST:event_jComboSeleccionItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clave = JOptionPane.showInputDialog("Inserta la clave a eliminar", clave);

        mostrar = jComboSeleccion.getSelectedIndex();
        switch (mostrar) {
            case 0:
                objCxn.eliminarAerolineas(clave);
                objCxn.mostrarDatosAerolinea(jTable1);
                clave ="";
                break;
            case 1:
                objCxn.eliminarAvion(clave);
                objCxn.mostrarDatosAvion(jTable1);
                clave ="";
                break;
            case 2:
                objCxn.eliminarVuelo(clave);
                objCxn.mostrarDatosVuelo(jTable1);
                clave ="";
                break;
            case 3:
                objCxn.eliminarAeropuerto(clave);
                objCxn.mostrarDatosAeropuerto(jTable1);
                clave ="";
                break;
            case 4:
                objCxn.eliminarReservaciones(clave);
                objCxn.mostrarDatosReservaciones(jTable1);
                clave ="";
                break;
            case 5:
                objCxn.eliminarClientes(clave);
                objCxn.mostrarDatosCliente(jTable1);
                clave ="";
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboAddItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboAddItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboAddItemStateChanged

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
                d1 = Dato1.getText();
                d2 = Dato2.getText();
   
           try {
               objCxn.insertarAerolinea(d1, d2);
           } catch (SQLException ex) {
               Logger.getLogger(CONSULTAS.class.getName()).log(Level.SEVERE, null, ex);
           }
       d1 = "";
       d2 = "";
        objCxn.mostrarDatosAerolinea(jTable1);
        ocultar();

    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
d1 = Dato1.getText();
d2 = Dato2.getText();
d3 = Dato3.getText();
d4 = Dato4.getText();
d5 = Dato5.getText();        

           try {
               objCxn.insertarAvion(d1, d2, d3, d4, d5);
           } catch (SQLException ex) {
               Logger.getLogger(CONSULTAS.class.getName()).log(Level.SEVERE, null, ex);
           }
           
d1="";
d2="";
d3="";
d4="";
d5="";
objCxn.mostrarDatosAvion(jTable1);
        ocultar();
       
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
d1 = Dato1.getText();
d2 = Dato2.getText();
d3 = Dato3.getText();
d4 = Dato4.getText();
d5 = Dato5.getText();    
d6 = Dato6.getText();
d7 = Dato7.getText();
d8 = Dato8.getText();    


           try {
               objCxn.insertarVuelo(d1, d2, d3, d4, d5,d6,d7,d8);
           } catch (SQLException ex) {
               Logger.getLogger(CONSULTAS.class.getName()).log(Level.SEVERE, null, ex);
           }
           
d1="";
d2="";
d3="";
d4="";
d5="";
d6="";
d7="";
d8="";
objCxn.mostrarDatosVuelo(jTable1);
        ocultar();
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
        d1 = Dato1.getText();
d2 = Dato2.getText();
d3 = Dato3.getText();
d4 = Dato4.getText();
d5 = Dato5.getText();    
d6 = Dato6.getText();
d7 = Dato7.getText();
d8 = Dato8.getText();    


           try {
               objCxn.insertarAeropuerto(d1, d2, d3, d4, d5,d6,d7,d8);
           } catch (SQLException ex) {
               Logger.getLogger(CONSULTAS.class.getName()).log(Level.SEVERE, null, ex);
           }
           
d1="";
d2="";
d3="";
d4="";
d5="";
d6="";
d7="";
d8="";
objCxn.mostrarDatosAeropuerto(jTable1);
        ocultar();
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:
d1 = Dato1.getText();
d2 = Dato2.getText();
d3 = Dato3.getText();
d4 = Dato4.getText();
d5 = Dato5.getText();    
           try {
               objCxn.insertarReservaciones(d1, d2, d3, d4, d5);
           } catch (SQLException ex) {
               Logger.getLogger(CONSULTAS.class.getName()).log(Level.SEVERE, null, ex);
           }           
d1="";
d2="";
d3="";
d4="";
d5="";
objCxn.mostrarDatosReservaciones(jTable1);
        ocultar();
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        // TODO add your handling code here:
        d1 = Dato1.getText();
d2 = Dato2.getText();
d3 = Dato3.getText();
d4 = Dato4.getText();
d5 = Dato5.getText();    
d6 = Dato6.getText();
d7 = Dato7.getText();
d8 = Dato8.getText();    
d9 = Dato9.getText();
d10 = Dato10.getText();
d11 = Dato11.getText();

           try {
               objCxn.insertarCliente(d1, d2, d3, d4, d5,d6,d7,d8,d9,d10,d11);
           } catch (SQLException ex) {
               Logger.getLogger(CONSULTAS.class.getName()).log(Level.SEVERE, null, ex);
           }
           
d1="";
d2="";
d3="";
d4="";
d5="";
d6="";
d7="";
d8="";
d9="";
d10="";
d11="";
objCxn.mostrarDatosCliente(jTable1);
        ocultar();
    }//GEN-LAST:event_B6ActionPerformed

    private void SeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionActionPerformed
        // TODO add your handling code here:
       int cambio = jComboAdd.getSelectedIndex();
        System.out.println(cambio);
        switch (cambio) {
            case 0:
                ocultar();
                Label1.setVisible(true);
                Label1.setText("Clave Linea");
                Label2.setVisible(true);
                Label2.setText("Nombre Aerolinea.");
                Dato1.setVisible(true);
                Dato2.setVisible(true);
                B1.setVisible(true);
                M1.setVisible(true);
                R1.setVisible(true);
                break;
            case 1:
                ocultar();
                Label1.setVisible(true);
                Label1.setText("Clave Avion");
                Label2.setVisible(true);
                Label2.setText("Tipo Avion");
                Label3.setVisible(true);
                Label3.setText("Numero Pasajeros (Numero)");
                Label4.setVisible(true);
                Label4.setText("Agencia");
                Label5.setVisible(true);
                Label5.setText("Linea");
                
                Dato1.setVisible(true);
                Dato2.setVisible(true);
                Dato3.setVisible(true);
                Dato4.setVisible(true);
                Dato5.setVisible(true);

                Dato2.setVisible(true);
                B2.setVisible(true);
                M2.setVisible(true);
                R2.setVisible(true);
                
                break;
            case 2:
                ocultar();
                Label1.setVisible(true);
                Label1.setText("Clave Vuelo");
                Label2.setVisible(true);
                Label2.setText("Estado de Vuelo");
                Label3.setVisible(true);
                Label3.setText("Tipo de Vuelo");
                Label4.setVisible(true);
                Label4.setText("Hora Destino");
                Label5.setVisible(true);
                Label5.setText("Dia Destino");
                Label6.setVisible(true);
                Label6.setText("Hora Origen");
                Label7.setVisible(true);
                Label7.setText("Dia Origen");
                Label8.setVisible(true);
                Label8.setText("Clave avion");
                
                Dato1.setVisible(true);
                Dato2.setVisible(true);
                Dato3.setVisible(true);
                Dato4.setVisible(true);
                Dato5.setVisible(true);
                Dato6.setVisible(true);
                Dato7.setVisible(true);
                Dato8.setVisible(true);
                
                B3.setVisible(true);
                M3.setVisible(true);
                R3.setVisible(true);

                break;
            case 3:
                ocultar();
                Label1.setVisible(true);
                Label1.setText("Clave Aeropuerto");
                Label2.setVisible(true);
                Label2.setText("Nombre Aeropuerto");
                Label3.setVisible(true);
                Label3.setText("Ciudad Aeropuerto");
                Label4.setVisible(true);
                Label4.setText("Pais");
                Label5.setVisible(true);
                Label5.setText("Numero Aero");
                Label6.setVisible(true);
                Label6.setText("Colonia");
                Label7.setVisible(true);
                Label7.setText("Codigo Posta");
                Label8.setVisible(true);
                Label8.setText("Clave Avion");
                
                Dato1.setVisible(true);
                Dato2.setVisible(true);
                Dato3.setVisible(true);
                Dato4.setVisible(true);
                Dato5.setVisible(true);
                Dato6.setVisible(true);
                Dato7.setVisible(true);
                Dato8.setVisible(true);
                
                B4.setVisible(true);
                M4.setVisible(true);
                R4.setVisible(true);

                
                break;
            case 4:
                                ocultar();
                Label1.setVisible(true);
                Label1.setText("Clave Reservacion");
                Label2.setVisible(true);
                Label2.setText("Horario Vuelo");
                Label3.setVisible(true);
                Label3.setText("Fecha Vuelo");
                Label4.setVisible(true);
                Label4.setText("Costo");
                Label5.setVisible(true);
                Label5.setText("Clave Vuelos");

                
                Dato1.setVisible(true);
                Dato2.setVisible(true);
                Dato3.setVisible(true);
                Dato4.setVisible(true);
                Dato5.setVisible(true);

                
                B5.setVisible(true);
                M5.setVisible(true);
                R5.setVisible(true);

                break;
                
            case 5:
                ocultar();
                Label1.setVisible(true);
                Label1.setText("Email Cliente");
                Label2.setVisible(true);
                Label2.setText("Contraseña");
                Label3.setVisible(true);
                Label3.setText("Nombre");
                Label4.setVisible(true);
                Label4.setText("Ap. Paterno");
                Label5.setVisible(true);
                Label5.setText("Ap. Materno");
                Label6.setVisible(true);
                Label6.setText("Calle");
                Label7.setVisible(true);
                Label7.setText("# Cliente");
                Label8.setVisible(true);
                Label8.setText("Colonia");
                Label9.setVisible(true);
                Label9.setText("Codigo Postal");
                Label10.setVisible(true);
                Label10.setText("Ciudad");
                Label11.setVisible(true);
                Label11.setText("Clave");
                
                Dato1.setVisible(true);
                Dato2.setVisible(true);
                Dato3.setVisible(true);
                Dato4.setVisible(true);
                Dato5.setVisible(true);
                Dato6.setVisible(true);
                Dato7.setVisible(true);
                Dato8.setVisible(true);
                Dato9.setVisible(true);
                Dato10.setVisible(true);
                Dato11.setVisible(true);
                
                B6.setVisible(true);
                M6.setVisible(true);
                R6.setVisible(true);

                break;
            default:
                ocultar();
                break;
        }
                       
    }//GEN-LAST:event_SeleccionActionPerformed

    private void M1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M1ActionPerformed
        // TODO add your handling code here:
       d1 = Dato1.getText();
       d2 = Dato2.getText();
   
       objCxn.modificarAerolinea(d1, d2);
       d1 = "";
       d2 = "";
       objCxn.mostrarDatosAerolinea(jTable1);
       ocultar();
    }//GEN-LAST:event_M1ActionPerformed

    private void M2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M2ActionPerformed
        // TODO add your handling code here:
d1 = Dato1.getText();
d2 = Dato2.getText();
d3 = Dato3.getText();
d4 = Dato4.getText();
d5 = Dato5.getText();
        try {
            objCxn.modificarAvion(d1, d2, d3, d4, d5);
        } catch (SQLException ex) {
            Logger.getLogger(CONSULTAS.class.getName()).log(Level.SEVERE, null, ex);
        }
d1="";
d2="";
d3="";
d4="";
d5="";
objCxn.mostrarDatosAvion(jTable1);
        ocultar();
      
    }//GEN-LAST:event_M2ActionPerformed

    private void M3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M3ActionPerformed
        // TODO add your handling code here:
d1 = Dato1.getText();
d2 = Dato2.getText();
d3 = Dato3.getText();
d4 = Dato4.getText();
d5 = Dato5.getText();    
d6 = Dato6.getText();
d7 = Dato7.getText();
d8 = Dato8.getText();    
        try {
            objCxn.ModificarVuelo(d1, d2, d3, d4, d5,d6,d7,d8);
        } catch (SQLException ex) {
            Logger.getLogger(CONSULTAS.class.getName()).log(Level.SEVERE, null, ex);
        }
d1="";
d2="";
d3="";
d4="";
d5="";
d6="";
d7="";
d8="";
objCxn.mostrarDatosVuelo(jTable1);
        ocultar();
    }//GEN-LAST:event_M3ActionPerformed

    private void M4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M4ActionPerformed
        // TODO add your handling code here:
        d1 = Dato1.getText();
d2 = Dato2.getText();
d3 = Dato3.getText();
d4 = Dato4.getText();
d5 = Dato5.getText();    
d6 = Dato6.getText();
d7 = Dato7.getText();
d8 = Dato8.getText();    
        try {        
            objCxn.modificarAeropuerto(d1, d2, d3, d4, d5,d6,d7,d8);
        } catch (SQLException ex) {
            Logger.getLogger(CONSULTAS.class.getName()).log(Level.SEVERE, null, ex);
        }
d1="";
d2="";
d3="";
d4="";
d5="";
d6="";
d7="";
d8="";
objCxn.mostrarDatosAeropuerto(jTable1);
        ocultar();
    }//GEN-LAST:event_M4ActionPerformed

    private void M5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M5ActionPerformed
        // TODO add your handling code here:
d1 = Dato1.getText();
d2 = Dato2.getText();
d3 = Dato3.getText();
d4 = Dato4.getText();
d5 = Dato5.getText();    
        try {      
            objCxn.modificarReservacion(d1, d2, d3, d4, d5);
        } catch (SQLException ex) {
            Logger.getLogger(CONSULTAS.class.getName()).log(Level.SEVERE, null, ex);
        }
d1="";
d2="";
d3="";
d4="";
d5="";
objCxn.mostrarDatosReservaciones(jTable1);
        ocultar();
    }//GEN-LAST:event_M5ActionPerformed

    private void M6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M6ActionPerformed
        // TODO add your handling code here:
                d1 = Dato1.getText();
d2 = Dato2.getText();
d3 = Dato3.getText();
d4 = Dato4.getText();
d5 = Dato5.getText();    
d6 = Dato6.getText();
d7 = Dato7.getText();
d8 = Dato8.getText();    
d9 = Dato9.getText();
d10 = Dato10.getText();
d11 = Dato11.getText();
        try {        
            objCxn.modificarCliente(d1, d2, d3, d4, d5,d6,d7,d8,d9,d10,d11);
        } catch (SQLException ex) {
            Logger.getLogger(CONSULTAS.class.getName()).log(Level.SEVERE, null, ex);
        }
d1="";
d2="";
d3="";
d4="";
d5="";
d6="";
d7="";
d8="";
d9="";
d10="";
d11="";
objCxn.mostrarDatosCliente(jTable1);
        ocultar();
    }//GEN-LAST:event_M6ActionPerformed

    private void R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1ActionPerformed
        // TODO add your handling code here:
        r = new Random();
        String [] aerolineas = {"Aeromexico","An All Japan","Qatar AL","Aerofree","Less Earth"};
        
        Dato1.setText(r.nextInt(98)+1+"");
        Dato2.setText(aerolineas[r.nextInt(aerolineas.length)]+"");
    }//GEN-LAST:event_R1ActionPerformed

    private void R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2ActionPerformed
        // TODO add your handling code here:
        r = new Random();
        String tipo[] = {"Jet Fx","Boeing 747","Helico","Jet","Presi","Turbo","Aplha","Omega"};
        String agencia[] = {"Qatar Airway","Trivago","Vivaerobus","Oriental Fly","MartyMcFly","Alex"};
        Dato1.setText("AV"+r.nextInt(99)+1);
        Dato2.setText(tipo[r.nextInt(tipo.length)]);
        Dato3.setText(r.nextInt(250)+1+"");
        Dato4.setText(agencia[r.nextInt(agencia.length)]);
        Dato5.setText(r.nextInt(99)+1+"");
    }//GEN-LAST:event_R2ActionPerformed

    private void R3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3ActionPerformed
        // TODO add your handling code here:
        r = new Random();
        String destinos[] = {"CO","MX","AL","RU","CN","CH","AR"};
        String estado[] = {"En transcurso","En espera","Cancelado"};
        String tipoV[] = {"Comercial","Privado","Especial"};
        String dias[] = {"Lunes","Martes","Mier","Juev","Vie","Sab","Dom"};
        Dato1.setText("V-"+destinos[r.nextInt(destinos.length)]+"-"+destinos[r.nextInt(destinos.length)]+"-"+(r.nextInt(99)+1));
        Dato2.setText(estado[r.nextInt(estado.length)]);
        Dato3.setText(tipoV[r.nextInt(tipoV.length)]);
        Dato4.setText(r.nextInt(24)+":"+r.nextInt(59));
        Dato5.setText(dias[r.nextInt(dias.length)]);
        Dato6.setText(r.nextInt(24)+":"+r.nextInt(59));
        Dato7.setText(dias[r.nextInt(dias.length)]);
        Dato8.setText("AV"+r.nextInt(99));
    }//GEN-LAST:event_R3ActionPerformed

    private void R4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R4ActionPerformed
        // TODO add your handling code here:
        r = new Random();
       String [] nAero = {"Airlines","Dustearth","KittyAir","Xhin Airs","MexSky"};
       String[] ciudades = {"CDMX","BERLIN","PEKIN","OKLAHOMA","BIEJING","B Aires","Santiago"};
       String []pais = {"CHINA","MEXICO","ALEMANIA","RUSIA","ARGEN","CHILE","USS"};
       String [] cols={"Bogota","Roswell","Wuhan","St. Panch","Mira Noa","San Pedro","Deusx"};
       Dato1.setText("AP-"+r.nextInt(99));
       Dato2.setText(nAero[r.nextInt(nAero.length)]);
       Dato3.setText(ciudades[r.nextInt(ciudades.length)]);
       Dato4.setText(pais[r.nextInt(pais.length)]);
       Dato5.setText(r.nextInt(99)+1+"");
       Dato6.setText(cols[r.nextInt(cols.length)]);
       Dato7.setText(r.nextInt(99)+"0"+r.nextInt(99));
       Dato8.setText("AV-"+r.nextInt(99));
       
    }//GEN-LAST:event_R4ActionPerformed

    private void R5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R5ActionPerformed
        // TODO add your handling code here:
        r = new Random();
        String destinos[] = {"CO","MX","AL","RU","CN","CH","AR"};
        
        Dato1.setText("RSV-"+r.nextInt(999));
        Dato2.setText(r.nextInt(24)+":"+r.nextInt(60));
        Dato3.setText((r.nextInt(3)+2018)+"/"+(r.nextInt(12)+1)+"/"+r.nextInt(31));
        Dato4.setText(r.nextInt(5000)+1000+"");
        Dato5.setText("V-"+destinos[r.nextInt(destinos.length)]+"-"+destinos[r.nextInt(destinos.length)]+"-"+r.nextInt(99));
        
    }//GEN-LAST:event_R5ActionPerformed

    private void R6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R6ActionPerformed
        // TODO add your handling code here:
        r = new Random();
        String iniCo[] = {"PrincesaMexicana","PedroSuarez28","AlexElCapo","EmoOxIiThoBeiiO","DrPerez","AlexA","EstefaniaF","MaryJoBie"};
        String finCo[] = {"@Gmail.com","@Outlook.com","@Hotmail.com","@Live.com"};
        String abcd = "ABCDEFGHIJKLMNOPQRSTVWXYZ-abcdefghijklmnopqrstuvwxyz-1234567890";
        char pass [] = abcd.toCharArray();
        String nombres[] = {"Juan","Juana","Carlos","Maria","Jose","Estefania","Pedro","Alejando","Artyom","Karla"};
        String apellidos[]= {"Alanis","Vazquez","Perez","Echeverria","Morales","Ugalde","Flores","Fernandez","Hernandez"};
        String calles[] = {"La ruleta","Flores","Quinta","Octava","Decima","Charales","San Juan","Tulipanes","Amatista","La fortuna"};

       String[] colonias = {"La Compresora","Centro","Barrio Viejo","La feria","Chapala"," Durangueña","Viñedos"};
       String[] ciudades = {"Gomez","Torreon","Lerdo","Matamoros","Chalvo"," CDMX","Monterrey"};
       Dato1.setText(iniCo[r.nextInt(iniCo.length)]+finCo[r.nextInt(finCo.length)]+"");
       Dato2.setText(pass[r.nextInt(pass.length)]+pass[r.nextInt(pass.length)]+pass[r.nextInt(pass.length)]+pass[r.nextInt(pass.length)]+pass[r.nextInt(pass.length)]+pass[r.nextInt(pass.length)]+pass[r.nextInt(pass.length)]+"");
       Dato3.setText(nombres[r.nextInt(nombres.length)]);
       Dato4.setText(apellidos[r.nextInt(apellidos.length)]);
       Dato5.setText(apellidos[r.nextInt(apellidos.length)]);
       Dato6.setText(calles[r.nextInt(calles.length)]);
       Dato7.setText((r.nextInt(9999)+1000)+"");
       Dato8.setText(colonias[r.nextInt(colonias.length)]);
       Dato9.setText(r.nextInt(99)+"0"+r.nextInt(99));
       Dato10.setText(ciudades[r.nextInt(ciudades.length)]);
       Dato11.setText("RSV-"+r.nextInt(899)+100);

    }//GEN-LAST:event_R6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CONSULTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CONSULTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CONSULTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CONSULTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CONSULTAS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JTextField Dato1;
    private javax.swing.JTextField Dato10;
    private javax.swing.JTextField Dato11;
    private javax.swing.JTextField Dato2;
    private javax.swing.JTextField Dato3;
    private javax.swing.JTextField Dato4;
    private javax.swing.JTextField Dato5;
    private javax.swing.JTextField Dato6;
    private javax.swing.JTextField Dato7;
    private javax.swing.JTextField Dato8;
    private javax.swing.JTextField Dato9;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label10;
    private javax.swing.JLabel Label11;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Label7;
    private javax.swing.JLabel Label8;
    private javax.swing.JLabel Label9;
    private javax.swing.JButton M1;
    private javax.swing.JButton M2;
    private javax.swing.JButton M3;
    private javax.swing.JButton M4;
    private javax.swing.JButton M5;
    private javax.swing.JButton M6;
    private javax.swing.JButton R1;
    private javax.swing.JButton R2;
    private javax.swing.JButton R3;
    private javax.swing.JButton R4;
    private javax.swing.JButton R5;
    private javax.swing.JButton R6;
    private javax.swing.JButton Seleccion;
    private javax.swing.JSeparator Separador;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboAdd;
    private javax.swing.JComboBox<String> jComboSeleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    // End of variables declaration//GEN-END:variables
}
