/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_2019_03_27_aplicacionnominaempleados;

import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alope
 */
public class JFrameReporte extends javax.swing.JFrame {

    /**
     * Creates new form JFrameReporte
     */
    
    JFrameMenu jfMenu;
    Empleado [] copia;
    DefaultTableModel modelo;

    public JFrameReporte(JFrameMenu jfm) {
        initComponents();
        
        jfMenu = jfm;

        jLabEmpReg.setText(jfMenu.getEmpleadosRegistrados()+"");
        
        copia = new Empleado[jfMenu.getEmpleadosRegistrados()];
  
        modelo = (DefaultTableModel)jTableEmpleados.getModel();
        modelo.setRowCount(copia.length);
        
        for(int i=0; i<copia.length; i++)
            copia[i] = jfMenu.getEmpleado(i);
        
        mostrar();
    }

    public void mostrar()
    {
        double total = 0;

        for (int r=0; r<copia.length; r++)
        {
            for (int c=0; c<modelo.getColumnCount(); c++)
                modelo.setValueAt(null, r, c);
            
            modelo.setValueAt(copia[r].getNumero(), r, 0);
            modelo.setValueAt(copia[r].getNombre(), r, 1);
            modelo.setValueAt(copia[r].sueldo(), r, 9);
            
            if (copia[r] instanceof Taller)
            {
                Taller tal = (Taller)copia[r];
                
                modelo.setValueAt(tal.getPiezas(), r, 2);
                modelo.setValueAt(tal.getPrecioUnitario(), r, 3);
            }
            
            if (copia[r] instanceof Ventas)
            {
                Ventas ven = (Ventas)copia[r];
                
                modelo.setValueAt(ven.getVentasTotales(), r, 4);
                modelo.setValueAt(ven.getComision(), r, 5);
            }

            if (copia[r] instanceof Administrativo)
            {
                Administrativo adm = (Administrativo)copia[r];
                
                modelo.setValueAt(adm.getDiasTrabajados(), r, 6);
                modelo.setValueAt(adm.getSueldoDiario(), r, 7);
            }
            
            if (copia[r] instanceof Ejecutivo)
            {
                Ejecutivo eje = (Ejecutivo)copia[r];
                
                modelo.setValueAt(eje.getDiasTrabajados(), r, 6);
                modelo.setValueAt(eje.getSueldoDiario(), r, 7);
                modelo.setValueAt(eje.getBono(), r, 8);
            }
            
            total += copia[r].sueldo();
        }
        
        jLabTotal.setText(total+"");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabEmpReg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jButSueldo = new javax.swing.JButton();
        jButAlfabetico = new javax.swing.JButton();
        jButOriginal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabTotal = new javax.swing.JLabel();
        jButExcel = new javax.swing.JButton();
        jButReportePDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jButRegresar.setText("Regresar");
        jButRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegresarActionPerformed(evt);
            }
        });

        jLabel2.setText("Empleados registrados");

        jLabEmpReg.setBackground(new java.awt.Color(255, 255, 0));
        jLabEmpReg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabEmpReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabEmpReg.setOpaque(true);

        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num", "Nombre", "Piezas", "Precio Unit$", "Ventas $", "%Comisión", "Días Trab", "Sueldo dia$", "Bono $", "Sueldo neto"
            }
        ));
        jScrollPane1.setViewportView(jTableEmpleados);
        if (jTableEmpleados.getColumnModel().getColumnCount() > 0) {
            jTableEmpleados.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableEmpleados.getColumnModel().getColumn(1).setPreferredWidth(175);
        }

        jButSueldo.setText("Por sueldo");
        jButSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSueldoActionPerformed(evt);
            }
        });

        jButAlfabetico.setText("Alfabético");
        jButAlfabetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAlfabeticoActionPerformed(evt);
            }
        });

        jButOriginal.setText("Orden original");
        jButOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButOriginalActionPerformed(evt);
            }
        });

        jLabel1.setText("Total");

        jLabTotal.setBackground(new java.awt.Color(255, 255, 0));
        jLabTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabTotal.setOpaque(true);

        jButExcel.setText("Exportar Excel");
        jButExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButExcelActionPerformed(evt);
            }
        });

        jButReportePDF.setText("Reporte PDF");
        jButReportePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButReportePDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButSueldo)
                                .addGap(33, 33, 33)
                                .addComponent(jButAlfabetico)
                                .addGap(40, 40, 40)
                                .addComponent(jButOriginal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(jLabEmpReg, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButRegresar)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButReportePDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(jLabTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabEmpReg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButSueldo)
                                    .addComponent(jButAlfabetico)
                                    .addComponent(jButOriginal)
                                    .addComponent(jButExcel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButReportePDF))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegresarActionPerformed
        // TODO add your handling code here:
        dispose();

        jfMenu.getEtiqueta().setBackground(Color.PINK);

        jfMenu.setVisible(true);
    }//GEN-LAST:event_jButRegresarActionPerformed

    private void jButSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSueldoActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<copia.length-1; i++)
            for (int j=i+1; j<copia.length; j++)
                if (copia[i].sueldo() < copia[j].sueldo())
                {
                    Empleado aux = copia[i];
                    copia[i]= copia[j];
                    copia[j] = aux;
                }

        mostrar();
    }//GEN-LAST:event_jButSueldoActionPerformed

    private void jButAlfabeticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAlfabeticoActionPerformed
        // TODO add your handling code here:
        ordenarAlfabetico();
        mostrar();
    }//GEN-LAST:event_jButAlfabeticoActionPerformed

    public void ordenarAlfabetico()
    {
        for(int i=0; i<copia.length-1; i++)
            for (int j=i+1; j<copia.length; j++)
                if (copia[i].getNombre().compareTo(copia[j].getNombre())>0)
                {
                    Empleado aux = copia[i];
                    copia[i]= copia[j];
                    copia[j] = aux;
                }
    }
    private void jButOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButOriginalActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<copia.length; i++)
            copia[i] = jfMenu.getEmpleado(i);
        
        mostrar();
    }//GEN-LAST:event_jButOriginalActionPerformed

    private void jButExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButExcelActionPerformed
        // TODO add your handling code here:
        JFileChooser jfch = new JFileChooser();
        
        if(jfch.showSaveDialog(jfMenu) !=0)
            return;
        
        FileWriter fw = null;
        PrintWriter pw = null;
        
        try {
            fw = new FileWriter(jfch.getSelectedFile());
            pw = new PrintWriter(fw);
            
            pw.println("Número,Empleado,Piezas,Precio Unit,Ventas,Comisión,Días Trab,Sueldo diario,Bono");
            
            Empleado emp;
            String clase;
            
            for(int i=0; i<jfMenu.getEmpleadosRegistrados(); i++)
            {
                emp = jfMenu.getEmpleado(i);
                clase = emp.getClass().getSimpleName();
                
                if(clase.equals("Empleado"))
                    pw.println(emp.getNumero()+","+emp.getNombre());
                
                if(clase.equals("Taller"))
                {
                    Taller t = (Taller)emp;
                    
                    pw.println(emp.getNumero()+","+emp.getNombre()+","+t.getPiezas()+","+t.getPrecioUnitario());
                }

                if(clase.equals("Ventas"))
                {
                    Ventas v = (Ventas)emp;
                    
                    pw.println(emp.getNumero()+","+emp.getNombre()+",,,"+v.getVentasTotales()+","+v.getComision());
                }

                if(clase.equals("Administrativo"))
                {
                    Administrativo a = (Administrativo)emp;
                    
                    pw.println(emp.getNumero()+","+emp.getNombre()+",,,,,"+a.getDiasTrabajados()+","+a.getSueldoDiario());
                }
                
                if(clase.equals("Ejecutivo"))
                {
                    Ejecutivo e = (Ejecutivo)emp;
                    
                    pw.println(emp.getNumero()+","+emp.getNombre()+",,,,,"+e.getDiasTrabajados()+","+e.getSueldoDiario()+","+e.getBono());
                }
                
            }
            
        } catch (IOException ex) {
            Logger.getLogger(JFrameRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            if(pw != null)
                pw.close();
            
            if(fw != null)
                try {
                    fw.close();
            } catch (IOException ex) {
                Logger.getLogger(JFrameRegistro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButExcelActionPerformed

    private void jButReportePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButReportePDFActionPerformed
        // TODO add your handling code here:
        JFileChooser jfch = new JFileChooser();
        
        if(jfch.showSaveDialog(jfMenu) !=0)
            return;
        
        FileOutputStream fos = null;
        Document doc = null;
        
        try {
            fos = new FileOutputStream(jfch.getSelectedFile());
            doc = new Document();
            
            PdfWriter.getInstance(doc, fos);

            doc.open();
            
            doc.add(new Paragraph("Lista de Nómina",FontFactory.getFont("arial",   // fuente
                                                    22,                            // tamaño
                                                    Font.ITALIC,                   // estilo
                                                    BaseColor.GREEN)));            // color

            doc.add(new Paragraph(" "));
            
            ordenarAlfabetico();
            
            String espacios = "                                        ";
            DecimalFormat df = new DecimalFormat("$###,##0.00");
            
            String nombre,sueldo;
            Empleado emp;
            
            Font fuenteAzul = FontFactory.getFont("courier",16,Font.NORMAL,BaseColor.BLUE);
            Font fuenteRojo = FontFactory.getFont("courier",16,Font.NORMAL,BaseColor.RED);
            
            for(int i=0; i<copia.length; i++)
            {
                emp = copia[i];
                nombre = (emp.getNombre()+espacios).substring(0, 35);
                sueldo = espacios+df.format(emp.sueldo());
                sueldo = sueldo.substring(sueldo.length()-15);
                
                doc.add(new Paragraph(nombre+sueldo,emp.sueldo()>0?fuenteAzul:fuenteRojo));
            }

            doc.add(new Paragraph(" "));

            Image foto = Image.getInstance("diver28.jpg");
            foto.scaleToFit(100, 100);
            foto.setAlignment(1); // centro
            doc.add(foto);
            
            doc.add(new Paragraph(" "));

            PdfPTable tabla = new PdfPTable(modelo.getColumnCount());
            
            int [] anchoColumna = new int[modelo.getColumnCount()];
            
            int ancho;
            for(int i=0; i<anchoColumna.length; i++)
            {
                switch(i)
                {
                    case 0: ancho = 40; break; // número de empleado
                    case 1: ancho = 170; break; // nombre
                    case 2: ancho = 60; break; // piezas
                    case 6: ancho = 60; break; // dias trabajados
                    default: ancho = 80;
                }
                
                anchoColumna[i] = ancho;
            }
            
            tabla.setWidths(anchoColumna);
            
            Font fuenteTabla = FontFactory.getFont("courier",8,Font.NORMAL,BaseColor.BLACK);
            Font fuenteEnc = FontFactory.getFont("arial",6,Font.NORMAL,BaseColor.RED);
            
            for(int c=0; c<jTableEmpleados.getColumnCount(); c++)
                tabla.addCell(new Paragraph(jTableEmpleados.getColumnModel().getColumn(c).getHeaderValue()+"",fuenteEnc));
            
            for(int r=0; r<modelo.getRowCount(); r++)
                for (int c=0; c<modelo.getColumnCount(); c++)
                    tabla.addCell(new Paragraph(modelo.getValueAt(r, c)==null?"":modelo.getValueAt(r, c)+"",fuenteTabla));
            
            doc.add(tabla);
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JFrameReporte.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException | IOException ex) {
            Logger.getLogger(JFrameReporte.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            if (doc != null)
                doc.close();
            
            if (fos != null)
                try {
                    fos.close();
            } catch (IOException ex) {
                Logger.getLogger(JFrameReporte.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                
    }//GEN-LAST:event_jButReportePDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameReporte(new JFrameMenu()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAlfabetico;
    private javax.swing.JButton jButExcel;
    private javax.swing.JButton jButOriginal;
    private javax.swing.JButton jButRegresar;
    private javax.swing.JButton jButReportePDF;
    private javax.swing.JButton jButSueldo;
    private javax.swing.JLabel jLabEmpReg;
    private javax.swing.JLabel jLabTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpleados;
    // End of variables declaration//GEN-END:variables
}
