/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_17130797_proyecto_01;

import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis Mario
 */
public class PB_17130797_Frame_01 extends javax.swing.JFrame {

    /**
     * Creates new form PB_17130797_Frame_01
     */
    //Atributo Frame
    Rectangulo [] lista = new Rectangulo[3];
    
    public PB_17130797_Frame_01() {
        initComponents();
        
        DefaultTableModel modelo = (DefaultTableModel)jTableRectangulo.getModel();
        modelo.setRowCount(lista.length);
        jTableRectangulo.setShowGrid(true);
        
        for (int i=0; i<lista.length; i++)
            lista[i] = new Rectangulo();
        
        Mostrar();
        
    }
    public void Mostrar()
    {
        double Total=0;
        double TotalAltura=0;
        double PromedioAltura=0;
        
        for (int R=0; R<lista.length; R++)
        {
            jTableRectangulo.setValueAt(lista[R].getNombre(), R, 0);
            jTableRectangulo.setValueAt(lista[R].getBase(), R, 1);
            jTableRectangulo.setValueAt(lista[R].Altura(), R, 2);
            jTableRectangulo.setValueAt(lista[R].AreaTotal(), R, 3);
            jTableRectangulo.setValueAt(lista[R].getPerimetro(), R, 4);               
               
            
            Total+=lista[R].AreaTotal();
            TotalAltura+=lista[R].Altura();
            PromedioAltura= TotalAltura/lista.length;
        }
        jLabTotal.setText(Total+"");
        jLabPromAltura.setText(PromedioAltura+"");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRectangulo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButGrabar = new javax.swing.JButton();
        jButAleatorios = new javax.swing.JButton();
        jButEjemplo1 = new javax.swing.JButton();
        jButEjemplo2 = new javax.swing.JButton();
        jButEjemplo3 = new javax.swing.JButton();
        jTextNombre = new javax.swing.JTextField();
        jTextBase = new javax.swing.JTextField();
        jTextPerimetro = new javax.swing.JTextField();
        jSpinNumRectangulos = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jButAlfa = new javax.swing.JButton();
        jButArea = new javax.swing.JButton();
        jLabMayor = new javax.swing.JLabel();
        jLabMenor = new javax.swing.JLabel();
        jLabTotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButMayorMenor = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabPromAltura = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableRectangulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Rectangulo", "Base", "Altura", "Area", "Perimetro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableRectangulo);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre: ");
        jLabel1.setToolTipText("");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Base:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Perimetro:");

        jButGrabar.setText("Grabar");
        jButGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButGrabarActionPerformed(evt);
            }
        });

        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jButEjemplo1.setText("Ejemplo 1");
        jButEjemplo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemplo1ActionPerformed(evt);
            }
        });

        jButEjemplo2.setText("Ejemplo 2");
        jButEjemplo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemplo2ActionPerformed(evt);
            }
        });

        jButEjemplo3.setText("Ejemplo 3");
        jButEjemplo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemplo3ActionPerformed(evt);
            }
        });

        jTextNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });

        jTextBase.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextPerimetro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jSpinNumRectangulos.setModel(new javax.swing.SpinnerNumberModel(1, 1, 3, 1));
        jSpinNumRectangulos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinNumRectangulosStateChanged(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 153, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Numero de Rectangulos");
        jLabel2.setOpaque(true);

        jButAlfa.setText("Alfabeticamente");
        jButAlfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAlfaActionPerformed(evt);
            }
        });

        jButArea.setText("Por Area");
        jButArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAreaActionPerformed(evt);
            }
        });

        jLabMayor.setBackground(new java.awt.Color(0, 204, 204));
        jLabMayor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabMayor.setOpaque(true);

        jLabMenor.setBackground(new java.awt.Color(102, 255, 102));
        jLabMenor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabMenor.setOpaque(true);

        jLabTotal.setBackground(new java.awt.Color(255, 153, 102));
        jLabTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabTotal.setOpaque(true);

        jLabel6.setText("Total Area:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Mayor:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Menor:");

        jButMayorMenor.setText("Mayor y Menor");
        jButMayorMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButMayorMenorActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pb_17130797_proyecto_01/Imagen Proyecto.png"))); // NOI18N

        jLabel9.setText("Promedio Altura:");

        jLabPromAltura.setBackground(new java.awt.Color(0, 255, 0));
        jLabPromAltura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabPromAltura.setOpaque(true);

        jCheckBox1.setText("Incrementar");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextNombre)
                                    .addComponent(jTextBase)
                                    .addComponent(jTextPerimetro, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButAleatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButGrabar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButEjemplo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButEjemplo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButEjemplo3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jSpinNumRectangulos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButArea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButAlfa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButMayorMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jLabPromAltura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinNumRectangulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButGrabar)
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButAleatorios))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButEjemplo1)
                            .addComponent(jButEjemplo2)
                            .addComponent(jButEjemplo3)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButAlfa)
                                        .addComponent(jButMayorMenor))
                                    .addGap(15, 15, 15))
                                .addComponent(jLabMayor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(12, 12, 12)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButArea)
                                .addComponent(jLabel8))
                            .addGap(15, 15, 15))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabPromAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabMenor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButGrabarActionPerformed
       
        int Posicion = (int)jSpinNumRectangulos.getValue() - 1;
        
        Rectangulo Rec = new Rectangulo(jTextNombre.getText(),
                                        Double.parseDouble(jTextBase.getText()),
                                        Double.parseDouble(jTextPerimetro.getText()));
        lista[Posicion] = Rec;
        Mostrar();
        
        if (jCheckBox1.isSelected())
            if((int)jSpinNumRectangulos.getValue()<3)
            jSpinNumRectangulos.setValue(Posicion+2);
    }//GEN-LAST:event_jButGrabarActionPerformed

    private void jButEjemplo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemplo1ActionPerformed
        
    jTextNombre.setText("Hoja");
    jTextBase.setText("21");
    jTextPerimetro.setText("98");
    }//GEN-LAST:event_jButEjemplo1ActionPerformed

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jButEjemplo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemplo2ActionPerformed
       
        jTextNombre.setText("Pizarron");
        jTextBase.setText("150");
        jTextPerimetro.setText("490");
        
    }//GEN-LAST:event_jButEjemplo2ActionPerformed

    private void jButEjemplo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemplo3ActionPerformed
       
       jTextNombre.setText("Borrador");
       jTextBase.setText("17");
       jTextPerimetro.setText("48"); 
        
    }//GEN-LAST:event_jButEjemplo3ActionPerformed

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        
        Random azar = new Random();
        
        String [] Nombre ={"Teclado","Hoja","Pizarron","Pantalla","Puerta","Borrador"
                            ,"Cama","Libreta","Carpeta"};
        
        jTextNombre.setText(Nombre[azar.nextInt(Nombre.length)]);
        jTextBase.setText(5+azar.nextInt(15)+"");
        jTextPerimetro.setText(10+azar.nextInt(51)+"");
        
        
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jSpinNumRectangulosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinNumRectangulosStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinNumRectangulosStateChanged

    private void jButAlfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAlfaActionPerformed
       
         for (int i=0; i<lista.length-1; i++)
            for (int j=i+1; j<lista.length; j++)
                if (lista[i].getNombre().compareTo(lista[j].getNombre())>0)
                {
                    Rectangulo aux = lista[i];
                    lista[i] = lista[j];
                    lista[j] = aux;
                }
        
        Mostrar();
        
    }//GEN-LAST:event_jButAlfaActionPerformed

    private void jButMayorMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButMayorMenorActionPerformed
       
         Rectangulo Mayor = lista[0];

        for (int i=1; i<lista.length; i++)
            if (lista[i].AreaTotal()>Mayor.AreaTotal())
                Mayor = lista[i];
        
        Rectangulo Menor = lista[0];

        for (int i=1; i<lista.length; i++)
            if (lista[i].AreaTotal()<Menor.AreaTotal())
                Menor = lista[i];
        
        jLabMayor.setText(Mayor.getNombre());
        jLabMenor.setText(Menor.getNombre());
        
    }//GEN-LAST:event_jButMayorMenorActionPerformed

    private void jButAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAreaActionPerformed
        
         for (int i=0; i<lista.length-1; i++)
            for (int j=i+1; j<lista.length; j++)
                if (lista[i].AreaTotal()<lista[j].AreaTotal())
                {
                    Rectangulo aux = lista[i];
                    lista[i] = lista[j];
                    lista[j] = aux;
                }
        
        Mostrar();
        
    }//GEN-LAST:event_jButAreaActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PB_17130797_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PB_17130797_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PB_17130797_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PB_17130797_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PB_17130797_Frame_01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButAlfa;
    private javax.swing.JButton jButArea;
    private javax.swing.JButton jButEjemplo1;
    private javax.swing.JButton jButEjemplo2;
    private javax.swing.JButton jButEjemplo3;
    private javax.swing.JButton jButGrabar;
    private javax.swing.JButton jButMayorMenor;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabMayor;
    private javax.swing.JLabel jLabMenor;
    private javax.swing.JLabel jLabPromAltura;
    private javax.swing.JLabel jLabTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinNumRectangulos;
    private javax.swing.JTable jTableRectangulo;
    private javax.swing.JTextField jTextBase;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextPerimetro;
    // End of variables declaration//GEN-END:variables
}
