/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_18131237_proyecto_03;

import java.awt.Component;

/**
 *
 * @author lDestroyerl
 */
public class PB_18131237_Frame_03a extends javax.swing.JFrame {

    /**
     * Creates new form PB_18131237_Frame_03a
     */
    
    private PB_18131237_Frame_03 jfMenu;
    private GrupoMusical [] copiaDatos;
    private IMostrar [] movimientos;
    private IMostrar [] dibujos;
    private String [] lugar = new String[4];
    private int [] numAlbum = new int[4];
     
    private Zoe zoe = new Zoe ();
    private BandaMs banda = new BandaMs();
    private FooFighter foo = new FooFighter();
    private Nirvana nir = new Nirvana();
    
    public PB_18131237_Frame_03a(PB_18131237_Frame_03 jfm) {
        initComponents();
        
        jfMenu = jfm;
        
        copiaDatos = new GrupoMusical[jfMenu.getGruposRegistrados()];
        dibujos = new IMostrar[copiaDatos.length];
        
        for(int i=0; i<copiaDatos.length; i++)
        {
            copiaDatos[i] = jfMenu.getGrupoMusical(i);
            dibujos[i] = jfMenu.getDibujos(i);
        }    
        
        zoe.setEstado("Cuernavaca, MX");
        banda.setEstado("Sinaloa, MX");
        foo.setPais("Seattle, EEUU");
        nir.setPais("Aberdeen, EEUU");
        
        zoe.setNumAlbumes(5);
        banda.setNumAlbumes(4);
        foo.setNumAlbumes(9);
        nir.setNumAlbumes(3);
        
        lugar[0] = zoe.getEstado();
        lugar[1] = banda.getEstado();
        lugar[2] = foo.getPais();
        lugar[3] = nir.getPais();
        
        numAlbum[0] = zoe.getNumAlbumes();
        numAlbum[1] = banda.getNumAlbumes();
        numAlbum[2] = foo.getNumAlbumes();
        numAlbum[3] = nir.getNumAlbumes();
        
        for(int i=0; i<copiaDatos.length; i++)
        {    
            for(int j = i+1; j<copiaDatos.length; j++)
                if(copiaDatos[i].getGenero().compareTo(copiaDatos[j].getGenero()) > 0)
                {
                    GrupoMusical aux = copiaDatos[i];
                    copiaDatos[i] = copiaDatos[j];
                    copiaDatos[j] =  aux;
                    
                    String auxs = lugar[i];
                    lugar[i] = lugar[j];
                    lugar[j] = auxs;
                    
                    int auxi = numAlbum[i];
                    numAlbum[i] = numAlbum[j];
                    numAlbum[j] = auxi;
                    
                    IMostrar auxd = dibujos[i];
                    dibujos[i] =dibujos[j];
                    dibujos[j] = auxd;
                }
        }
        mostrar();
    }
    
    public void mostrar()
    {
        jLabNombre.setText(copiaDatos[0].getNombre());
        jLabGenero.setText(copiaDatos[0].getGenero());
        jLabNumIntegrantes.setText(copiaDatos[0].getNumIntegrantes()+"");
        jLabLugar.setText(lugar[0]);
        jLabNumAlbumes.setText(numAlbum[0]+"");
        
                
        Component compDibujos = jPanelDesfileDibujo;
        //dibujos[0].dibujar(compDibujos);
    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButRegresarDesfile = new javax.swing.JButton();
        jPanelDesfileDibujo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabNombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabGenero = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabNumIntegrantes = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabLugar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabNumAlbumes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Frame Desfile");
        setFocusCycleRoot(false);
        setPreferredSize(new java.awt.Dimension(980, 700));

        jButRegresarDesfile.setBackground(new java.awt.Color(102, 102, 255));
        jButRegresarDesfile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButRegresarDesfile.setText("REGRESAR");
        jButRegresarDesfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegresarDesfileActionPerformed(evt);
            }
        });

        jPanelDesfileDibujo.setBackground(new java.awt.Color(153, 153, 153));
        jPanelDesfileDibujo.setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("NOMBRE DEL GRUPO:");

        jLabNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("GÉNERO DEL GRUPO:");

        jLabGenero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("NUMERO DE INTEGRANTES:");

        jLabNumIntegrantes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("LUGAR DE ORIGEN:");

        jLabLugar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("NUMERO DE ALBUMES:");

        jLabNumAlbumes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanelDesfileDibujoLayout = new javax.swing.GroupLayout(jPanelDesfileDibujo);
        jPanelDesfileDibujo.setLayout(jPanelDesfileDibujoLayout);
        jPanelDesfileDibujoLayout.setHorizontalGroup(
            jPanelDesfileDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDesfileDibujoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDesfileDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDesfileDibujoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabNumIntegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDesfileDibujoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDesfileDibujoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabNumAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDesfileDibujoLayout.createSequentialGroup()
                        .addGroup(jPanelDesfileDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDesfileDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(597, Short.MAX_VALUE))
        );
        jPanelDesfileDibujoLayout.setVerticalGroup(
            jPanelDesfileDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDesfileDibujoLayout.createSequentialGroup()
                .addContainerGap(458, Short.MAX_VALUE)
                .addGroup(jPanelDesfileDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDesfileDibujoLayout.createSequentialGroup()
                        .addGroup(jPanelDesfileDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDesfileDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addComponent(jLabNumIntegrantes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDesfileDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDesfileDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabNumAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(831, Short.MAX_VALUE)
                .addComponent(jButRegresarDesfile)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelDesfileDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDesfileDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButRegresarDesfile)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButRegresarDesfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegresarDesfileActionPerformed
        dispose(); //Quita el objeto de la memoria (FrameDesfile)
        
        jfMenu.setVisible(true);
    }//GEN-LAST:event_jButRegresarDesfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PB_18131237_Frame_03a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PB_18131237_Frame_03a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PB_18131237_Frame_03a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PB_18131237_Frame_03a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PB_18131237_Frame_03a(new PB_18131237_Frame_03()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButRegresarDesfile;
    private javax.swing.JLabel jLabGenero;
    private javax.swing.JLabel jLabLugar;
    private javax.swing.JLabel jLabNombre;
    private javax.swing.JLabel jLabNumAlbumes;
    private javax.swing.JLabel jLabNumIntegrantes;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelDesfileDibujo;
    // End of variables declaration//GEN-END:variables
}
