/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_eli;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahdeijack
 */
public class PA_18131285_jFrame_A extends javax.swing.JFrame {

    /**
     * Creates new form PA_18131285_jFrame_A
     */
    DefaultTableModel modelo;
    private int registro;
    PA_18131285_Clase_A [] citys = new PA_18131285_Clase_A[4];
    PA_18131285_Clase_A [] dibujos = new PA_18131285_Clase_A[citys.length];
    
    public PA_18131285_jFrame_A() {
        initComponents();
        modelo = (DefaultTableModel) jTab1.getModel();
        jTab1.setShowGrid(true);
        
        //Alemania
        modelo.setValueAt(3796, 0, 0);
        modelo.setValueAt("Euro", 0, 1);
        modelo.setValueAt("Austria", 0, 2);
        modelo.setValueAt("Alemania", 0, 3);
        
        //Italia
         modelo.setValueAt(2873, 1, 0);
        modelo.setValueAt("Euro", 1, 1);
        modelo.setValueAt("Pomezia", 1, 2);
        modelo.setValueAt("Italia", 1, 3);
        
        //Chile
         modelo.setValueAt(2706, 2, 0);
        modelo.setValueAt("Santiago", 2, 1);
        modelo.setValueAt("Argentina", 2, 2);
        modelo.setValueAt("Chile", 2, 3);
        
        //Italia
         modelo.setValueAt(8399, 3, 0);
        modelo.setValueAt("Washington", 3, 1);
        modelo.setValueAt("Conneticut", 3, 2);
        modelo.setValueAt("Estados Unidos", 3, 3);
    }
    
    public int getTamaño(){
        return(citys.length);
    }
    
public int getCiudadesRegistradas(){
    return registro;
}

public boolean agregarCiudad(PA_18131285_Clase_A ciudad){
    if (registro == citys.length) 
        return false;
    
    citys[registro] = ciudad;
    registro++;
    return true;
}

public  void  setCiudad(PA_18131285_Clase_A ciudad, int posicion){
    if (posicion>= 0 && posicion < citys.length) {
        citys[posicion] = ciudad;
    }
}

public PA_18131285_Clase_A getCiudad(int posicion){
    if (posicion >= 0 && posicion < citys.length) {
        return(citys[posicion]);
    } else {
        return null;
    }
}

public void guardar(){
    PA_18131285_Clase_D c1 = new PA_18131285_Clase_D(
    Integer.parseInt(modelo.getValueAt(0, 0)+""),
    (String)modelo.getValueAt(0, 1),
    (String)modelo.getValueAt(0, 2),
    (String)modelo.getValueAt(0, 3));
    
    PA_18131285_Clase_G c2 = new PA_18131285_Clase_G(
     Integer.parseInt(modelo.getValueAt(1, 0)+""),
    (String)modelo.getValueAt(1, 1),
    (String)modelo.getValueAt(1, 2),
    (String)modelo.getValueAt(1, 3));
    
    PA_18131285_Clase_F c3 = new PA_18131285_Clase_F(
     Integer.parseInt(modelo.getValueAt(2, 0)+""),
    (String)modelo.getValueAt(2, 1),
    (String)modelo.getValueAt(2, 2),
    (String)modelo.getValueAt(2, 3));
    
    PA_18131285_Clase_E c4 = new PA_18131285_Clase_E(
     Integer.parseInt(modelo.getValueAt(3, 0)+""),
    (String)modelo.getValueAt(3, 1),
    (String)modelo.getValueAt(3, 2),
    (String)modelo.getValueAt(3, 3));
    
    citys[0] = c1;
    citys[1] = c2;
    citys[2] = c3;
    citys[3] = c4;
    
    dibujos[0] = c1;
    dibujos[1] = c2;
    dibujos[2] = c3;
    dibujos[3] = c4;
    
    for (int i = 0; i < citys.length; i++) {
        for (int j = 0; j < citys.length; j++) {
            if (citys[i].getColindaCon().compareTo(citys[j].getColindaCon())>0) {
                
                PA_18131285_Clase_A aux = citys[i];
                citys[i] = citys[j];
                citys[j] = aux;
                
                
            }
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTab1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSRenglon = new javax.swing.JSpinner();
        jLabNombre6 = new javax.swing.JLabel();
        jTextHabitantes = new javax.swing.JTextField();
        jLabNombre7 = new javax.swing.JLabel();
        jTextCapital = new javax.swing.JTextField();
        jLabNombre8 = new javax.swing.JLabel();
        jTextColindante = new javax.swing.JTextField();
        jLabNombre9 = new javax.swing.JLabel();
        jTextCiudad = new javax.swing.JTextField();
        jLabNombre10 = new javax.swing.JLabel();
        hoja = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Habitantes (Millones)", "Moneda / Capital", "Colindante", "Pais"
            }
        ));
        jScrollPane1.setViewportView(jTab1);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_eli/Asignacion.jpg"))); // NOI18N
        jLabel1.setOpaque(true);

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Diagrama");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Mostrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Desfile");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jSRenglon.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jSRenglon.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        jLabNombre6.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabNombre6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabNombre6.setText("Renglon");

        jTextHabitantes.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N

        jLabNombre7.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabNombre7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabNombre7.setText("Habitantes");

        jTextCapital.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N

        jLabNombre8.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabNombre8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabNombre8.setText("Moneda / Capital");

        jTextColindante.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N

        jLabNombre9.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabNombre9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabNombre9.setText("Colindante");

        jTextCiudad.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N

        jLabNombre10.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabNombre10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabNombre10.setText("Ciudad");

        hoja.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout hojaLayout = new javax.swing.GroupLayout(hoja);
        hoja.setLayout(hojaLayout);
        hojaLayout.setHorizontalGroup(
            hojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hojaLayout.setVerticalGroup(
            hojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(hoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabNombre10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabNombre9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextColindante, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabNombre6, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                            .addComponent(jSRenglon, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                            .addComponent(jLabNombre7, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                            .addComponent(jTextHabitantes)
                                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabNombre8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextCapital, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(8, 8, 8)))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabNombre6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSRenglon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabNombre7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextHabitantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabNombre8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextCapital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabNombre9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextColindante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabNombre10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int renglon = (int)jSRenglon.getValue(); //Seleccionamos el renglon a modificar
        int habitantes = Integer.parseInt(jTextHabitantes.getText()+"");
        String capital = jTextCapital.getText();
        String ciudad = jTextCiudad.getText();
        String colindante = jTextColindante.getText();
        
        modelo.setValueAt(habitantes, renglon-1, 0);
        modelo.setValueAt(capital, renglon-1, 1);
        modelo.setValueAt(colindante, renglon-1, 2);
        modelo.setValueAt(ciudad, renglon-1, 3);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        guardar();
        
        for (int i = 0; i < 1; i++) {
            for (int j = 0; j < citys.length; j++) {
                
                 dibujos[j].mover(hoja, citys);
                
                try {
                Thread.sleep(20);
                } catch (InterruptedException ex) {
                Logger.getLogger(PA_18131285_jFrame_A.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        guardar();
        setVisible(false);
        
        PA_18131285_jFrame_B jDes = new PA_18131285_jFrame_B(this);
        jDes.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        guardar();
        PA_18131285_jFrame_C jDiag = new PA_18131285_jFrame_C(this);
        jDiag.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PA_18131285_jFrame_A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PA_18131285_jFrame_A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PA_18131285_jFrame_A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PA_18131285_jFrame_A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PA_18131285_jFrame_A().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel hoja;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabNombre10;
    private javax.swing.JLabel jLabNombre6;
    private javax.swing.JLabel jLabNombre7;
    private javax.swing.JLabel jLabNombre8;
    private javax.swing.JLabel jLabNombre9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner jSRenglon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTab1;
    private javax.swing.JTextField jTextCapital;
    private javax.swing.JTextField jTextCiudad;
    private javax.swing.JTextField jTextColindante;
    private javax.swing.JTextField jTextHabitantes;
    // End of variables declaration//GEN-END:variables
}
