/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_17131621_proyecto_02;

import Utilerias.JTable.ColorCeldas;
import java.awt.Color;
import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RicardoMtz
 */
public class PB_17131621_Frame_01 extends javax.swing.JFrame {
        
    /**
     * Creates new form PB_17131621_Frame_01
     */
    Perfume [] tienda = new Perfume[0];
    
    public PB_17131621_Frame_01() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKiosco = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButEjemplo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSpinKioscos = new javax.swing.JSpinner();
        jButAleatorio = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButArregloEncapsulado = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButCalcular = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTotales = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jButOrdenDescendente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Proyecto 2");

        jLabel5.setText("Descripcion:");

        jLabel6.setText("Soy RicardoMtz (17131621) Y Me Toco Hacer La Actividad 2. ");

        jLabel7.setText("Arreglo Encapsulado.");

        jTableKiosco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kiosco", "Galón", "Pinta", "Onza", "Galón", "Pinta", "Onza", "Galón", "Pinta", "Onza", "$ Ventas"
            }
        ));
        jScrollPane1.setViewportView(jTableKiosco);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pb_17131621_proyecto_02/MiProyecto.png"))); // NOI18N

        jButEjemplo.setText("Ejemplo");
        jButEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemploActionPerformed(evt);
            }
        });

        jLabel3.setText("Numero De Kioscos");

        jSpinKioscos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinKioscosStateChanged(evt);
            }
        });

        jButAleatorio.setText("Aleatorios");
        jButAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatorioActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 102, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Inventario Inicial");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setOpaque(true);

        jButArregloEncapsulado.setText("Arreglo Encapsulado");
        jButArregloEncapsulado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButArregloEncapsuladoActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 0, 51));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ventas");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel8.setOpaque(true);

        jLabel9.setBackground(new java.awt.Color(0, 102, 204));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Inventario Final");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel9.setOpaque(true);

        jTextField1.setBackground(new java.awt.Color(0, 255, 0));
        jTextField1.setText("   ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(255, 255, 0));
        jTextField2.setText("   ");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Mayor Venta");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Menor Venta");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Precio Por Onza $");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("125.56");

        jButCalcular.setText("Calcular");
        jButCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalcularActionPerformed(evt);
            }
        });

        jTableTotales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Total Inicial", "Total Final", "Total Ventas", "Total Dinero"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableTotales);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("TOTALES");

        jButOrdenDescendente.setText("Ordenar Descendente");
        jButOrdenDescendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButOrdenDescendenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel24))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinKioscos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButAleatorio)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButEjemplo)
                                        .addComponent(jButCalcular))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButOrdenDescendente)
                                            .addComponent(jButArregloEncapsulado))))))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jSpinKioscos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButAleatorio))
                                .addGap(18, 18, 18)
                                .addComponent(jButCalcular)))
                        .addGap(18, 18, 18)
                        .addComponent(jButEjemplo)
                        .addGap(18, 18, 18)
                        .addComponent(jButArregloEncapsulado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButOrdenDescendente)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel22)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jSpinKioscosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinKioscosStateChanged
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel)jTableKiosco.getModel();
        modelo.setRowCount((int)jSpinKioscos.getValue());
    }//GEN-LAST:event_jSpinKioscosStateChanged

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatorioActionPerformed
        // TODO add your handling code here:
        Random azar = new Random();
        
        String [] nom = {"Cimaco","Galerias","Liverpool","Soriana","HEB","Chedraui","Sams Club"};
        
        for (int r=0; r<jTableKiosco.getRowCount(); r++)
        {
            jTableKiosco.setValueAt(nom[azar.nextInt(nom.length)], r, 0);
            
            //Contenido Inicial
            jTableKiosco.setValueAt(10+azar.nextInt(5), r, 1); // Galones
            jTableKiosco.setValueAt(azar.nextInt(8), r, 2); // Pintas
            jTableKiosco.setValueAt(azar.nextInt(16), r, 3); // Onzas
            
            //Contenido Terminal
            jTableKiosco.setValueAt(5+azar.nextInt(5), r, 4); // Galones
            jTableKiosco.setValueAt(azar.nextInt(8), r, 5); // Pintas
            jTableKiosco.setValueAt(azar.nextInt(16), r, 6); // Onzas         
        }
    }//GEN-LAST:event_jButAleatorioActionPerformed

    private void jButCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalcularActionPerformed
        // TODO add your handling code here:
        Contenido inicial = new Contenido();
        Contenido terminal = new Contenido();
        Contenido contenidoVendido;
        Contenido totalInicial = new Contenido();
        Contenido totalTerminal = new Contenido();
        Contenido totalVendido = new Contenido();
        double totalDinero=0;
        Contenido mayor = new Contenido (0,0,0);
        Contenido menor = new Contenido (0,0,0);
        
        for (int r=0; r<jTableKiosco.getRowCount(); r++)
        {
            inicial.setGalones(Integer.parseInt(jTableKiosco.getValueAt(r, 1)+""));
            inicial.setPintas(Integer.parseInt(jTableKiosco.getValueAt(r, 2)+""));
            inicial.setOnzas(Integer.parseInt(jTableKiosco.getValueAt(r, 3)+""));
            
            totalInicial = totalInicial.suma(inicial);
            
            terminal.setGalones(Integer.parseInt(jTableKiosco.getValueAt(r, 4)+""));
            terminal.setPintas(Integer.parseInt(jTableKiosco.getValueAt(r, 5)+""));
            terminal.setOnzas(Integer.parseInt(jTableKiosco.getValueAt(r, 6)+""));
            
            totalTerminal = totalTerminal.suma(terminal);
            
            contenidoVendido = inicial.resta(terminal);
            
            jTableKiosco.setValueAt(contenidoVendido.getGalones(), r, 7);
            jTableKiosco.setValueAt(contenidoVendido.getPintas(), r, 8);
            jTableKiosco.setValueAt(contenidoVendido.getOnzas(), r, 9);
            
            jTableKiosco.setValueAt(contenidoVendido.Dinero(), r, 10);
            
            totalVendido = totalVendido.suma(contenidoVendido);
            totalDinero+= contenidoVendido.Dinero();
            
        }
        jTableTotales.setValueAt(totalInicial.toString(), 0, 0);
        jTableTotales.setValueAt(totalTerminal.toString(), 0, 1);
        jTableTotales.setValueAt(totalVendido.toString(), 0, 2);
        jTableTotales.setValueAt(totalDinero, 0, 3);
        
        ColorCeldas celdas = new ColorCeldas (jTableKiosco);
        for(int r=0; r<jTableKiosco.getRowCount(); r++)
            for(int c=0; c<jTableKiosco.getColumnCount(); c++)
                if()
//        ColorCeldas celdas = new ColorCeldas (jTableKiosco);
//        
//        for (int i = 0; i < jTableKiosco.getRowCount(); i++) 
//            for (int j = 0; j < jTableKiosco.getRowCount(); j++)
//            {
//                celdas.addCelda(i, j, Color.white);
//            }
//        
//        if (totalVendido.onzasTotales()>mayor.onzasTotales()) 
//           {
//               mayor = totalVendido;
//           }
//           if (r==0)
//           {
//             menor.setGalones(Integer.parseInt(jTableKiosco.getValueAt(0, 7)+""));
//             menor.setPintas(Integer.parseInt(jTableKiosco.getValueAt(0, 8)+""));
//             menor.setOnzas(Integer.parseInt(jTableKiosco.getValueAt(0, 9)+""));
//           }
//           if (totalVendido.onzasTotales()<menor.onzasTotales())
//           {
//               menor = totalVendido;
//           }
// 
//        }
//        
//        Contenido deposito = new Contenido();
//        for (int r = 0; r < jTableKiosco.getRowCount(); r++) 
//        {
//            deposito.setGalones(Integer.parseInt(jTableKiosco.getValueAt(r, 7)+""));
//            deposito.setPintas(Integer.parseInt(jTableKiosco.getValueAt(r, 8)+""));
//            deposito.setOnzas(Integer.parseInt(jTableKiosco.getValueAt(r, 9)+""));
//            
//            if (deposito.onzasTotales()== mayor.onzasTotales())
//            {
//                for (int i = 0; i < jTableKiosco.getColumnCount(); i++) 
//                    
//                celdas.addCelda(r, i, Color.yellow);
//                
//                celdas.repaint();
//            }
//            if (deposito.onzasTotales()== menor.onzasTotales())
//            {
//                for (int i = 0; i < jTableKiosco.getColumnCount(); i++) 
//           
//                celdas.addCelda(r, i, Color.red);
//                
//                celdas.repaint();
//            }
//        }
            
    }//GEN-LAST:event_jButCalcularActionPerformed

    private void jButEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemploActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel)jTableKiosco.getModel();
        modelo.setRowCount((int)4);
        jSpinKioscos.setValue(4);
        
            jTableKiosco.setValueAt("Galerias", 0, 0);
            
            //Contenido Inicial
            jTableKiosco.setValueAt(4, 0, 1); // Galones
            jTableKiosco.setValueAt(5, 0, 2); // Pintas
            jTableKiosco.setValueAt(14, 0, 3); // Onzas
            
            //Contenido Terminal
            jTableKiosco.setValueAt(2, 0, 4); // Galones
            jTableKiosco.setValueAt(7, 0, 5); // Pintas
            jTableKiosco.setValueAt(10, 0, 6); // Onzas     
            
            jTableKiosco.setValueAt("4 Caminos", 1, 0);
            
            //Contenido Inicial
            jTableKiosco.setValueAt(6, 1, 1); // Galones
            jTableKiosco.setValueAt(0, 1, 2); // Pintas
            jTableKiosco.setValueAt(0, 1, 3); // Onzas
            
            //Contenido Terminal
            jTableKiosco.setValueAt(1, 1, 4); // Galones
            jTableKiosco.setValueAt(6, 1, 5); // Pintas
            jTableKiosco.setValueAt(15, 1, 6); // Onzas   
            
            jTableKiosco.setValueAt("Fundadores", 2, 0);
            
            //Contenido Inicial
            jTableKiosco.setValueAt(5, 2, 1); // Galones
            jTableKiosco.setValueAt(7, 2, 2); // Pintas
            jTableKiosco.setValueAt(15, 2, 3); // Onzas
            
            //Contenido Terminal
            jTableKiosco.setValueAt(3, 2, 4); // Galones
            jTableKiosco.setValueAt(0, 2, 5); // Pintas
            jTableKiosco.setValueAt(0, 2, 6); // Onzas   
            
            jTableKiosco.setValueAt("Plaza Imagen", 3, 0);
            
            //Contenido Inicial
            jTableKiosco.setValueAt(3, 3, 1); // Galones
            jTableKiosco.setValueAt(1, 3, 2); // Pintas
            jTableKiosco.setValueAt(4, 3, 3); // Onzas
            
            //Contenido Terminal
            jTableKiosco.setValueAt(3, 3, 4); // Galones
            jTableKiosco.setValueAt(0, 3, 5); // Pintas
            jTableKiosco.setValueAt(2, 3, 6); // Onzas
        
    }//GEN-LAST:event_jButEjemploActionPerformed

    private void jButArregloEncapsuladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButArregloEncapsuladoActionPerformed
        // TODO add your handling code here:
        Kiosco cimaco = new Kiosco(jTableKiosco.getRowCount());
               
        Contenido inicial, terminal;
        
        for(int r=0; r<jTableKiosco.getRowCount(); r++)
        {
            inicial = new Contenido(Integer.parseInt(jTableKiosco.getValueAt(r, 1)+""),
                                    Integer.parseInt(jTableKiosco.getValueAt(r, 2)+""),
                                    Integer.parseInt(jTableKiosco.getValueAt(r, 3)+""));
            
            terminal = new Contenido(Integer.parseInt(jTableKiosco.getValueAt(r, 4)+""),
                                    Integer.parseInt(jTableKiosco.getValueAt(r, 5)+""),
                                    Integer.parseInt(jTableKiosco.getValueAt(r, 6)+""));
            
            cimaco.setPerfume(new Perfume(jTableKiosco.getValueAt(r, 0)+"",
                              inicial, terminal), r);
        }
        
        cimaco.ordenar();
        
        for (int r=0; r<cimaco.getTamaño(); r++)
        {
            jTableKiosco.setValueAt(cimaco.getPerfume(r).getNombre(), r, 0);
            
            jTableKiosco.setValueAt(cimaco.getPerfume(r).getContenidoInicial().getGalones(), r, 1);
            jTableKiosco.setValueAt(cimaco.getPerfume(r).getContenidoInicial().getPintas(), r, 2);
            jTableKiosco.setValueAt(cimaco.getPerfume(r).getContenidoInicial().getOnzas(), r, 3);

            jTableKiosco.setValueAt(cimaco.getPerfume(r).getContenidoTerminal().getGalones(), r, 4);
            jTableKiosco.setValueAt(cimaco.getPerfume(r).getContenidoTerminal().getPintas(), r, 5);
            jTableKiosco.setValueAt(cimaco.getPerfume(r).getContenidoTerminal().getOnzas(), r, 6);

            jTableKiosco.setValueAt(cimaco.getPerfume(r).contenidoVendido().getGalones(), r, 7);
            jTableKiosco.setValueAt(cimaco.getPerfume(r).contenidoVendido().getPintas(), r, 8);
            jTableKiosco.setValueAt(cimaco.getPerfume(r).contenidoVendido().getOnzas(), r, 9);
            
            jTableKiosco.setValueAt(cimaco.getPerfume(r).Dinero(), r, 10);
        }
    }//GEN-LAST:event_jButArregloEncapsuladoActionPerformed

    private void jButOrdenDescendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButOrdenDescendenteActionPerformed
        // TODO add your handling code here:
        Perfume [] tienda = new Perfume[jTableKiosco.getRowCount()];
        
        Contenido entrada = new Contenido();
        Contenido salida = new Contenido();
        
        for (int r=0; r<tienda.length; r++)
        {
            entrada.setGalones(Integer.parseInt(jTableKiosco.getValueAt(r, 1)+""));
            entrada.setPintas(Integer.parseInt(jTableKiosco.getValueAt(r, 2)+""));
            entrada.setOnzas(Integer.parseInt(jTableKiosco.getValueAt(r, 3)+""));

            salida.setGalones(Integer.parseInt(jTableKiosco.getValueAt(r, 4)+""));
            salida.setPintas(Integer.parseInt(jTableKiosco.getValueAt(r, 5)+""));
            salida.setOnzas(Integer.parseInt(jTableKiosco.getValueAt(r, 6)+""));
            
            tienda[r] = new Perfume(jTableKiosco.getValueAt(r, 0)+"",
                                      entrada,salida);
        }
        
        for (int i=0; i<tienda.length-1; i++)
            for (int j=i+1; j<tienda.length; j++)
                if (tienda[i].contenidoVendido().onzasTotales()<
                    tienda[j].contenidoVendido().onzasTotales())
                {
                    Perfume aux = tienda[i];
                    tienda[i] = tienda[j];
                    tienda[j] = aux;
                }
        
        for (int r=0; r<tienda.length; r++)
        {
            jTableKiosco.setValueAt(tienda[r].getNombre(), r, 0);
            
            jTableKiosco.setValueAt(tienda[r].getContenidoInicial().getGalones(), r, 1);
            jTableKiosco.setValueAt(tienda[r].getContenidoInicial().getPintas(), r, 2);
            jTableKiosco.setValueAt(tienda[r].getContenidoInicial().getOnzas(), r, 3);

            jTableKiosco.setValueAt(tienda[r].getContenidoTerminal().getGalones(), r, 4);
            jTableKiosco.setValueAt(tienda[r].getContenidoTerminal().getPintas(), r, 5);
            jTableKiosco.setValueAt(tienda[r].getContenidoTerminal().getOnzas(), r, 6);

            jTableKiosco.setValueAt(tienda[r].contenidoVendido().getGalones(), r, 7);
            jTableKiosco.setValueAt(tienda[r].contenidoVendido().getPintas(), r, 8);
            jTableKiosco.setValueAt(tienda[r].contenidoVendido().getOnzas(), r, 9);
            
            jTableKiosco.setValueAt(tienda[r].contenidoVendido().Dinero(), r, 10);
        }
    }//GEN-LAST:event_jButOrdenDescendenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PB_17131621_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PB_17131621_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PB_17131621_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PB_17131621_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PB_17131621_Frame_01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorio;
    private javax.swing.JButton jButArregloEncapsulado;
    private javax.swing.JButton jButCalcular;
    private javax.swing.JButton jButEjemplo;
    private javax.swing.JButton jButOrdenDescendente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinKioscos;
    private javax.swing.JTable jTableKiosco;
    private javax.swing.JTable jTableTotales;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
