package app;

import clase.Conexion;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kobura Quiroz
 */

public class PrincipalFrame extends javax.swing.JFrame {
    public static final String NUEVO = "Nuevo";
    public static final String EDITAR = "Editar";

    public static final String TIT_FRAME   = "Caivul System";
    public static final String TIT_MODULO1 = "Jefes";
    public static final String TIT_MODULO2 = "Sucursales";
    public static final String TIT_MODULO3 = "Empleados";
    public static final String TIT_MODULO4 = "Clientes";
    public static final String TIT_MODULO5 = "Pasillos";
    public static final String TIT_INICIO  = "Caivul System";
    private String moduloActual;
    private DefaultTableModel dtmPrincipal;
    Conexion objcon= new Conexion();
    public PrincipalFrame(boolean usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.setTitle(TIT_FRAME);
        jLabelMensajeDelSistema.setText("");
        jToolBarPrincipal.setVisible(false);
        jPanelTabla.setVisible(false);
        jPanelLogoPrincipal.setVisible(true);
        jLabelLeyendaPrincipal.setText(TIT_INICIO);
        jLabelModulo1.setText(TIT_MODULO1);
        jLabelModulo2.setText(TIT_MODULO2);
        jLabelModulo3.setText(TIT_MODULO3);
        jLabelModulo4.setText(TIT_MODULO4);
        jLabelModulo5.setText(TIT_MODULO5);
        
        if (usuario == false) {
            jButtonNuevo.setVisible(false);
            jButtonEditar.setVisible(false);
            jButtonEliminar.setVisible(false);
        } 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jToolBarPrincipal = new javax.swing.JToolBar();
        jButtonNuevo = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonInicio = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jPanel1 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel4 = new javax.swing.JLabel();
        jLabelEstatusConexion = new javax.swing.JLabel();
        jToolBar3 = new javax.swing.JToolBar();
        jLabelMensajeDelSistema = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jButtonModulo1 = new javax.swing.JButton();
        jButtonModulo2 = new javax.swing.JButton();
        jButtonModulo3 = new javax.swing.JButton();
        jLabelModulo1 = new javax.swing.JLabel();
        jLabelModulo2 = new javax.swing.JLabel();
        jLabelModulo3 = new javax.swing.JLabel();
        jLabelModulo4 = new javax.swing.JLabel();
        jButtonModulo4 = new javax.swing.JButton();
        jLabelModulo5 = new javax.swing.JLabel();
        jButtonModulo5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelLeyendaPrincipal = new javax.swing.JLabel();
        jPanelTabla = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePrincipal = new javax.swing.JTable();
        jPanelLogoPrincipal = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMIAcercaDe = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setIconImages(getIconImages());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jToolBarPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBarPrincipal.setFloatable(false);
        jToolBarPrincipal.setRollover(true);

        jButtonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar-archivo2.png"))); // NOI18N
        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.setToolTipText("Nuevo");
        jButtonNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonNuevo.setFocusable(false);
        jButtonNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });
        jToolBarPrincipal.add(jButtonNuevo);

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setFocusable(false);
        jButtonEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jToolBarPrincipal.add(jButtonEditar);

        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/eliminar.png"))); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setFocusable(false);
        jButtonEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jToolBarPrincipal.add(jButtonEliminar);

        jButtonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pagina-de-inicio2.png"))); // NOI18N
        jButtonInicio.setText("Inicio");
        jButtonInicio.setFocusable(false);
        jButtonInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonInicio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioActionPerformed(evt);
            }
        });
        jToolBarPrincipal.add(jButtonInicio);
        jToolBarPrincipal.add(jSeparator1);

        jToolBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jLabel4.setText("Estatus de la conexión: ");
        jToolBar2.add(jLabel4);

        jLabelEstatusConexion.setText("<estatus>");
        jToolBar2.add(jLabelEstatusConexion);

        jToolBar3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar3.setFloatable(false);
        jToolBar3.setRollover(true);

        jLabelMensajeDelSistema.setText("<mensajes>");
        jToolBar3.add(jLabelMensajeDelSistema);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2.setAutoscrolls(true);

        jButtonModulo1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonModulo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/jefe_b1.png"))); // NOI18N
        jButtonModulo1.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonModulo1.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonModulo1.setOpaque(false);
        jButtonModulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModulo1ActionPerformed(evt);
            }
        });

        jButtonModulo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/tienda_b1.png"))); // NOI18N
        jButtonModulo2.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonModulo2.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonModulo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModulo2ActionPerformed(evt);
            }
        });

        jButtonModulo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/empleados_b1.png"))); // NOI18N
        jButtonModulo3.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonModulo3.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonModulo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModulo3ActionPerformed(evt);
            }
        });

        jLabelModulo1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelModulo1.setText("Modulo 1");

        jLabelModulo2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelModulo2.setText("Modulo 2");

        jLabelModulo3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelModulo3.setText("Modulo 3");

        jLabelModulo4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelModulo4.setText("Modulo 4");

        jButtonModulo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cliente_b1.png"))); // NOI18N
        jButtonModulo4.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonModulo4.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonModulo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModulo4ActionPerformed(evt);
            }
        });

        jLabelModulo5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelModulo5.setText("Modulo 5");

        jButtonModulo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/supermercado_b1.png"))); // NOI18N
        jButtonModulo5.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonModulo5.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonModulo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModulo5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonModulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(jLabelModulo1))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jButtonModulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(jLabelModulo2))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jButtonModulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(jLabelModulo3))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jButtonModulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(jLabelModulo4))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jButtonModulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jLabelModulo5))))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonModulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelModulo1)
                .addGap(23, 23, 23)
                .addComponent(jButtonModulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabelModulo2)
                .addGap(33, 33, 33)
                .addComponent(jButtonModulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabelModulo3)
                .addGap(18, 18, 18)
                .addComponent(jButtonModulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabelModulo4)
                .addGap(28, 28, 28)
                .addComponent(jButtonModulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabelModulo5))
        );

        jScrollPane1.setViewportView(jPanel2);

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));

        jLabelLeyendaPrincipal.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelLeyendaPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLeyendaPrincipal.setText("Modulo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelLeyendaPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLeyendaPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTabla.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTablePrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablePrincipal);

        javax.swing.GroupLayout jPanelTablaLayout = new javax.swing.GroupLayout(jPanelTabla);
        jPanelTabla.setLayout(jPanelTablaLayout);
        jPanelTablaLayout.setHorizontalGroup(
            jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanelTablaLayout.setVerticalGroup(
            jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/tienda2.png"))); // NOI18N

        javax.swing.GroupLayout jPanelLogoPrincipalLayout = new javax.swing.GroupLayout(jPanelLogoPrincipal);
        jPanelLogoPrincipal.setLayout(jPanelLogoPrincipalLayout);
        jPanelLogoPrincipalLayout.setHorizontalGroup(
            jPanelLogoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLogoPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE))
        );
        jPanelLogoPrincipalLayout.setVerticalGroup(
            jPanelLogoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogoPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        jMenuItem8.setText("Diagrama de Clases");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMIAcercaDe.setText("Ayuda");

        jMenuItem2.setText("Acerca De");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMIAcercaDe.add(jMenuItem2);

        jMenuItem10.setText("Buscar mi tienda");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMIAcercaDe.add(jMenuItem10);

        jMenuItem11.setText("Administrador de pasillos");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMIAcercaDe.add(jMenuItem11);

        jMenuBar1.add(jMIAcercaDe);

        jMenu2.setText("Herramientas");

        jMenuItem3.setText("Ver Encargados en Torreón");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Ver Encargados en Gómez");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem9.setText("Ver Jefes De Sucursales");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem6.setText("Encargados sin ubicación");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Atención a clientes");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBarPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelLogoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelLogoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        AcercaDeDialog acercaDe = new AcercaDeDialog(this, true);
        acercaDe.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButtonModulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModulo1ActionPerformed
        prepararVistaModulo(TIT_MODULO1);
        try {
            objcon.mosrarDatosJefe(jTablePrincipal);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonModulo1ActionPerformed

    private void jButtonModulo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModulo2ActionPerformed
        prepararVistaModulo(TIT_MODULO2);
        try {
            objcon.mosrarDatosSucursal(jTablePrincipal);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonModulo2ActionPerformed

    private void jButtonModulo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModulo3ActionPerformed
        prepararVistaModulo(TIT_MODULO3);
        try {
            objcon.mosrarDatosEmpleado(jTablePrincipal);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonModulo3ActionPerformed

    private void jButtonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioActionPerformed
        jToolBarPrincipal.setVisible(false);
        jPanelLogoPrincipal.setVisible(true);
        jPanelTabla.setVisible(false);
        
        jLabelLeyendaPrincipal.setText(TIT_INICIO);
        moduloActual = "";
    }//GEN-LAST:event_jButtonInicioActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        int pos = jTablePrincipal.getSelectedRow();
        if (pos == -1) {
            JOptionPane.showMessageDialog(this, "No hay un registro seleccionado", 
                    "Eliminar", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String id =(String) this.jTablePrincipal.getValueAt(this.jTablePrincipal.getSelectedRow(),0); 
        switch (moduloActual) {
            case TIT_MODULO1:
                try {
                    objcon.delJefe(id);
                    objcon.mosrarDatosEmpleado(jTablePrincipal);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex, "Error", JOptionPane.ERROR_MESSAGE);
                }
                break;
            case TIT_MODULO3:
                try {
                    objcon.delEmpleado(id);
                    objcon.mosrarDatosEmpleado(jTablePrincipal);
                } catch (SQLException ex) {
                    Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
                
            case TIT_MODULO4:
                try {
                    objcon.delCliente(id);
                    objcon.mosrarDatosCliente(jTablePrincipal);
                } catch (SQLException ex) {
                    Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
                
            case TIT_MODULO5:
                try {
                    objcon.delPasillo(id);
                    objcon.mosrarDatosPasillo(jTablePrincipal);
                } catch (SQLException ex) {
                    Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
               break;
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        switch (moduloActual) {
            case TIT_MODULO1: 
                Modulo1EditarDialog dialog1 = null;
        try {
            dialog1 = new Modulo1EditarDialog(true);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
                dialog1.setVisible(true);
                break;
            case TIT_MODULO2:
                Modulo2EditarDialog dialog2 = null;
        try {
            dialog2 = new Modulo2EditarDialog(true);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
                dialog2.setVisible(true);
                break;
            case TIT_MODULO3:
                Modulo3EditarDialog dialog3 = null;
        try {
            dialog3 = new Modulo3EditarDialog(true);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
                dialog3.setVisible(true);
                break;
            case TIT_MODULO4:
                Modulo4EditarDialog dialog4 = null;
        try {
            dialog4 = new Modulo4EditarDialog(true);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
                dialog4.setVisible(true);
                break;
            case TIT_MODULO5:
                Modulo5EditarDialog dialog5 = null;
        try {
            dialog5 = new Modulo5EditarDialog(true);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
                dialog5.setVisible(true);
                break;
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        switch (moduloActual) {
            case TIT_MODULO1: 
                Modulo1EditarDialog dialog1 = null;
        try {
            dialog1 = new Modulo1EditarDialog(false);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
                dialog1.setVisible(true);
                break;
            case TIT_MODULO2:
                Modulo2EditarDialog dialog2 = null;
        try {
            dialog2 = new Modulo2EditarDialog(false);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
                dialog2.setVisible(true);
                break;
            case TIT_MODULO3:
                Modulo3EditarDialog dialog3 = null;
        try {
            dialog3 = new Modulo3EditarDialog(false);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
                dialog3.setVisible(true);
                break;
            case TIT_MODULO4:
                Modulo4EditarDialog dialog4 = null;
        try {
            dialog4 = new Modulo4EditarDialog(false);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
                dialog4.setVisible(true);
                break;
            case TIT_MODULO5:
                Modulo5EditarDialog dialog5 = null;
        try {
            dialog5 = new Modulo5EditarDialog(false);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
                dialog5.setVisible(true);
                break;
        }
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonModulo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModulo4ActionPerformed
        prepararVistaModulo(TIT_MODULO4);
        try {
            objcon.mosrarDatosCliente(jTablePrincipal);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonModulo4ActionPerformed

    private void jButtonModulo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModulo5ActionPerformed
        prepararVistaModulo(TIT_MODULO5);
        try {
            objcon.mosrarDatosPasillo(jTablePrincipal);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonModulo5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jButtonModulo1.doClick();
        try {
            objcon.EncargadosTorreon(jTablePrincipal);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        jButtonModulo1.doClick();
        try {
            objcon.EncargadosGomez(jTablePrincipal);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        jButtonModulo1.doClick();
        try {
            objcon.EncargadosSinUbicacion(jTablePrincipal);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        jButtonModulo3.doClick();
        try {
            objcon.AtencioClientes(jTablePrincipal);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        DiagramaDeClases diagrama = new DiagramaDeClases(this, true);
        diagrama.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        jButtonModulo1.doClick();
        try {
            objcon.JefesSucursal(jTablePrincipal);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        String correo = JOptionPane.showInputDialog("Ingresa tu correo electronico.");
        try {
            objcon.buscarMiTienda(correo);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        String Administrador = JOptionPane.showInputDialog("Ingresa el ID del trabajador.");
        try {
            objcon.buscarAdministradorPasillo(Administrador);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed
    
    //--------------------------------------------------------------------------
    // MÉTODO PARA LA VISTA DE CADA SECCIÓN
    private void prepararVistaModulo(String modulo){
        moduloActual = modulo;
        jToolBarPrincipal.setVisible(true);
        jPanelLogoPrincipal.setVisible(false);
        jPanelTabla.setVisible(true);
        
        jLabelLeyendaPrincipal.setText(modulo);
        
        dtmPrincipal = new DefaultTableModel();
        jTablePrincipal.setModel(dtmPrincipal);
    }
    
    //---------------------------------------------
    //Metodo para crear la base de datos
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFrame(true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JButton jButtonModulo1;
    private javax.swing.JButton jButtonModulo2;
    private javax.swing.JButton jButtonModulo3;
    private javax.swing.JButton jButtonModulo4;
    private javax.swing.JButton jButtonModulo5;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelEstatusConexion;
    private javax.swing.JLabel jLabelLeyendaPrincipal;
    private javax.swing.JLabel jLabelMensajeDelSistema;
    private javax.swing.JLabel jLabelModulo1;
    private javax.swing.JLabel jLabelModulo2;
    private javax.swing.JLabel jLabelModulo3;
    private javax.swing.JLabel jLabelModulo4;
    private javax.swing.JLabel jLabelModulo5;
    private javax.swing.JMenu jMIAcercaDe;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelLogoPrincipal;
    private javax.swing.JPanel jPanelTabla;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTable jTablePrincipal;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBarPrincipal;
    // End of variables declaration//GEN-END:variables

}
