/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_2019_03_27_aplicacionnominaempleados;

import java.awt.Color;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alope
 */
public class JFrameRegistro extends javax.swing.JFrame {

    /**
     * Creates new form JFrameRegistro
     */
    JFrameMenu jfMenu;
    MiRandom azar = new MiRandom();
    
    public JFrameRegistro(JFrameMenu jfm) {
        initComponents();
        
        jfMenu = jfm;
        
        jRBEmpleado.setSelected(true);
        ocultar();
        
        jLabEmpReg.setText(jfMenu.getEmpleadosRegistrados()+"");
        jLabEmpTot.setText("Capacidad: "+jfMenu.getTamaño()+
                           "    Vacantes: "+(jfMenu.getTamaño()-jfMenu.getEmpleadosRegistrados()));
    }

    public void ocultar()
    {
        jLabPiezas.setVisible(false);
        jLabPrecio.setVisible(false);
        jLabVentas.setVisible(false);
        jLabComision.setVisible(false);
        jLabDias.setVisible(false);
        jLabSueldo.setVisible(false);
        jLabBono.setVisible(false);

        jTextPiezas.setVisible(false);
        jTextPrecio.setVisible(false);
        jTextVentas.setVisible(false);
        jTextComision.setVisible(false);
        jTextDias.setVisible(false);
        jTextSueldo.setVisible(false);
        jTextBono.setVisible(false);
        
        jTextNumero.setText("");
        jTextNombre.setText("");
        jTextPiezas.setText("");
        jTextPrecio.setText("");
        jTextVentas.setText("");
        jTextComision.setText("");
        jTextDias.setText("");
        jTextSueldo.setText("");
        jTextBono.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabEmpReg = new javax.swing.JLabel();
        jRBEmpleado = new javax.swing.JRadioButton();
        jRBTaller = new javax.swing.JRadioButton();
        jRBVentas = new javax.swing.JRadioButton();
        jRBAdmin = new javax.swing.JRadioButton();
        jRBEjecutivo = new javax.swing.JRadioButton();
        jButAleatorios = new javax.swing.JButton();
        jButGrabar = new javax.swing.JButton();
        jButCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextNumero = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextPiezas = new javax.swing.JTextField();
        jTextPrecio = new javax.swing.JTextField();
        jLabPrecio = new javax.swing.JLabel();
        jLabPiezas = new javax.swing.JLabel();
        jTextVentas = new javax.swing.JTextField();
        jTextComision = new javax.swing.JTextField();
        jLabComision = new javax.swing.JLabel();
        jLabVentas = new javax.swing.JLabel();
        jTextDias = new javax.swing.JTextField();
        jTextSueldo = new javax.swing.JTextField();
        jLabSueldo = new javax.swing.JLabel();
        jLabDias = new javax.swing.JLabel();
        jTextBono = new javax.swing.JTextField();
        jLabBono = new javax.swing.JLabel();
        jLabEmpTot = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Registro de empleados");

        jButRegresar.setText("Regresar");
        jButRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegresarActionPerformed(evt);
            }
        });

        jLabel2.setText("Empleados registrados");

        jLabEmpReg.setBackground(new java.awt.Color(255, 255, 0));
        jLabEmpReg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabEmpReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabEmpReg.setOpaque(true);

        buttonGroup1.add(jRBEmpleado);
        jRBEmpleado.setText("Empleado");
        jRBEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBEmpleadoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBTaller);
        jRBTaller.setText("Taller");
        jRBTaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBTallerActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBVentas);
        jRBVentas.setText("Ventas");
        jRBVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBVentasActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBAdmin);
        jRBAdmin.setText("Administrativo");
        jRBAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBAdminActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBEjecutivo);
        jRBEjecutivo.setText("Ejecutivo");
        jRBEjecutivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBEjecutivoActionPerformed(evt);
            }
        });

        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jButGrabar.setText("Grabar");
        jButGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButGrabarActionPerformed(evt);
            }
        });

        jButCancelar.setText("Cancelar");

        jLabel3.setText("Número");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });

        jLabel4.setText("Nombre");

        jLabPrecio.setText("Precio unitario $");

        jLabPiezas.setText("Piezas");

        jLabComision.setText("%Comisión");

        jLabVentas.setText("Ventas $");

        jLabSueldo.setText("Sueldo diario $");

        jLabDias.setText("Días trabajados");

        jLabBono.setText("Bono $");

        jLabEmpTot.setBackground(new java.awt.Color(51, 255, 255));
        jLabEmpTot.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabEmpTot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabEmpTot.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRBEmpleado)
                        .addGap(30, 30, 30)
                        .addComponent(jRBTaller)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBVentas)
                        .addGap(18, 18, 18)
                        .addComponent(jRBAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBEjecutivo)
                        .addGap(317, 317, 317))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabPiezas)
                            .addGap(18, 18, 18)
                            .addComponent(jTextPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(672, 672, 672))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabVentas)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(161, 161, 161)
                                        .addComponent(jLabComision)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextComision, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabPrecio)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(457, 457, 457)))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButCancelar)
                            .addGap(6, 6, 6))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabDias)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextDias, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(jLabSueldo)
                                    .addGap(22, 22, 22)
                                    .addComponent(jTextSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(30, 30, 30)
                                    .addComponent(jLabEmpReg, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabBono)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextBono, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButRegresar)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButAleatorios)
                                .addGap(41, 41, 41)
                                .addComponent(jButGrabar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jLabEmpTot, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBEmpleado)
                    .addComponent(jRBTaller)
                    .addComponent(jRBVentas)
                    .addComponent(jRBAdmin)
                    .addComponent(jRBEjecutivo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabPiezas)
                    .addComponent(jTextPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabPrecio)
                    .addComponent(jTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabVentas)
                    .addComponent(jTextVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabComision)
                    .addComponent(jTextComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabDias)
                    .addComponent(jTextDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabSueldo)
                    .addComponent(jTextSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabBono)
                    .addComponent(jTextBono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButAleatorios)
                    .addComponent(jButGrabar)
                    .addComponent(jButCancelar))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButRegresar)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabEmpReg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabEmpTot, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegresarActionPerformed
        // TODO add your handling code here:
        FileWriter fw = null;
        PrintWriter pw = null;
        
        try {
            fw = new FileWriter(jfMenu.getArchivo());
            pw = new PrintWriter(fw);
            
            pw.println(jfMenu.getEmpleadosRegistrados());
            
            Empleado emp;
            String clase;
            
            for(int i=0; i<jfMenu.getEmpleadosRegistrados(); i++)
            {
                emp = jfMenu.getEmpleado(i);
                clase = emp.getClass().getSimpleName();
                
                if(clase.equals("Empleado"))
                {
                    pw.println("E");
                    pw.println(emp.getNumero());
                    pw.println(emp.getNombre());
                }
                
                if(clase.equals("Taller"))
                {
                    Taller t = (Taller)emp;
                    
                    pw.println("T");
                    pw.println(emp.getNumero());
                    pw.println(emp.getNombre());
                    pw.println(t.getPiezas());
                    pw.println(t.getPrecioUnitario());
                }

                if(clase.equals("Administrativo"))
                {
                    Administrativo a = (Administrativo)emp;
                    
                    pw.println("A");
                    pw.println(emp.getNumero());
                    pw.println(emp.getNombre());
                    pw.println(a.getDiasTrabajados());
                    pw.println(a.getSueldoDiario());
                }
                
                if(clase.equals("Ejecutivo"))
                {
                    Ejecutivo e = (Ejecutivo)emp;
                    
                    pw.println("EJ");
                    pw.println(emp.getNumero());
                    pw.println(emp.getNombre());
                    pw.println(e.getDiasTrabajados());
                    pw.println(e.getSueldoDiario());
                    pw.println(e.getBono());
                }
                
                if(clase.equals("Ventas"))
                {
                    Ventas v = (Ventas)emp;
                    
                    pw.println("V");
                    pw.println(emp.getNumero());
                    pw.println(emp.getNombre());
                    pw.println(v.getVentasTotales());
                    pw.println(v.getComision());
                }
            }
            
        } catch (IOException ex) {
            Logger.getLogger(JFrameRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            if(pw != null)
                pw.close();
            
            if(fw != null)
                try {
                    fw.close();
            } catch (IOException ex) {
                Logger.getLogger(JFrameRegistro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        dispose();
        
        jfMenu.getEtiqueta().setBackground(Color.BLUE);

        jfMenu.setVisible(true);        
    }//GEN-LAST:event_jButRegresarActionPerformed

    private void jRBEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBEmpleadoActionPerformed
        // TODO add your handling code here:
        ocultar();
    }//GEN-LAST:event_jRBEmpleadoActionPerformed

    private void jRBTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBTallerActionPerformed
        // TODO add your handling code here:
        ocultar();
        
        jLabPiezas.setVisible(true);
        jLabPrecio.setVisible(true);

        jTextPiezas.setVisible(true);
        jTextPrecio.setVisible(true);
    }//GEN-LAST:event_jRBTallerActionPerformed

    private void jRBVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBVentasActionPerformed
        // TODO add your handling code here:
        ocultar();
        
        jLabVentas.setVisible(true);
        jLabComision.setVisible(true);

        jTextVentas.setVisible(true);
        jTextComision.setVisible(true);
    }//GEN-LAST:event_jRBVentasActionPerformed

    private void jRBAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBAdminActionPerformed
        // TODO add your handling code here:
        ocultar();
        
        jLabDias.setVisible(true);
        jLabSueldo.setVisible(true);

        jTextDias.setVisible(true);
        jTextSueldo.setVisible(true);
    }//GEN-LAST:event_jRBAdminActionPerformed

    private void jRBEjecutivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBEjecutivoActionPerformed
        // TODO add your handling code here:
        ocultar();
        
        jLabDias.setVisible(true);
        jLabSueldo.setVisible(true);
        jLabBono.setVisible(true);
        
        jTextDias.setVisible(true);
        jTextSueldo.setVisible(true);
        jTextBono.setVisible(true);
    }//GEN-LAST:event_jRBEjecutivoActionPerformed

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        // TODO add your handling code here:
        
        jTextNumero.setText(azar.nextInt(1,1000)+"");
        jTextNombre.setText(azar.nextNombreLegal());
        
        jTextPiezas.setText(azar.nextInt(100,1000)+"");
        jTextPrecio.setText(azar.nextDouble(3,10,.25)+"");

        jTextVentas.setText(azar.nextInt(5000, 70000, 1000)+"");
        jTextComision.setText(azar.nextDouble(2,8,.2)+"");
        
        jTextDias.setText(azar.nextInt(6, 30)+"");
        jTextSueldo.setText(azar.nextInt(102, 600)+"");
        jTextBono.setText(azar.nextInt(2000, 20000, 500)+"");
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jButGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButGrabarActionPerformed
        // TODO add your handling code here:
        int numero = Integer.parseInt(jTextNumero.getText());
        String nombre = jTextNombre.getText();
        
        if (jRBEmpleado.isSelected())
        {
            Empleado emp = new Empleado(numero,nombre);
            jfMenu.agregarEmpleado(emp);
        }
        
        if (jRBTaller.isSelected())
        {
            Taller tal = new Taller(numero,nombre,
                                    Integer.parseInt(jTextPiezas.getText()),
                                    Double.parseDouble(jTextPrecio.getText()));
            
            jfMenu.agregarEmpleado(tal);
        }
        
        if (jRBVentas.isSelected())
        {
            Ventas ven = new Ventas(numero,nombre,
                                    Double.parseDouble(jTextVentas.getText()),
                                    Double.parseDouble(jTextComision.getText()));
            
            jfMenu.agregarEmpleado(ven);
        }
        
        if (jRBAdmin.isSelected())
        {
            Administrativo adm = new Administrativo(numero,nombre,
                                     Integer.parseInt(jTextDias.getText()),
                                     Double.parseDouble(jTextSueldo.getText()));
            
            jfMenu.agregarEmpleado(adm);
        }
        
        if (jRBEjecutivo.isSelected())
        {
            Ejecutivo eje = new Ejecutivo(numero,nombre,
                                     Integer.parseInt(jTextDias.getText()),
                                     Double.parseDouble(jTextSueldo.getText()),
                                     Double.parseDouble(jTextBono.getText()));
            
            jfMenu.agregarEmpleado(eje);
        }
        
        jLabEmpReg.setText(jfMenu.getEmpleadosRegistrados()+"");
        jfMenu.ampliarArreglo();
        jLabEmpTot.setText("Capacidad: "+jfMenu.getTamaño()+
                           "    Vacantes: "+(jfMenu.getTamaño()-jfMenu.getEmpleadosRegistrados()));
    }//GEN-LAST:event_jButGrabarActionPerformed

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:

        for (int i=1; i<=7; i++)
        {
            switch(azar.nextInt(5))
            {
                case 0: jRBEmpleado.setSelected(true); break;
                case 1: jRBTaller.setSelected(true); break;
                case 2: jRBVentas.setSelected(true); break;
                case 3: jRBAdmin.setSelected(true); break;
                case 4: jRBEjecutivo.setSelected(true); break;
            }

            jButAleatorios.doClick();
            jButGrabar.doClick();
        }
    }//GEN-LAST:event_jLabel3MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameRegistro(new JFrameMenu()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButCancelar;
    private javax.swing.JButton jButGrabar;
    private javax.swing.JButton jButRegresar;
    private javax.swing.JLabel jLabBono;
    private javax.swing.JLabel jLabComision;
    private javax.swing.JLabel jLabDias;
    private javax.swing.JLabel jLabEmpReg;
    private javax.swing.JLabel jLabEmpTot;
    private javax.swing.JLabel jLabPiezas;
    private javax.swing.JLabel jLabPrecio;
    private javax.swing.JLabel jLabSueldo;
    private javax.swing.JLabel jLabVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRBAdmin;
    private javax.swing.JRadioButton jRBEjecutivo;
    private javax.swing.JRadioButton jRBEmpleado;
    private javax.swing.JRadioButton jRBTaller;
    private javax.swing.JRadioButton jRBVentas;
    private javax.swing.JTextField jTextBono;
    private javax.swing.JTextField jTextComision;
    private javax.swing.JTextField jTextDias;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextPiezas;
    private javax.swing.JTextField jTextPrecio;
    private javax.swing.JTextField jTextSueldo;
    private javax.swing.JTextField jTextVentas;
    // End of variables declaration//GEN-END:variables
}
